### ISSUE TITLE
Significantly slower crew remove performance

### ISSUE THREAD

**Issue by Zopolis4** [chromebrew/chromebrew#10102]
The current method of checking for conflicts when removing a package is much slower than the previous version, probably because we use ruby to iterate through the file rather than passing it to grep. 

Master:
```
$ time crew remove qt5_base
qt5_base removed!

real    0m17.970s
user    0m8.586s
sys     0m9.207s
```

Before #9529:
```
$ time crew remove qt5_base
Checking for conflicts of qt5_base with files from installed packages...
Qt5_base removed!

real    0m1.669s
user    0m1.021s
sys     0m0.278s
```

**Comment by satmandu** [comment]
grep is insanely fast.  IIRC, I was using `grep` over the ruby functions for exactly that reason, I forget if for this though...

**Comment by uberhacker** [comment]
> Agree that this is insanely slow.
> 
> In my container I see:
> 
> ```
> chronos@cheekon-x86_64 /usr/local/lib/crew/packages (master >|SPARSE)$ time crew remove qt5_base
> qt5_base removed!
> 
> real	0m23.960s
> user	0m11.265s
> sys	0m11.931s
> ```

If it's slow on x86_64, imagine how much slower it is on emulated arm.

**Comment by satmandu** [comment]
Maybe this is better?
```
qt5_base removed!

real   0m0.982s
user   0m0.737s
sys    0m0.166s
chronos@cheekon-x86_64 /usr/local/lib/crew/packages (master >|SPARSE)$ 
```
