### ISSUE TITLE
🐞 Bug: QT issue

### ISSUE THREAD

**Issue by mcagabe19** [chromebrew/chromebrew#10138]
**Describe the bug**
Every QT apps gives symbol lookup error

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was crosh:

2. I executed the command(s) below:
      ```shell
       ./Minecraft_Bedrock_Launcher-x86_64-v0.15.2.796.AppImage
      ```

      Output:

      ```
      ./Minecraft_Bedrock_Launcher-x86_64-v0.15.2.796.AppImage: symbol lookup error: /usr/local/lib64/libQt5Core.so.5: undefined symbol: u_strToLower_73
      ```
**Expected behavior**
To Minecraft Bedrock Launcher Start

**Screenshots**
![image](https://github.com/user-attachments/assets/ab1bbe18-5271-4ad4-8f9e-afe4a9dbd4b6)

**System Information:**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.49.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 73a659f29 `Go 1.22.4 => 1.22.5 (#10130) (26 hours ago)`

- OS variant: `Chrome OS`
- OS version: `volteer-release/R126-15886.44.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**
Nothing

**Comment by Zopolis4** [comment]
Qt needs to be rebuilt against the latest ICU-- the progress on that can be tracked on [my branch](github.com/Zopolis4/chromebrew/tree/graceless), [this PR](https://invent.kde.org/qt/qt/qtbase/-/merge_requests/326), and [this issue](https://github.com/chromebrew/chromebrew/issues/10088).

**Comment by mcagabe19** [comment]
so we can mark this duplicate of 10088th issue
