### ISSUE TITLE
🐞 Bug There appears to be a problem upgrading fake packages

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#10148]
While running `crew upgrade`, the process is seemingly caught in an endless loop attempting to upgrade fake packages.  If core and buildessential need to be upgraded, it never happens because running `crew update` again shows both still need to be upgraded.

**Comment by uberhacker** [comment]
The workaround to fix this for now is the following:
```
crew remove core buildessential
crew install core buildessential
```
`crew reinstall core buildessential` does not work.

**Comment by satmandu** [comment]
Even with that I still see this, which indicates that stuff isn't being removed correctly:

```
jq --arg key "glibc_lib" -e '.installed_packages[] | select(.name == $key )' /usr/local/etc/crew/device.json
{
  "name": "glibc_lib",
  "version": "2.37",
  "sha256": null
}
{
  "name": "glibc_lib",
  "version": "2.37-1",
  "sha256": null
}
{
  "name": "glibc_lib",
  "version": "2.37-1",
  "sha256": null
}
{
  "name": "glibc_lib",
  "version": "2.37-1",
  "sha256": null
}
```

**Comment by satmandu** [comment]
Looks like the fix was in install, where `PackageUtils.installed?(@pkg.name)` is false for `is_fake` packages...
