### ISSUE TITLE
Installs broken because core has ruby_ruby_libversion, which requires buildessential to install

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#10450]
Adding `ruby_ruby_libversion` to the bootstrap gems in `install.sh` does not fix the install.
- Installing the `ruby-libversion` gem with `gem install ruby-libversion` invokes a c compiler to build the extension that links to `libversion`, and we don't have a compiler available until `buildessential` is installed.
- So in the short term, we may just have to remove `ruby_ruby_libversion` from `core.rb` to let builds to succeed.
- I put some thoughts on this into an issue on the ruby-libversion repo at https://github.com/Zopolis4/ruby-libversion/issues/1

Also,  `ruby_ruby_libversion` needs a `libversion` dependency added.

**Comment by Zopolis4** [comment]
Should we just remove ruby_ruby_libversion from core? tools/version.rb is a feature only really used by developers anyways, so there's no massive harm done if it doesn't work out of the box.

**Comment by satmandu** [comment]
The simplest short term solution then would be to just move it to buildessential, right?

But we also need to wrap the usage in crew so that buildessential is installed before we start using it?

(Gating functionality behind buildessential makes sense, but maybe you want to make the gem work without local building being necessary anyways?)

**Comment by Zopolis4** [comment]
This is why I was against making this script accessible via a crew command :p

Given that the average user isn't going to need this, I think its fine to just drop it from core-- it's not a core part of crew's functionality anyways
