### ISSUE TITLE
🐞 Bug filezilla doesn't launch

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#10479]
**Describe the bug**
Filezilla refuses to launch

**To Reproduce**

1. Install and run `filezilla`
2. Filezilla outputs errors in terminal and refuses to launch

My environment was (crosh, bash or VT-2):
VT-2

2. I executed the command(s) below:
      ```shell
      # filezilla
      ```

      Output:

      ```
      chronos@sycamore-rev5 ~ $ filezilla 
      Reading locale option from /usr/local/.config/filezilla/filezilla.xml
      Failed to connect to D-BUS: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
      wxD-Bus: Could not connect to session bus
      Segmentation fault (core dumped)
      chronos@sycamore-rev5 ~ $ echo $DISPLAY
      :0
      ```
**Expected behavior**
Filezilla to launch with no issues

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***

<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.50.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 16a602fb4 `Update micro package (#10275) (5 weeks ago)`

- OS variant: `Chrome OS`
- OS version: `hana-release/R126-15886.74.0`
- OS channel: `stable-channel`

</details>

***

**Comment by satmandu** [comment]
You can't launch in VT-2 because there is no display manager running in VT-2.

Launch `filezilla` from `crosh`.

**Comment by VenomousSteam81** [comment]
> You can't launch in VT-2 because there is no display manager running in VT-2.
> 
> Launch `filezilla` from `crosh`.

oh ok. i thought there was because i can launch things like xfce4-terminal

**Comment by VenomousSteam81** [comment]
I'm still getting the same error.

**Comment by satmandu** [comment]
> I'm still getting the same error.

Does running `restartsommelier` first help?

**Comment by satmandu** [comment]
> > You can't launch in VT-2 because there is no display manager running in VT-2.
> > 
> > Launch `filezilla` from `crosh`.
> 
> oh ok. i thought there was because i can launch things like xfce4-terminal


Hmmm... The segfaults suggests that maybe the program is crashing though...

**Comment by satmandu** [comment]
Also do a `crew update && crew upgrade`...

**Comment by VenomousSteam81** [comment]
Now I can't run filezilla because of this error:
```
filezilla: error while loading shared libraries: libgspell-1.so.2: cannot open shared object file: No such file or directory
```
(Yes, I've updated)
