### ISSUE TITLE
🐞 Bug

### ISSUE THREAD

**Issue by antoine2711** [chromebrew/chromebrew#10502]
**Describe the bug**
While doing a `crew upgrade`… And even after, while doing the recommended `gem cleanup stringio`.

**To Reproduce**
My environment was: crosh

      crew upgrade
      gem cleanup stringio

      Output:

      chronos@localhost / $ gem cleanup stringio
      Cleaning up installed gems...
      WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.1.0
      WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
      Please report a bug if this causes problems.
      Clean up complete

**System Information**

<main>The last update was 5 min, 20 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.52.7`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 23265468d `Zed 0.147.2 => 0.153.6 (#10501) (28 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `nami-release/R127-15917.65.0`
- OS channel: `stable-channel`

</details>

**Comment by satmandu** [comment]
Try a `crew update; crew upgrade` now... There have been some gem updates today

**Comment by antoine2711** [comment]
@satmandu : all good. Thanks.

Regards, Antoine
