### ISSUE TITLE
🐞 Bug `crew` fails if `/usr/local/tmp/crew` does not exist

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#10510]
**Describe the bug**
Bug crew fails if /usr/local/tmp/crew does not exist

**To Reproduce**

1. remove `/usr/local/tmp/crew`
2. attempt to install a package with crew

My environment was VT-2

2. I executed the command(s) below:
      ```shell
      rm -rf /usr/local/tmp/*
      crew install [package(s)]
      ```

      Output:

      ```
      /usr/local/bin/crew:465:in `chdir': No such file or directory @ dir_chdir0 - /usr/local/tmp/crew (Errno::ENOENT)
	from /usr/local/bin/crew:465:in `download'
	from /usr/local/bin/crew:1266:in `install'
	from /usr/local/bin/crew:1228:in `block in resolve_dependencies'
	from /usr/local/bin/crew:1225:in `each'
	from /usr/local/bin/crew:1225:in `resolve_dependencies'
	from /usr/local/bin/crew:1118:in `resolve_dependencies_and_install'
	from /usr/local/bin/crew:1763:in `block in install_command'
	from /usr/local/bin/crew:1748:in `each'
	from /usr/local/bin/crew:1748:in `install_command'
	from /usr/local/bin/crew:1871:in `<main>'
      ```
**Expected behavior**
I expect `crew` to create `/usr/local/tmp/crew`

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.52.8`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: df8eb0dc2 `Krita 5.2.3 => 5.2.5 (#10507) (3 days ago)`

- OS variant: `Chrome OS`
- OS version: `hana-release/R126-15886.74.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] Make `crew` create `/usr/local/tmp/crew` when it isn't present.

**Comment by satmandu** [comment]
Wow. ok we have a bunch of `Dir.chdir CREW_BREW_DIR do` lines in `crew`. Where is the best place to have a `FileUtils.mkdir_p CREW_BREW_DIR` ?

@supechicken @Zopolis4 @uberhacker

**Comment by satmandu** [comment]
I think just adding
```ruby
# Make sure crew work directories exist.
FileUtils.mkdir_p CREW_BREW_DIR
FileUtils.mkdir_p CREW_DEST_DIR
```
to `crew` should take care of this...
