### ISSUE TITLE
🐞 Bug `ffmpeg` needs `libtesseract.so.5.3.3`, however only `libtesseract.so.5.4.1` exists.

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#10604]
**Describe the bug**
`ffmpeg` needs updated

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): VT-2

2. I executed the command(s) below:
      ```shell
      ffmpeg
      ```

      Output:

      ```
      ffmpeg: error while loading shared libraries: libtesseract.so.5.3.3: cannot open shared object file: No such file or directory
      ```
**Expected behavior**
`ffmpeg` should not complain

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.54.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: c06b30fa1 `Fix issue with overmatching gem names. (#10603) (2 hours ago)`

- OS variant: `Chrome OS`
- OS version: `hana-release/R126-15886.74.0`
- OS channel: `stable-channel`

</details>

***

**Comment by satmandu** [comment]
There's a PR up to update ffmpeg to 7.1, but unfortunately that also breaks other stuff.

**Comment by satmandu** [comment]
Can you see if the commands in that PR give you a working ffmpeg?

**Comment by VenomousSteam81** [comment]
Yes, I can! Doing that right now.

**Comment by VenomousSteam81** [comment]
ffmpeg now works. Hopefully it doesn't break too much

**Comment by satmandu** [comment]
Fixed by https://github.com/chromebrew/chromebrew/pull/10551
