### ISSUE TITLE
🐞 Bug - Sommelier - Cannot open display ":0"

### ISSUE THREAD

**Issue by merll002** [chromebrew/chromebrew#10616]
**Describe the bug**
When trying to start Sommelier with the command `restartsommelier` it produces the following errors:
```
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: configure event loop: 6.3168e-05 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: drm device: 0.0085423 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: connect display: 0.000176719 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: client create: 4.1693e-05 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: display implementation: 3.247e-06 seconds
INFO <sommelier-scope-timer.cc:30> ~ScopeTimer: spawn xwayland: 0.00101111 seconds
xset: unable to open display ":0"
xset: unable to open display ":0"
xset: unable to open display ":0"
xset: unable to open display ":0"
```

My environment was (crosh).

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1929:<main>:The last update was 24 hrs, 7 min, 7 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.54.7`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 2db4f97fa `Ffmpeg => 7.1 & Deps Updates (#10551) (2 days ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R129-16002.51.0`
- OS channel: `stable-channel`

</details>
***
Any ideas why this is happening?

**Comment by uberhacker** [comment]
What is the output of `echo $DISPLAY`?

**Comment by merll002** [comment]
Will try the workaround tomorrow

**Comment by merll002** [comment]
Unfortunately this did not work. Any other ideas?

**Comment by satmandu** [comment]
Are you in VT-2 or crosh?

**Comment by merll002** [comment]
Crosh, yes.

**Comment by uberhacker** [comment]
Reading over the previous posts, there is no mention of updating crew.  Have you tried the following yet?
````
crew update && crew upgrade
```

**Comment by merll002** [comment]
yep. done both

**Comment by uberhacker** [comment]
Have you tried a fresh install from scratch?
````
rm -rf /usr/local
bash <(curl -L git.io/vddgY) && . ~/.bashrc

**Comment by merll002** [comment]
will try tomorrow

**Comment by merll002** [comment]
Reinstalling fixed the issue. Closing
