### ISSUE TITLE
🐞 Bug Package libcaca is missing from repositories

### ISSUE THREAD

**Issue by etihwjd** [chromebrew/chromebrew#10689]
**Describe the bug**
Package libcaca is missing

**To Reproduce**
Install MPV on Lenovo Chromebook Duet 3

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): bash

2. I executed the command(s) below:
      ```shell
      # crew install mpv
      ```

      Output:

      ```
      # mpv: Video player based on MPlayer/mplayer2
      # https://mpv.io/
      # Version: 0.38.0
      # License: LGPL-2.1+, GPL-2+, BSD, ISC and GPL-3+
      # Performing pre-flight checks for mpv...
      # The following packages also need to be installed: 
      # libcaca libcddb libcdio libcdio_paranoia libdovi libdvdread libdvdnav libplacebo libxpresent libxss luajit mujs openmp shaderc vapoursynth
      # Proceed (YES/no)?
      # y
      # libcaca: libcaca is a graphics library that outputs text instead of pixels, so that it can work on older video cards or text terminals.
      # Precompiled binary available, downloading...
      # Download of https://gitlab.com/api/v4/projects/26210301/packages/generic/libcaca/0.99.beta20-f42aa68-py3.13_armv7l/libcaca-0.99.beta20-f42aa68-py3.13-chromeos-armv7l.tar.zst failed with error 404: Not Found
      ```
**Expected behavior**
MPV installs with appropriate dependencies

**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1931:<main>:The last update was 1 min, 13 seconds ago.
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.55.8`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 93a1c8401 `Telegram 5.6.0 => 5.7.0 (#10687) (2 hours ago)`

- OS variant: `Chrome OS`
- OS version: `strongbad-release/R130-16033.43.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
building libcaca from a source also fails due to the following error:
libtool:   error: cannot find the library '/usr/local/lib/libfreetype.la' or unhandled argument '/usr/local/lib/libfreetype.la'

What I think needs to be done:

      - [ ] upload up to date libcaca package 
      - [ ]  Profit...?

**Comment by satmandu** [comment]
https://github.com/chromebrew/chromebrew/pull/10691 Should also help with getting `mpv` to work...
