### ISSUE TITLE
Ruby on armv7l built with kernel headers newer than 3.17 is broken for machines with kernels older than 3.17 due to missing getentropy() call. Ruby cannot use the "urandom" call

### ISSUE THREAD

**Issue by incogninto1-1** [chromebrew/chromebrew#10724]
I was trying to install Chromebrew on my ARMv7 based Chromebook and everything was going well until I reached the part where it was "Performing pre-install for crew_profile_base...". Afterwards I got the following message:
"/usr/local/lib/ruby/3.3.0/tmpdir.rb:133:in `urandom': failed to get urandom (RuntimeError)"

Steps to reproduce the issue:
Run the install command in the repo's readme

Model: HP Chromebook 14 G3

Please let me know if there is anything I can do to get it fixed

**Comment by incogninto1-1** [comment]
> Hmmm.... Googling that error I see that might be a ulimit issue?
> 
> https://stackoverflow.com/a/59890433
> 
> What does `ulimit -n` give you?
> 
> Can you increase that if it is low?

The original value outputted by the command was 8192.

I tried to increase the -n value to 16384 (double of 8192) however that didn't fix the issue. What value should I use?

**Comment by satmandu** [comment]
Hmmm. This could be a kernel issue.

What does `uname -a` give you?

**Comment by satmandu** [comment]
The relevant line is `/usr/local/lib/ruby/3.3.0/tmpdir.rb:133`
```ruby
(::Random.urandom(4).unpack1("L")%MAX).to_s(36)
```

**Comment by satmandu** [comment]
(Is it possible that you are on a kernel older than 3.17?)

**Comment by incogninto1-1** [comment]
> Hmmm. This could be a kernel issue as per [rubygems/rubygems#5941 (comment)](https://github.com/rubygems/rubygems/issues/5941#issuecomment-2085121770)
> 
> What does `uname -a` give you?

The kernel version is 3.10.18.
Is there a possibility to get chromebrew working on this older kernel? If not, are there any alternatives I can try?

**Comment by satmandu** [comment]
I did some searches for your model, and it doesn't look like there are any great options. There was an arch Linux script post several days ago with possibly your hardware, but it looks like there may still be some issues:

https://github.com/altreact/archbk/pull/20

**Comment by satmandu** [comment]
> > Hmmm. This could be a kernel issue as per [rubygems/rubygems#5941 (comment)](https://github.com/rubygems/rubygems/issues/5941#issuecomment-2085121770)
> > 
> > What does `uname -a` give you?
> 
> The kernel version is 3.10.18.
> Is there a possibility to get chromebrew working on this older kernel? If not, are there any alternatives I can try?

Also, that's an ancient kernel. The i686 builds are built against an even older kernel, but the problem is that some software needs newer kernels to build, and you might find other breakage beyond just ruby ...

**Comment by incogninto1-1** [comment]
> [@incogninto1-1](https://github.com/incogninto1-1) Can you try an install again? I rebuilt `ruby` with older 3.10 kernel headers, sop maybe it might be compatible with your system now.

I tried. Nope, it didn't work. Same error

**Comment by satmandu** [comment]
Sorry then, I don't think we can help. Docker isn't even supported for kernels older than 4.8, so if this is a regression in Ruby's support for older kernels, then this isn't going to work for you.

You might have to see if you can replace your kernel on your machine, but that might be a slog, as alternate Linux builds for Chromebooks, and especially arm Chromebooks, are iffy in their availability.

**Comment by satmandu** [comment]
@uberhacker @supechicken @Zopolis4 It looks like our attempts to support older arm Chromebooks with the 3.x kernels isn't working. (Though i686 does not appear to be broken...)

**Comment by Zopolis4** [comment]
Admittedly, I don't know if i686 support has gotten tested on real hardware in a while.
