### ISSUE TITLE
🐞 Bug : vscodium doesnt launch

### ISSUE THREAD

**Issue by Eeeevox** [chromebrew/chromebrew#10752]
**Describe the bug**
after running codium app returns an error about missing version information

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh after typing 'shell'):

2. I executed the command(s) below:
      ```shell
      crew install vscodium
      crew postinstall vscodium
      codium
      ```

      Output:

      ```
/usr/local/VSCodium-linux-arm/bin/../codium: /usr/local/lib/libffi.so.8: no version information available (required by /usr/local/lib/libgobject-2.0.so.0)

/usr/local/VSCodium-linux-arm/bin/../codium: /usr/local/lib/libffi.so.8: no version information available (required by /usr/local/lib/libwayland-server.so.0)

/usr/local/VSCodium-linux-arm/bin/../codium: /usr/local/lib/libffi.so.8: no version information available (required by /usr/local/lib/libwayland-client.so.0)

/usr/local/VSCodium-linux-arm/bin/../codium: /usr/local/lib/libffi.so.8: no version information available (required by /usr/local/lib/libLLVM.so.19.1)
      
      ```
**Expected behavior**
vscodium would open

**Screenshots**
![Image](https://github.com/user-attachments/assets/3686eecd-ae4a-4c6b-aba7-111e66046370)

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
usr/local/bin/crew:1931:<main>:The last update was 12 hrs, 43 min, 4 seconds ago.
fatal: your current branch 'main' does not have any commits yet
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.55.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `trogdor-release/R130-16033.58.0`
- OS channel: `stable-channel`

</details>
***

**Comment by uberhacker** [comment]
@Eeeevox: Thank you for the bug report.  Is sommelier running?  What is the output of `/usr/local/var/log/sommelier.log`?
