### ISSUE TITLE
🐞 Bug - Missing resource for installation (404)

### ISSUE THREAD

**Issue by lightsrgr8** [chromebrew/chromebrew#10761]
**Installation**

I ran the usual setup script in crosh (sudo still works on m.103)

2. I executed the command(s) below:
      
         shell
         bash <(curl -L git.io/vddgY) && . ~/.bashrc

[Cut] 
eudev: Gentoo standalone udev
Precompiled binary available, downloading...
Eudev archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for eudev...
Performing install...
libcap_ng: The libcap-ng library is intended to make programming with posix capabilities much easier than the traditional libcap library.
Precompiled binary available, downloading...
Download of https://gitlab.com/api/v4/projects/26210301/packages/generic/libcap_ng/0.8.5-py_x86_64/libcap_ng-0.8.5-py-chromeos-x86_64.tar.zst failed with error 404: Not Found
An error occured during the installation :/
chronos@localhost / $ 
      ```
It should've installed normally with no errors
(It had installed correctly a month ago)

This had some errors too:
***
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.55.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `celes-release/R103-14816.131.5`
- OS channel: `stable-channel`

</details>
***

      - [ ] bring back the missing url so chromebrew can fully install
      (it mostly installs, but then tries to install the missing package whenever you attempt to install something through crew.

**Comment by satmandu** [comment]
Your install is broken.
What does this give you?
 ```bash
crew const CREW_PY_VER
```
This is what it should show:
```bash
crew const CREW_PY_VER
CREW_PY_VER=py3.13
```

**Comment by satmandu** [comment]
Also, what does this give you?
```bash
python3 -c "print('.'.join(__import__('platform').python_version_tuple()[:2]))"
```

**Comment by satmandu** [comment]
If your install is failing, please run this:
```bash
bash -x <(curl -L git.io/vddgY) && . ~/.bashrc
```

**Comment by lightsrgr8** [comment]
Thanks for the quick reply!
the crew conts gives:
[/usr/local/lib64/ruby/gems/3.3.0/specifications/logger-1.6.1.gemspec] isn't a Gem::Specification (NilClass instead).
[/usr/local/lib64/ruby/gems/3.3.0/specifications/logger-1.6.1.gemspec] isn't a Gem::Specification (NilClass instead).
python3: no python-exec wrapped executable found in /usr/lib/python-exec.
CREW_PY_VER=py
python command:
3.6

I'll try the -x option

**Comment by lightsrgr8** [comment]
The output of `bash -x <(curl -L git.io/vddgY) && . ~/.bashrc`:

```
eudev: Gentoo standalone udev
Precompiled binary available, downloading...
Eudev archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for eudev...
Performing install...
libcap_ng: The libcap-ng library is intended to make programming with posix capabilities much easier than the traditional libcap library.
Precompiled binary available, downloading...
Download of https://gitlab.com/api/v4/projects/26210301/packages/generic/libcap_ng/0.8.5-py_x86_64/libcap_ng-0.8.5-py-chromeos-x86_64.tar.zst failed with error 404: Not Found
++ echo_error 'An error occured during the installation :/'
++ echo -e '\e[1;91mAn error occured during the installation :/\e[0m'
An error occured during the installation :/
```

**Comment by lightsrgr8** [comment]
Ok. Maybe done for day though.

This chromebook was about the worst model 10yrs ago.
Don't expect much, so if it doesn't work, whatever.
(Homeschool crumbook)

And chromebrew erases `usr/local/bin` automatically before it installs
I already made backups of my custom crouton scripts

**Comment by lightsrgr8** [comment]
Well, the partial install now broke about half of the OS.

All non-shell commands fail with
`/usr/bin/coreutils: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short`

I can't even use `cp` to restore anything, and have to use `echo *` instead of `ls` or `dir`
My chroot is still running, though, and may be able to recover something.
I do have a chromeos recovery stick on hand if needed.

**Comment by satmandu** [comment]
Feel free to try this after a clean install and post the install log so we can help you debug this further.
```bash
cd /usr/local ; bash -x <(curl -L git.io/vddgY) > >(tee -a chromebrew_install.log) 2> >(tee -a chromebrew_install.log >&2)
```

**Comment by lightsrgr8** [comment]
Well, I figured out that the chromebrew installation wipes the log automatically.
I might need to use `( tee -a /media/removable/chromebrew_install.log)` instead.

**Comment by Goosople** [comment]
I'm having the same problem now: returns 404 when trying to download libcap-ng while installing crew. Maybe the link is broken?

**Comment by satmandu** [comment]
You are having an issue with python not getting properly installed.

Please run this and attach the log file here please

```bash
cd /usr/local ; bash -x <(curl -L git.io/vddgY) > >(tee -a ~/chromebrew_install.log) 2> >(tee -a ~/chromebrew_install.log >&2)
```

**Comment by Goosople** [comment]
> You are having an issue with python not getting properly installed.
> 
> Please run this and attach the log file here please
> 
> `cd /usr/local ; bash -x <(curl -L git.io/vddgY) > >(tee -a ~/chromebrew_install.log) 2> >(tee -a ~/chromebrew_install.log >&2)`

The output: [chromebrew_install.log](https://github.com/user-attachments/files/17964288/chromebrew_install.log)

By the way, I forgot to mention that the script told me the beta, dev or canary channel are not supported, and I have to set `CREW_FORCE_INSTALL=1` to install. But my device is running the latest stable ChromeOS (actually it seems to be LTS, I didn't realized that until seeing the output of the script). Is that where the problem is?

**Comment by satmandu** [comment]
That is not the problem. Thanks for the log.

The problem is likely here:
```bash
Installing core Chromebrew packages...
+ crew install core
+ yes
python3: no python-exec wrapped executable found in /usr/lib/python-exec.
```
FYI @chromebrew/active we need to modify `lib/const.rb` to manually set `CREW_PY_VER` to `3.13` before `/usr/local/bin/python3` is available, i.e., before the `python3` package is installed, as otherwise installs on some hardware break with that variable getting set to empty.
