### ISSUE TITLE
🐞 Bug Package `librsvg` doesn't exist on GitLab package repo

### ISSUE THREAD

**Issue by FinnBaltazar1111** [chromebrew/chromebrew#10764]
**Describe the bug**
404 when trying to fetch `librsvg`
**To Reproduce**

1. Please indicate where the command(s) were executed.

crosh

2. I executed the command(s) below:
      `crew install librsvg`
**Expected behavior**
Package `librsvg` installs successfully installs.

**Output**
```
librsvg: SVG library for GNOME
https://wiki.gnome.org/Projects/LibRsvg
Version: 2.58.2-icu
License: LGPL-2+
Performing pre-flight checks for librsvg...
Precompiled binary available, downloading...
Download of https://gitlab.com/api/v4/projects/26210301/packages/generic/librsvg/2.58.2-icu_armv7l/librsvg-2.58.2-icu-chromeos-armv7l.tar.zst failed with error 404: Not Found
```

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.50.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 8292d7ae0 `update other arm ver (3 months ago)`

- OS variant: `Chrome OS`
- OS version: `jacuzzi-release/R109-15236.66.0`
- OS channel: `testimage-channel`

</details>
***

**Comment by satmandu** [comment]
Please run `crew update && yes | crew upgrade` and retry the install.

**Comment by satmandu** [comment]
Hopefully an update or reinstall will resolve this, due to updates in the last several days.

Please reopen this if that doesn't solve the issue.
