### ISSUE TITLE
🐞 can't "install" libwebp when it's installed manually

### ISSUE THREAD

**Issue by joskezelensky** [chromebrew/chromebrew#10765]
**Describe the bug**
can't "install" libwebp when it's installed manually
**To Reproduce**
install libwebp manually (binaries available [here](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/) and then install it with crew
1. Please indicate where the command(s) were executed.
My environment was (crosh, bash or VT-2):
crosh shell v114
2. I executed the command(s) below:
      ```shell
      crew install mpv
      ```

      Output:

     ```
     # output of your command(s)
    crew install mpv
    mpv: Video player based on MPlayer/mplayer2
    https://mpv.io/
    Version: 0.39.0
    License: LGPL-2.1+, GPL-2+, BSD, ISC and GPL-3+
    Performing pre-flight checks for mpv...
    
    
    
    libwebp: WebP is a modern image format that provides superior lossless and lossy compression for images on the web.
    Precompiled binary available, downloading...
    Libwebp archive downloaded.
    Unpacking archive using 'tar', this may take a while...
    Performing pre-install for libwebp...
    Performing install...
    /usr/local/include/webp/mux.h: failed to remove file: Permission denied
    /usr/local/bin/crew:1085:in `system': Command failed with exit 13: crew-mvdir (RuntimeError)
            from /usr/local/bin/crew:1085:in `install_files'
            from /usr/local/bin/crew:1138:in `block in install_package'
            from /usr/local/bin/crew:1109:in `chdir'
            from /usr/local/bin/crew:1109:in `install_package'
            from /usr/local/bin/crew:1350:in `install'
            from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
            from /usr/local/bin/crew:1262:in `each'
            from /usr/local/bin/crew:1262:in `resolve_dependencies'
            from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
            from /usr/local/bin/crew:1826:in `block in install_command'
            from /usr/local/bin/crew:1811:in `each'
            from /usr/local/bin/crew:1811:in `install_command'
            from /usr/local/bin/crew:1934:in `<main>'
       ```
**Expected behavior**
notice that libwebp is already installed and write it down somewhere that it is installed
**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `AuthenticAMD`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.55.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: feced24a7 `Ugrep 6.4.1 => 7.0.4 (#10750) (4 days ago)`

- OS variant: `Chrome OS`
- OS version: `zork-release/R114-15437.98.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by satmandu** [comment]
The permissions in your manually installed files are wrong. Everything in /usr/local needs to be owned by `chronos` for chromebrew actions to work properly.

Having said that, we are not going to support hybrid installs of chromebrew in combination with manual installs, as it makes the install just too non-deterministic.

Debugging such systems is very difficult!

**Comment by joskezelensky** [comment]
> I suppose we could add a check for the files already existing, but from crew's perspective this is less a manual installation than just a bunch of files being in the target directory for some reason. What prompted you to 'install it manually' in the first place?

didn't know that it was available

**Comment by joskezelensky** [comment]
> The permissions in your manually installed files are wrong. Everything in /usr/local needs to be owned by `chronos` for chromebrew actions to work properly.
> 
> Having said that, we are not going to support hybrid installs of chromebrew in combination with manual installs, as it makes the install just too non-deterministic.
> 
> Debugging such systems is very difficult!

i completely understand!

**Comment by joskezelensky** [comment]
> The permissions in your manually installed files are wrong. Everything in /usr/local needs to be owned by `chronos` for chromebrew actions to work properly.
> 
> Having said that, we are not going to support hybrid installs of chromebrew in combination with manual installs, as it makes the install just too non-deterministic.
> 
> Debugging such systems is very difficult!

is it possible to chmod every file in usr/local/ to make 'chronos' the owner?

**Comment by satmandu** [comment]
(You may or may not have to run that command from `VT-2`.)
