### ISSUE TITLE
🐞 Bug

### ISSUE THREAD

**Issue by joskezelensky** [chromebrew/chromebrew#10774]
**Describe the bug**

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2):
crosh

2. I executed the command(s) below:
      ```shell
      bash <(curl -L git.io/vddgY) && . ~/.bashrc
      ```

      Output:
```
py3_flit_core: Flit provides simplified packaging of Python modules—core portions.
Skipping source download...
Building from source, this may take a while...
Preconfiguring package...
/usr/local/lib64/ruby/3.3.0/json/common.rb:220:in `parse': unexpected token at '' (JSON::ParserError)
        from /usr/local/lib64/ruby/3.3.0/json/common.rb:220:in `parse'
        from /usr/local/lib/crew/lib/buildsystems/pip.rb:58:in `install'
        from /usr/local/bin/crew:734:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:702:in `chdir'
        from /usr/local/bin/crew:702:in `build_and_preconfigure'
        from /usr/local/bin/crew:1308:in `install'
        from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1262:in `each'
        from /usr/local/bin/crew:1262:in `resolve_dependencies'
        from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1826:in `block in install_command'
        from /usr/local/bin/crew:1811:in `each'
        from /usr/local/bin/crew:1811:in `install_command'
        from /usr/local/bin/crew:1934:in `<main>'
An error occured during the installation :/
```
**Expected behavior**

**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
CHROMEOS_ARC_ANDROID_SDK_VERSION=30
CHROMEOS_ARC_VERSION=11580385
CHROMEOS_AUSERVER=https://auserver.coolelectronics.me
CHROMEOS_BOARD_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_RELEASE_BOARD=zork-signed-mp-v9keys
CHROMEOS_RELEASE_BRANCH_NUMBER=98
CHROMEOS_RELEASE_BUILDER_PATH=zork-release/R114-15437.98.0
CHROMEOS_RELEASE_BUILD_NUMBER=15437
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=114
CHROMEOS_RELEASE_DESCRIPTION=15437.98.0 (Official Build) stable-channel zork 
CHROMEOS_RELEASE_KEYSET=mp-v9
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15437.98.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15437.98.0
***

**Additional context**

What I think needs to be done:
idk
      - [ ] step one
      - [ ] step two

**Comment by satmandu** [comment]
You appear to be on Milestone 114. Please update your ChromeOS device to the most recent ChromeOS release and try again?

**Comment by joskezelensky** [comment]
> You appear to be on Milestone 114. Please update your ChromeOS device to the most recent ChromeOS release and try again?

lts isn't good enough?

**Comment by satmandu** [comment]
It doesn't make sense for us to test against releases that aren't current for a device.

**Comment by joskezelensky** [comment]
> It doesn't make sense for us to test against releases that aren't current for a device.

_have you tried restarting your device?_
would've also helped.
Anyway it worked when i restared my laptop so all is good
