### ISSUE TITLE
Make util_linux install without binaries.

### ISSUE THREAD

**Issue by s0urce-c0de** [chromebrew/chromebrew#10816]
**Describe the bug**

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): crosh

2. I executed the command(s) below:
      ```shell
      Entering the shell
      ```

      Output:

      ```
      Starting chromebrew bash.
      ```
**Expected behavior**

I expect it not to start chromebrew bash with an annoying message, and to at least let me use default ChromeOS bash. It even forces me to use chromebrew mount, chromebrew chsh, chromebrew every package that ChromeOS has. I would like to at least respect chsh with chromebrew bash, or something. Even if other packages depend on it, they most likely depend on the libraries it provides. Can we change these packages to something like it provides the commands in a different directory or not?

**Screenshots**
![Image](https://github.com/user-attachments/assets/42036c05-74de-4a46-a18e-db73b0c4ea3e)

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1931:<main>:The last update was 14 min, 40 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.56.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: d63f2ec94 `Use curl for connecting to github API to add reviewer team to automated PRs (#10813) (33 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R130-16033.58.0`
- OS channel: `stable-channel`
</details>

***

**Additional context**

What I think needs to be done:

      - [ ] Allow installing "stubs" which are packages without bins, packages can say to install them, or via `crew install/reinstall --stub`

**Comment by uberhacker** [comment]
I guess I'm not sure what you are requesting here.  Are you saying you want to return to the ChromeOS versions of these binaries?

**Comment by satmandu** [comment]
We use an updated version of the utilities that come with ChromeOS because we provide more recentl updated binaries than those that might be available for people, especially those with EOL systems.

But I suspect that making util-linux an optional install isn't high on our priority list.

You're welcome to adjust the `~/,bashrc` and the scripts it invokes in `/usr/local/etc` to make the system do what you want though, including prefixing the path with /bin, /usr/bin, etc to make sure those binaries get invoked first, but of course that could break expectations in Chromebrew apps that might expect newer versions of binaries...

**Comment by s0urce-c0de** [comment]
Can we at least allow remove it with the force flag?

**Comment by satmandu** [comment]
Yes but it will reinstall if you do an update, & upgrade, I think

**Comment by uberhacker** [comment]
You can now force remove util_linux with `crew remove util_linux -f` as per https://github.com/chromebrew/chromebrew/pull/10818.

**Comment by s0urce-c0de** [comment]
> You can now force remove util_linux with `crew remove util_linux -f` as per [#10818](https://github.com/chromebrew/chromebrew/pull/10818).

tysm
