### ISSUE TITLE
🐞 Dbus is broken

### ISSUE THREAD

**Issue by code-leech** [chromebrew/chromebrew#11054]
### Sytem info:

Laptop type: HP Chromebook 11a na0
Board type: Kappa
CPU: MediaTek Kompanio 500 (MT8183) (8 threads, 1.99GHz)
RAM: 4.00GB

### Bug 🐞

On opening crosh (and typing shell), I get this error:

```
Starting Chromebrew bash.
dbus-daemon[8161]: Failed to start message bus: Failed to bind socket "/var/run/dbus/system_bus_socket": Address already in use
EOF in dbus-launch reading address from bus daemon
dbus-update-activation-environment: error: unable to connect to D-Bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Sommelier can use direct scaling.
sommelier processes running:  7899
```

And the problem specifically is
```
 Failed to bind socket "/var/run/dbus/system_bus_socket": Address already in use
```

I dug around my system, only to find that `dbus` (yes, and `dbus_glib`) doesn't have to be installed! **Both are preinstalled even without chromebrew.** 

However when `dbus` and `dbus_glib` are uninstalled through chromebrew and I run 
```
dbus-launch gnome-terminal
```

I get 
```
gnome-terminal: error while loading shared libraries: libdbus-1.so.3: cannot open shared object file: No such file or directory
```

This means that chromebrew's dbus package should only contain the `dbus` library (wherever it's meant to be) and nothing else.
I might be wrong about that, but it is a plausible theory.

**Comment by satmandu** [comment]
Attempting an update:

https://github.com/chromebrew/chromebrew/actions/runs/12540807968

**Comment by satmandu** [comment]
(FYI, `dbus` is essentially a stub package in Chromebrew. Feel free to submit a PR to make it actually work. We primarily have it in here to keep other compiles which require it from breaking from it not being installed.)

**Comment by satmandu** [comment]
Also, `gnome-terminal` is linked against the Chromebrew `dbus`, so you can't just uninstall `dbus` and expect `gnome-terminal` not to break. (ChromeOS as shipped offers a cut-down set of libraries to build against...)
