### ISSUE TITLE
Feature request: Install packages from file

### ISSUE THREAD

**Issue by cygnus8595** [chromebrew/chromebrew#2460]
I don't know if this is already in place (apologies if it is, I didn't find it in the docs) but I was wondering if it would be possible to install a list of packages from a file. I think it would be good in the event that someone would need to powerwash their Chromebook and wants to reinstall Chromebrew just like the had it. This would be the workflow:

1. Before powerwashing, run crew list installed > packages.txt to get a list of installed packages saved to a file
2. Powerwash, turn on developer mode and re-install Chromebrew
3. Re-install all packages from file by running something like crew install -f packages.txt

This would also work when upgrading to a new Chromebook or replacing a dead one.

**Comment by uberhacker** [comment]
@cygnus8595: This is a good suggestion.  We might also want to add a backup of `~/.bashrc` or `~/.zshrc` and any other configuration as part of a complete backup solution.

**Comment by JL2210** [comment]
```
crew install $(cat packages.txt)
```
is what I always use
