### ISSUE TITLE
Package request - gcloud

### ISSUE THREAD

**Issue by nosarthur** [chromebrew/chromebrew#2897]
The AWS command line tool is available as `aws`. Is it possible to provide `gcloud` as well?

**Comment by uberhacker** [comment]
@nosarthur: Check out the `google_cloud_sdk` package.  It has the `gcloud` command.

**Comment by uberhacker** [comment]
I'm going to leave this issue open as others have asked the same question and this issue should help answer future questions.

**Comment by nosarthur** [comment]
Didn't look careful enough. Thanks @uberhacker

**Comment by nosarthur** [comment]
What's the difference between `aws` and `aws_shell` packages?

**Comment by JL2210** [comment]
From here, it looks like `aws_shell` is more of a shell, like Bash.

**Comment by JL2210** [comment]
But, it requires a whole lot of manual resolution of `pip2` dependencies.

**Comment by nosarthur** [comment]
Ah, just installed both, it seems `aws` is the correct one, i.e., it's the shell command for AWS. `aws-shell` is [this repo](https://github.com/awslabs/aws-shell)

**Comment by JL2210** [comment]
OK. Glad I could help. :)

**Comment by satmandu** [comment]
This issue doesn't need to stay open for it to be searchable...
