### ISSUE TITLE
Can't run QB64 on ChromeOS

### ISSUE THREAD

**Issue by caglewebsolutions** [chromebrew/chromebrew#2985]
## Description
QB64 was installed via Chromebrew, but doesn't open when I try to run it. 

If you executed a specific command:
```shell
qb64
```

Output:
```shell
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 952
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 870
Warning: Unknown scale factor: 833
Warning: Unknown scale factor: 769
Warning: Unknown scale factor: 667
freeglut (/usr/local/share/qb64/qb64): 
Child exited with status: 1
```

## Versions and system information
chromebrew: `1.0.6`

ChromeOS: 

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0

Model: Dell Chromebook 11 3120

Architecture: `x86_64`

**Comment by caglewebsolutions** [comment]
Admittedly it's in the beta channel. I suppose I could try stable channel too though.

**Comment by JL2210** [comment]
Don't try to use Chromebrew when not on the stable channel.

**Comment by JL2210** [comment]
@caglewebsolutions Try running this command: `crew install freeglut`

**Comment by uberhacker** [comment]
@caglewebsolutions: You can save yourself a lot of trouble if you stick to the stable channel.  We plan to support only the stable channel.  With that said, we have some contingency plans to handle the changes in these newer releases once they become stable.

**Comment by JL2210** [comment]
@uberhacker The issue persists on the stable channel. I have the same problem.

**Comment by JL2210** [comment]
> Yeah I figured that out. Anyway I'm having the same problem on the stable channel. Anyway I've updated my info to reflect that this is also happening on stable.

**Comment by uberhacker** [comment]
@caglewebsolutions: Can you please update this issue to include the stable channel in your `Versions and system information` section?

**Comment by JL2210** [comment]
@uberhacker He has.

**Comment by uberhacker** [comment]
Really? `CHROMEOS_RELEASE_CHROME_MILESTONE=71`

**Comment by JL2210** [comment]
Told you, that's stable now. Update and tell me that I'm wrong.

**Comment by JL2210** [comment]
```
chronos@localhost / $ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5167872
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2EDF7C6D-6586-D292-0B61-4A33B62E3BF6}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2EDF7C6D-6586-D292-0B61-4A33B62E3BF6}
CHROMEOS_RELEASE_BOARD=kefka-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=59
CHROMEOS_RELEASE_BUILDER_PATH=kefka-release/R71-11151.59.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.59.0 (Official Build) stable-channel kefka 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.59.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11151.59.0
```

**Comment by uberhacker** [comment]
I haven't been prompted to install this release yet so for me and others, the stable version is still 70.

**Comment by JL2210** [comment]
Is your Chromebook on the [Death page](https://support.google.com/chrome/a/answer/6220366)?

**Comment by JL2210** [comment]
Otherwise, go to `Settings > triple bar on the top left > About Chrome OS > Check for updates`

**Comment by uberhacker** [comment]
With the exception of the Samsung Series 5, none of my devices are past the AUE date.  There is usually a delay from the time the stable channel is updated and the notices are triggered on the devices.  Most users likely don't bother to update manually but wait until the notice to update reminds them.

**Comment by caglewebsolutions** [comment]
71 is definitely in the stable channel here.

I just got home from going to the movies and having Christmas dinner with my girlfriend, so I need to catch up.

**Comment by caglewebsolutions** [comment]
same results with freeglut removed and then re-installed.

**Comment by skiman6010** [comment]
@JL2210 @uberhacker On top of that, the stable channel is rolled out in batches over a week or so with different devices getting the update at different times or held back for an issue that is fixed, sometimes the "check for updates" button doesn't pull the update because the update isn't available for your board. 

Anyway, I can actually reproduce this issue unlike the others, so I will work on solving this.

**Comment by JL2210** [comment]
Hmm... The issue seems to be springing from `libglut.so`; maybe a recompile with needed features will help.

**Comment by cstrouse** [comment]
Here's what I get on Samsung Chromebook Plus V1:
```
chronos@localhost / $ qb64
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Warning: Unknown scale factor: 1667
Warning: Unknown scale factor: 1429
Warning: Unknown scale factor: 1111
Warning: Unknown scale factor: 909
Warning: Unknown scale factor: 667
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
freeglut (/usr/local/share/qb64/qb64): 
Child exited with status: 1
```

```
chronos@localhost / $ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=5823788
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=92
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R76-12239.92.0
CHROMEOS_RELEASE_BUILD_NUMBER=12239
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=76
CHROMEOS_RELEASE_DESCRIPTION=12239.92.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12239.92.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12239.92.0
```

**Comment by cstrouse** [comment]
This no longer seems to be an issue.

![image](https://user-images.githubusercontent.com/849044/101899421-0cf73880-3b6b-11eb-9707-42b52fccedcf.png)
