### ISSUE TITLE
[feature request]: New --check option

### ISSUE THREAD

**Issue by JL2210** [chromebrew/chromebrew#3100]
To execute the `def self.check` section, we currently need to use `crew build <package-name>`. If we added a new `--check` option, we could run this command to run the checks while installing a package: `crew install --check <package-name>`. Is this possible?

It would be preferable to eventually have the `--check` option be the default for `crew install`.

**Comment by uberhacker** [comment]
We definitely don't want to check by default for `crew install`, especially when installing from binaries.  It might make sense to have the option available when installing from source, however.  A new command would be overkill.  The switch option makes more sense.  Just my two cents.

**Comment by JL2210** [comment]
> A new command would be overkill.

Fair enough.

> We definitely don't want to check by default for crew install, especially when installing from binaries. It might make sense to have the option available when installing from source, however.

Sorry, I forgot to elaborate: Only when installing from sources.

> The switch option makes more sense.

That seems reasonable.

**Comment by skycocker** [comment]
Do we want to abort the build if any of the checks fail?

**Comment by JL2210** [comment]
Yes.

**Comment by uberhacker** [comment]
@skycocker: That would be reasonable.  I envision this will only be needed when installing from source, not from binaries.  That said, we should do a good job of checking during builds so there are no errors.

**Comment by cstrouse** [comment]
I've ran into quite a few projects where the tests aren't well-maintained or don't work on odd configurations such as the Samsung Chromebook Plus V1 (64-bit kernel and 32-bit armv7l userland). One that comes to mind was `memcached` where the tests had broken alignment checks in their `Makefile` and would always fail even though the software compiled and worked properly. I certainly don't want the check step enabled by default on my machine.

**Comment by uberhacker** [comment]
Yeah, tests are usually overrated and can provide a false sense of success.  If the tests are thorough, I can see the value but most tests are inadequate.

**Comment by cstrouse** [comment]
They also seem to be less useful on ChromeOS devices since the software and hardware configurations are often quite different from the main configurations that they develop on, test on, and support.

**Comment by Zopolis4** [comment]
Also, for the packages where we do still run tests, we tend to disable shipping them, so the tests wouldn't be available in the precompiled binary and thus cannot be run from crew install.

**Comment by satmandu** [comment]
We could package the build archives. 😅

**Comment by Zopolis4** [comment]
We could...

**Comment by Zopolis4** [comment]
I don't think its worth shipping test binaries to all users so that some tests can be ran without building a package.
