### ISSUE TITLE
Package request: LÖVE (2D lua game engine)

### ISSUE THREAD

**Issue by torzod** [chromebrew/chromebrew#3236]
Seeing as lua and luaJIT are already present, I do not believe this would be terribly difficult to compile and/or port to chromebrew. I am running the samsung xe303c12, armv7l
This would be helpful running games on stabyourself.net on the go, which would be very fun.

**Comment by JL2210** [comment]
You can try it yourself, if you'd like. The process is fairly easy:
https://bitbucket.org/rude/love/src

This is the process for creating a package:
https://github.com/skycocker/chromebrew/wiki/Creating-a-package

**Comment by torzod** [comment]
May as well give it a try later today, thanks for the instructions.

**Comment by torzod** [comment]
@JL2210 It seems that love requires the openAL library, but i cannot find instructions anywhere on how to build it. could you try to help?

**Comment by JL2210** [comment]
It doesn't work in Chromebrew, and I haven't been able to find it. Sorry.

**Comment by JL2210** [comment]
Could you please post this in #132?

**Comment by JL2210** [comment]
@torzod I think that version of love requires a different version of Lua. It won't work with the (newest) Chromebrew-provided version.
