### ISSUE TITLE
Question about move local to a SD card

### ISSUE THREAD

**Issue by TheElf01** [chromebrew/chromebrew#3443]
Hi, i have a question. 

Is possible to move /usr/local  to a micro sd card?

I tried something

format a SD card to ext4
install chromebrew
move all directories from /usr/local  (bin, etc, sbin, etc etc) to sd card
do symbolik links to /usr/local

for example

ln -s /media/removable/sd/local/bin /usr/local/bin

etc etc to every directory..

But is not working at all

Any ideas? my chromebook have 8.9GB free after powerbash, but i need at least 7GB for some android applications i need for work

thanks

**Comment by uberhacker** [comment]
@TheElf01: If you set the environment variable `CREW_PREFIX`, you should be able to relocate the default `/usr/local` install directory.  However, you will need to compile all the core packages from source since the binaries have been built using the default.  Something like `export CREW_PREFIX=/media/removable/sd/usr/local` is what you will need.  Make sure the directory exists before attempting to install.  If you want to build all the binaries in advance, you could try:
```
for p in $(cat /path/to/chromebrew/tools/core_packages.txt); do crew build $p; done
```
Of course, you will need to install crew the recommended way first.  Once this is finished, you will need to point all the core packages in /usr/local/lib/crew/packages to your new binaries with something like:
```
binary_url ({
  x86_64: 'file://path/to/build/directory/package-version-chromeos-x86_64.tar.xz'
})
binary_url ({
  x86_64: 'hash from package-version-chromeos-x86_64.tar.xz.sha256 goes here'
})
```
Replace `x86_64` with your architecture, if different.  Hopefully, that makes sense.  Let me know how it works!

**Comment by uberhacker** [comment]
Another important thing to consider is your SD card directory must be mounted with execute permission, otherwise, the binaries will not work.

**Comment by JL2210** [comment]
@uberhacker `crew build -p` only builds the packages.
@TheElf01 Also note that the SD card must be formatted as EXT4 or something compatible. Anything related to FAT (including NTFS) will not work.

**Comment by TheElf01** [comment]
Hi, first sorry delay to answer i was pretty bussy with work

I want to say thank for all help,  sadly i was not luck with moving enviroment to SD card


But finally i did in this way... for sure not best way, but work for me

- First i did a full install of chromebrew to internal storage (/usr/local)

- create a local directory in SD card (ext4) and move all directory there (/usr/local/bin, lib64, etc)

- did a symbolink link of every directory from SD to /usr/local

- erase libmount* and dependencies from chromebrew lib64 and do symbolink links to same files in /usr/lib64

- mount sd card with execute permission 
sudo mount -o remount,rw -o exec /media/sdcardname/partition

-add same mount command to /home/-user-/.bashrc



I know...FOR SURE is not best..  but it works.. jeje,  any advice is welcome

[url=https://ibb.co/mhYz0TM][img]https://i.ibb.co/F8f7X3j/Screenshot-2019-09-10-at-09-42-54.png[/img][/url]


and i can compile without problems... ohh... mikmod in my chromebook... a good module player is priceless jeje  compile just with some minor changes in source

[url=https://ibb.co/mF5Qqy9][img]https://i.ibb.co/84gF5xr/Screenshot-2019-09-10-at-09-44-57.png[/img][/url]


thanks a lot

**Comment by uberhacker** [comment]
@TheElf01: That is great news!  You shouldn't need to mount your home directory executable.  Did you want to make a package out of mikmod?  You might want to check out audacious also.

**Comment by TheElf01** [comment]
> @TheElf01: That is great news! You shouldn't need to mount your home directory executable. Did you want to make a package out of mikmod? You might want to check out audacious also.

Thanks a lot for all help, this is a great project, and now i feel my chromebook is really a... computer  jeje

Finally i compiled some software i really love, mostly console module players,  xmp and ocp

I tested audacious, it works good, is a GTK software,  i just need to check how to change GTK themes to mimic chromeos 

I will be happy if i can do a package, any tutorial?

Sorry, i know how to deal with unix, i worked many years administrating sunOS servers, but im a little lost in linux

thanks

**Comment by uberhacker** [comment]
You can follow this [guide](https://github.com/skycocker/chromebrew/wiki/Creating-a-package).  See https://coderwall.com/p/no3qfa/setting-gtk2-and-gtk3-theme-via-config-file to configure a theme for GTK.
