### ISSUE TITLE
[ldc] shared library error

### ISSUE THREAD

**Issue by cstrouse** [chromebrew/chromebrew#3455]
When I install this from binaries on ARM I get the following when trying to run the compiler:

```chronos@localhost ~ $ ldc2
ldc2: error while loading shared libraries: libLLVMLTO.so.5: cannot open shared object file: No such file or directory
```

**Comment by uberhacker** [comment]
@cstrouse: Does `crew install llvm` fix it?

**Comment by cstrouse** [comment]
I already had the llvm package installed when I received this error.

**Comment by tulaneadam** [comment]
I had a curl error and a similar shared library error when I attempted to install chromebrew on a new HP Chromebook x360 14(nami). I attempted to install chromebrew both in developer mode and default on the stable chrome os version (77) multiple times, following the main install instructions but was not able to install chromebrew.  If there's anything I missed or can do to help get chromebrew working on a nami chromebook please let me know, would be happy to help/test.  Thanks.

**Comment by cstrouse** [comment]
Looks like the problem here is a mismatch between the versions of the llvm shared objects vs what you had installed when you compiled the binaries.

**Comment by saltedcoffii** [comment]
no longer an issue
