### ISSUE TITLE
Jupyter Notebook can't access the other folder

### ISSUE THREAD

**Issue by richblack** [chromebrew/chromebrew#3600]
## Description
I successifully installed miniconda, then I installed jupyter notebook with conda.

1. The jupyter notebook can't run by use the standard command "jupyter notebook" from the very outside of shell, but when the conda virtual environment activated, it works;
2. When it is running, the dashboard isn't open automatically, instead, it provides some local urls to paste on chrome to open dashboard (Is it possible that it could not locate runnable browser?) ;
3. After paste the file it provide and open dashboard in Chrome, It can't access any directory outside where it be installed-- "/usr/local/share/miniconda3/bin". In another OS, Jupyter Notebook can access the other directory tree like "Downloads", so that the users can save files in those directory and not save files in package. (please see the attached screen capture, in the dashboard, there is no upper directory to go)

If you executed a specific command:
```shell
chronos@localhost /usr/local/share/miniconda3/bin $ source activate root
(base) chronos@localhost /usr/local/share/miniconda3/bin $ jupyter notebook
```

Output:
```shell
[I 09:16:57.759 NotebookApp] The port 8888 is already in use, trying another port.
[I 09:16:57.760 NotebookApp] The port 8889 is already in use, trying another port.
[I 09:16:57.769 NotebookApp] Serving notebooks from local directory: /usr/local/share/miniconda3/bin
[I 09:16:57.770 NotebookApp] The Jupyter Notebook is running at:
[I 09:16:57.770 NotebookApp] http://localhost:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
[I 09:16:57.770 NotebookApp]  or http://127.0.0.1:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
[I 09:16:57.770 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:16:57.781 NotebookApp] No web browser found: could not locate runnable browser.
[C 09:16:57.782 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/chronos/user/.local/share/jupyter/runtime/nbserver-10605-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
     or http://127.0.0.1:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
Serving notebooks from local directory: /usr/local/share/miniconda3/bin
0 active kernels
The Jupyter Notebook is running at:
http://localhost:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
 or http://127.0.0.1:8890/?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b
Shutdown this notebook server (y/[n])? No answer for 5s: resuming operation...
[I 09:18:06.575 NotebookApp] 302 GET /?token=01053178d6f705d98dd108d5100af888f0eacae9e8f0514b (127.0.0.1) 2.06ms
```

## Versions and system information
chromebrew: 1.2.5

ChromeOS:
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=5950196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
CHROMEOS_RELEASE_BOARD=reef-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=40
CHROMEOS_RELEASE_BUILDER_PATH=reef-release/R78-12499.40.0
CHROMEOS_RELEASE_BUILD_NUMBER=12499
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=78
CHROMEOS_RELEASE_DESCRIPTION=12499.40.0 (Official Build) beta-channel reef 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=12499.40.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12499.40.0

Model: Asus Chromebook C213NA

Architecture: x86_64
![Screenshot 2019-10-29 at 9 41 12 AM](https://user-images.githubusercontent.com/16075080/67730540-4684e700-fa30-11e9-8ee4-3e300c10afc4.png)

**Comment by mustfkeskin** [comment]
I have same problem
Any progress here

**Comment by skiman6010** [comment]
1. Since you installed Jupyter Notebooks inside of a conda env, you can't activate it outside of that env. 

2. The shell can't autolaunch the dashboard because we don't have integration between the browser and shell. `No web browser found: could not locate runnable browser.` is the error.

3.  `jupyter notebook` will serve the browser view from the folder location you are in with your shell. You should follow add miniconda to your path so you can use `source activate [envname]` without having to be in your miniconda install folder.

All of this is working as intended.

**Comment by Zopolis4** [comment]
Given that, I don't see any reason to keep this issue open.
