### ISSUE TITLE
php7 has a new name?

### ISSUE THREAD

**Issue by lettucehead** [chromebrew/chromebrew#3690]
(prelude, linked for posterity in case helpful:) https://github.com/skycocker/chromebrew/issues/3689

In some not so ancient history, php7 was a chromebrew package.

I had it.
I discovered that if a user with it upgrades, they get this very exciting error:

```
chronos@localhost /usr/local $ crew upgrade -v
Updating packages...
Package php7 not found. :(
```

Looks like now it ain't there:

```
chronos@localhost /usr/local $ crew search php
php: PHP is a popular general-purpose scripting language that is especially suited to web development.
php5: PHP is a popular general-purpose scripting language that is especially suited to web development.
php70: PHP is a popular general-purpose scripting language that is especially suited to web development.
php71: PHP is a popular general-purpose scripting language that is especially suited to web development.
php72: PHP is a popular general-purpose scripting language that is especially suited to web development.
php73: PHP is a popular general-purpose scripting language that is especially suited to web development.
php74: PHP is a popular general-purpose scripting language that is especially suited to web development.
```
... so maybe something needs to refer to the 7* instead of the 7, or whatever

**Comment by lettucehead** [comment]
To other non-geniuses like myself looking to fix upgrade issue, do:
```
crew remove php7
```
... then install another php7 pkg of yr choice, then continue upgrading.

**Comment by uberhacker** [comment]
@lettucehead: Thank you for bringing this to our attention.  You can choose the php version you need with `crew install php`.  I'll leave this open for others that may struggle with this issue.

**Comment by lettucehead** [comment]
thank you for your speedy response!
i feel heard.
however `crew install php` provides options other than the options were when i actually *ran* this command some months ago.
what i believe happened is there was a reference to php7, the version that existed a few months ago, and then somebody updated it to a subversion, like 7.0 and 7.1 and 7.2, etc., which is expressed as php70 and php71 and php72, etc., and that instead of changing every single reference to php7 to i.e. php70 somebody changed *almost* every reference and that's why this error appeared.

therefore this issue does not require me to know how to install php with crew.

instead this issue requires somebody who knows how to grep the crew source files or package xml for php-related references and find the offending one

otherwise people who are as dumb as me will continue to waste small amounts of time trying to update crew

i believe this is at least a few people

i would like to save these people a few minutes of time

regards
lettucehead

**Comment by uberhacker** [comment]
The previous php7 package was for php 7.3 only.  The binaries for the other point releases were in php.rb.  This has been cleaned up so php.rb references the php7x "sub" packages instead.  You are correct to resolve this issue with `crew remove php7`.

**Comment by uberhacker** [comment]
You might want to `crew remove php && crew install php` to "upgrade" php.rb.  This is related to a bug with fake packages.  See issue [#1390](https://github.com/skycocker/chromebrew/issues/1390) for more details.

**Comment by cstrouse** [comment]
Should we add an entry to the wiki and then close this?

**Comment by uberhacker** [comment]
Sure, go for it.

**Comment by uberhacker** [comment]
We now have `crew reinstall php` that replaces `crew remove php && crew install php`.

**Comment by uberhacker** [comment]
Also, the bug in #1390 is fixed.
