### ISSUE TITLE
No sound with mpv

### ISSUE THREAD

**Issue by vincowl** [chromebrew/chromebrew#3712]
Launching `mpv`, the video is correctly displayed but have no sound. Chromebrew's packages are fully updated.
Here is the output of  the `mpv` launching :
```
 (+) Video --vid=1 (*) (h264 576x322 23.984fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu/wayland] Compositor doesn't support the required xdg_wm_base protocol!
libEGL warning: DRI2: failed to open swrast (search paths /usr/local/lib64/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/local/lib64/dri)
[vo/gpu/opengl] GLX not found.
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/wlshm/wayland] Compositor doesn't support the required xdg_wm_base protocol!
[vo/xv] No Xvideo support found.
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vaapi] Failed to initialize VAAPI: unknown libva error
[vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO.
AO: [pulse] 44100Hz stereo 2ch float
VO: [x11] 576x322 yuv420p
```

**Comment by uberhacker** [comment]
Thank you for the error report @vincowl.  My guess is pulseaudio is the issue.  The audacious package works only with alsa so we may need to switch from pulseaudio.

**Comment by vincowl** [comment]
`audacious` was not installed. If it is a dependency, then it should be added. But whatever, installing it and handling `audacious` settings didn't help to solve the bug. Uninstalling `pulseaudio` crashed `mpv` since `libpulse` is needed.

**Comment by uberhacker** [comment]
Yeah, I didn't think `audacious` should be a dependency.  I just mentioned that it only works with alsa which may apply here as well.

**Comment by cubedcod** [comment]
ensure you have the ALSA cras plugin and various tools for testing:

`crew install cras alsa_plugins alsa_tools alsa_utils`

make sure your /etc/asound.conf looks liks this:

```
pcm.!default {
        type cras
}
ctl.!default {
        type cras
}
```
tell mpv to use ALSA:

```
mkdir -p ~/.config/mpv
echo audio-device=alsa/default >> ~/.config/mpv/mpv.conf
```

**Comment by vincowl** [comment]
Works like a charm ! Thanks @cubedcod

**Comment by uberhacker** [comment]
Wow @cubedcod, this is great!  We have an issue with firefox lacking sound as well and this may do the trick there also.  It probably makes sense to add this config in the mpv package.  We can try to do this in the next update.  In the meantime, I will leave this issue open so others can try this also.

**Comment by vincowl** [comment]
@uberhacker I am working on the firefox problem. This solution only applies to mpv. Trying to apply something similar to firefox

**Comment by satmandu** [comment]
Mpv definitely plays with sound now.
