### ISSUE TITLE
Cannot start sommelier [solved]

### ISSUE THREAD

**Issue by iz0eyj** [chromebrew/chromebrew#4142]
Hi,
I'm testing your great work on my FydeOS machine (Core i7), but I cannot start GUI software.
Sommelier & stopsommelier are installed, **but not** the startsommelier script.
I removed & reinstalled sommelier using crew remove sommelier -> crew install sommelier... same thing, startsommelier not found.
Any idea to solve?

Thanks.

I missed this, sorry:

`To complete the installation, execute the following:
echo '# Sommelier environment variables + daemon' >> ~/.bashrc
echo '# See https://github.com/dnschneid/crouton/wiki/Sommelier-(A-more-native-alternative-to-xiwi)' >> ~/.bashrc
echo 'if [ ! -d /tmp/.X11-unix ]; then' >> ~/.bashrc
echo 'mkdir /tmp/.X11-unix' >> ~/.bashrc
echo 'fi' >> ~/.bashrc
echo 'sudo chmod -R 1777 /tmp/.X11-unix' >> ~/.bashrc
echo 'sudo chown root:root /tmp/.X11-unix' >> ~/.bashrc
echo 'alias startsommelier="set -a && source ~/.sommelier.env && set +a && initsommelier"' >> ~/.bashrc
echo 'startsommelier' >> ~/.bashrc
source ~/.bashrc`

**Comment by uberhacker** [comment]
@iz0eyj: Glad you were able to figure it out.  Yes, that post install message is easy to miss.  I will leave this open to help others who might run into the same issue.

**Comment by iz0eyj** [comment]
@uberhacker 
why not put a configuration script in / usr / local / bin?
I think my mistake is quite common

**Comment by uberhacker** [comment]
Hey @iz0eyj:  You mean to replace the alias in `~/.bashrc`?  If you can figure that out, you are a better man than me.

**Comment by iz0eyj** [comment]
@uberhacker 
No, I asked if it would not be possible to insert a configuration script containing the sequence of commands among the files installed by the sommelier package, insert it in /usr/local/bin and have it automatically launched at the end.
But it doesn't really matter anyway, in the end just don't make my mistake of not reading everything on the screen :)
