### ISSUE TITLE
CloudReady support

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#4340]
[CloudReady](https://www.neverware.com/freedownload#intro-text) is becoming increasing popular since it provides an option to run a newer version of ChromeOS after a Chromebook has reached end of life support.  There are some differences with CloudReady and native ChromeOS that Chromebrew could do a better job of handling so crew commands work better.

**Comment by satmandu** [comment]
It would also be nice as part of enabling this NOT to treat all of ```/usr/local``` as belonging to chromebrew.

The recursive chmod to ```/usr/local``` not respecting volume boundaries (other volumes may be mounted off of /usr/local ) is an especially heinous annoyance. ;)

**Comment by supechicken** [comment]
Closing as Cloudready is dead now :)
