### ISSUE TITLE
[codium] unable to install

### ISSUE THREAD

**Issue by storm1er** [chromebrew/chromebrew#4417]
## Before you submit an issue
May be related to #2105

## Description

The following command did not work
```shell
crew install codium
```

Output:
```shell
Message: libdrm 2.4.102 needed because nouveau has the highest requirement
Run-time dependency libdrm_intel found: NO (tried pkgconfig and cmake)

meson.build:1414:4: ERROR: Dependency "libdrm_intel" not found, tried pkgconfig and cmake
```

## Versions and system information
chromebrew: `1.4.4`

ChromeOS: `83.4.27` cloudready

Model: Lenovo Ideapad 300 15arr (ryzen 5 2500u vega graphics)

Architecture: `x86_64`

**Comment by uberhacker** [comment]
@storm1er: We currently don't support CloudReady...but you could help with the support initiative.  See #4340.

**Comment by cstrouse** [comment]
I think the main issue there is that he's on an AMD machine with non-Intel iGPU and it's trying to use the Intel DRM graphics library.

**Comment by storm1er** [comment]
That was my initial thought, and why I also wrote the cpu/gpu in the model description

**Comment by EvidenceRepulsive151** [comment]
I had the exact same issue with an Intel CPU when installing `parsec`. Try installing `libdrm`: `crew install libdrm`

**Comment by satmandu** [comment]
Codium installs now.
