### ISSUE TITLE
[Suggestion] Install DE instead of Sommelier on i686 to provide GUI apps support 

### ISSUE THREAD

**Issue by supechicken666** [chromebrew/chromebrew#4506]
Is there any possible that to provide GUI apps support for i686 again by using an desktop environment like `i3` ?
If so, can we install desktop environment to replace `sommelier` ? 
Since the `sommelier` support for i686 is dropped
Thanks

**Comment by uberhacker** [comment]
I suppose that is a possibility.

**Comment by satmandu** [comment]
Does the sommelier at https://github.com/skycocker/chromebrew/pull/4450 work for you on i686?

(and if not, can you let me know which machine you are using?)

**Comment by supechicken666** [comment]
> Does the sommelier at #4450 work for you on i686?
> 
> (and if not, can you let me know which machine you are using?)

I haven't test it yet
I will use chromium os to test it since i only have an old arm chromebook
