### ISSUE TITLE
Dependency installation thoughts

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#4531]
It occurs to me that when one asks ```crew``` to install package ```A```, ```crew``` walks through the dependency tree and adds them to the _end of the queue_ of packages to be installed before package ```A``` can be installed.

Simply reversing that, and adding those dependency packages as they are found to the _top of that queue_, might solve some large part of the dependency issue.

**Comment by vincowl** [comment]
Seems to be logic !  👍

**Comment by uberhacker** [comment]
@satmandu:  It's probably a bit more complicated than that but it would be a good first start.

**Comment by satmandu** [comment]
@uberhacker Yeah late-night epiphanies need to be taken with a large grain of salt... hence my hedging. ;)

**Comment by satmandu** [comment]
The quick and dirty way to do this is to change
https://github.com/skycocker/chromebrew/blob/2ffec00e85672850c9840874ec9ef01a09a5de37/crew#L773
to ```@dependencies.reverse.each do |dep| ```
