### ISSUE TITLE
Use Github Actions to do CI?

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#4588]
And maybe also for creating packages?
e.g. https://docs.github.com/en/free-pro-team@latest/actions/guides/about-packaging-with-github-actions

Seems like access to this infrastructure should be free for us?

Also, apparently, you can use docker containers as part of actions: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action

It might be useful to have PRs be built as part of the review process to make sure compiles occur correctly?

**Comment by uberhacker** [comment]
Good suggestion.  We need smart people like you to set it up. :)

**Comment by satmandu** [comment]
Aria2 has some interesting github actions using brew:

https://github.com/aria2/aria2/commit/faa6955c8d7bb7b6541e0b7fbb84f7d213f761ab
