### ISSUE TITLE
Package Request: Samba

### ISSUE THREAD

**Issue by jvadair** [chromebrew/chromebrew#4626]
I would love to be able to create network shares on my Chromebook. I use mine as a server, and I host 2 discord bots and 2 Terraria servers on it. Currently whenever I want to edit a file, I either have to clone the file or use WinSCP to access files. The latter works quite well but I would like to be able to host a simple smb network share so that I can manage files better without external services (on PC, I've heard it's simple to mount SFTP on Linux).

**Comment by uberhacker** [comment]
@jvadair: You might try `crew install sshfs`.  This will enable you to mount a remote share to access files.

**Comment by jvadair** [comment]
> @jvadair: You might try `crew install sshfs`.  This will enable you to mount a remote share to access files.

@uberhacker What you're describing is a way to mount SFTP shares to my Chromebook, Im talking about a scenario where I access files from the Chromebook on my Windows PC, which is most easily achieved through an smb network share.

**Comment by satmandu** [comment]
It can be done, but setting up daemons in ChromeOS is difficult as there is no access to setup services under upstart or systemd...

**Comment by smartguy1196** [comment]
> It can be done, but setting up daemons in ChromeOS is difficult as there is no access to setup services under upstart or systemd...

...without disabling write protection (though I don't recommend it)

**Comment by satmandu** [comment]
We do have smbclient though. It's not that we can't build samba, it's that we don't have the plumbing in place to allow for lots of daemons to be running from crosh. Really the only one we do tend to start is `sommelier`...
