### ISSUE TITLE
[sommelier] Unable to run sommelier with options

### ISSUE THREAD

**Issue by supechicken666** [chromebrew/chromebrew#4742]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
Provide a short description of your problem here.

If you executed a specific command:
```shell
crew postinstall sommelier
sommelier -X opera
sommelier --scale=1.5 opera
sommelier --x-display=:0 opera
```

Output:
```shell
error: failed to create virtwl context: Inappropriate ioctl for device
```

## Versions and system information
```shell
chronos@localhost / $ sommelier --version
Version: 0.20
```

ChromeOS: `cat /etc/lsb-release`
```shell
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6957084
CHROMEOS_AUSERVER=https://block-tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=99
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R86-13421.99.0
CHROMEOS_RELEASE_BUILD_NUMBER=13421
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=86
CHROMEOS_RELEASE_DESCRIPTION=13421.99.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13421.99.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13421.99.0
```

Architecture: `x86_64`

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by uberhacker** [comment]
@supechicken666: What sommelier related lines do you have in your `~/.bashrc`?

**Comment by satmandu** [comment]
can you do a ```crew update && crew reinstall -s sommelier```? It should now enter stuff into .bashrc automatically now.

**Comment by satmandu** [comment]
But the output of ```env``` would be useful as well, especially after running ```restartsommelier```

**Comment by supechicken666** [comment]
> @supechicken666: What sommelier related lines do you have in your `~/.bashrc`?

```shell
# Sommelier environment variables + daemon
set -a && source ~/.sommelier.env && set +a
startsommelier
```

**Comment by supechicken666** [comment]
> crew update && crew reinstall -s sommelier

Done, checked `.bashrc` after reinstall but nothing happened

**Comment by supechicken666** [comment]
@satmandu @uberhacker  Now I am only able to edit the scale on  `~/.sommelier.env`

**Comment by satmandu** [comment]
You can run sommelier manually so long as you run stopsommelier first, since otherwise sommelier is invoked through the sommelierd script in /usr/local/sbin . Take a look at that to get a sense of how this is started now.
