### ISSUE TITLE
Unable to Install Qemu

### ISSUE THREAD

**Issue by imreallyliam** [chromebrew/chromebrew#5286]
## Description
Attempting to install `qemu` normally, other packages include its dependencies and sommelier (with its dependencies too).

If you executed a specific command:
```shell
crew install qemu
```

Output:
```shell
ld: Error: unable to disambiguate: -nopie (did you mean --nopie ?)
```

## Versions and system information
chromebrew: `1.7.8`

ChromeOS: `R88-12597.94.0`

Model: Brunch Zork

Architecture: `x86_64`

## Addtional information
N/A

**Comment by uberhacker** [comment]
@xeu100:  Thank you for the feedback.  Yes, qemu is one of the troublesome packages we've been trying to tackle.  I keep hoping a newer release fixes issues with earlier versions.  This is a fairly active project so I imagine we'll have some success, hopefully, in the near future.

**Comment by saltedcoffii** [comment]
Unfortunately qemu is a very outdated package in our repositories. We're at version 4, upstream is version 5. @uberhacker do you suggest removing it for the time being?

**Comment by uberhacker** [comment]
Have you tried the compiling the latest release?

**Comment by saltedcoffii** [comment]
When I have time, I'll to do the whole qemu/libvirt/virt-manager setup. I might even have to do something fancy with `dkms` to get some of those packages to work 🙃

**Comment by satmandu** [comment]
Just hold on until 6.0 comes out. It's in RC now, and it has things like LTO support...

Also arch has some patches to make compiles of qemu more resilient to changes by building many of the modules statically: https://github.com/archlinux/svntogit-packages/tree/packages/qemu/trunk
