### ISSUE TITLE
Use GitHub archive for installer script?

### ISSUE THREAD

**Issue by superloach** [chromebrew/chromebrew#5839]
I've noticed the installer script spends a lot of time `curl`ing individual package files to fetch them.

Wouldn't it be easier to fetch the latest packaged `unzip` and simply extract the [current master archive](https://github.com/skycocker/chromebrew/archive/refs/heads/master.zip)?

**Comment by satmandu** [comment]
Do you want to try it and compare times?

(We could also just use git, since we now have a static git binary...)

**Comment by superloach** [comment]
If we have a static git binary, that's even more straightforward. I haven't had time to experiment with rewriting the installer script yet, but I may try it later.

**Comment by superloach** [comment]
Much better idea - use the [gzipped archive](https://github.com/skycocker/chromebrew/archive/refs/heads/master.tar.gz) and just use `tar`, avoiding `unzip` entirely!

**Comment by satmandu** [comment]
@superloach We now have static binaries of curl, git, and pixz, so we should be able to dramatically lower the number of package files downloaded to just the prereqs for ruby. That should speed things up.

If you want to take a swing at it. :)

**Comment by supechicken** [comment]
Change made in #7436
