### ISSUE TITLE
error in installing crew

### ISSUE THREAD

**Issue by kamran-nishat** [chromebrew/chromebrew#5978]
ruby: /lib/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libruby.so.3.0)
ruby: /lib/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/libruby.so.3.0)
Any idea how can I resolve this error. Same error is displayed if I run "ruby". I have a version of the libc.so.6 which is older. How can I install a newer version?

thanks

If you executed a specific command:
```shell   bash
your command here
chronos@localhost / $ crew

Output:
ruby: /lib/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/libruby.so.3.0)
ruby: /lib/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/libruby.so.3.0)

```

## Versions and system information
chromebrew: `crew --version`

ChromeOS: `cat /etc/lsb-release`

Model: YOUR MODEL HERE

Architecture: `uname -m`

## Additional information
Mention things we might need to know. Like:

What I think needs to be done:
- [ ] step one
- [ ] step two

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by saltedcoffii** [comment]
Okay so we currently support two glibc versions, 2.23 and 2.27. We're working on 2.32. I'm seeing glibc 2.25 in this list which makes me worry that your version of ChromeOS has a version of glibc that chromebrew doesn't support. I need your help to debug this. Could you give me the output of a few commands @kamran-nishat ?
`uname -a`
`ls /lib64/ | grep ld`
`ls /lib/ | grep ld`

Your ChromeOS version may also need updating. Please go into your ChromeOS settings, go to "About ChromeOS" and click "Check for Updates". If there's an update, update. Also, please make sure ChromeOS is running the stable channel as we don't support beta, dev and canary.

If you have any futher info, let us know.

**Comment by kamran-nishat** [comment]
Thanks for your reply.
uname -a
Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 29
21:31:23 PST 2018 armv7l ARMv7 Processor rev 5 (v7l) Qualcomm (Flattened
Device Tree) GNU/Linux

ls /lib64/ | grep ld

ls: cannot access '/lib64/': No such file or directory
ls /lib/ | grep ld
ld-2.23.so
ld-linux-armhf.so.3

**Comment by satmandu** [comment]
What model device is this?

I don't think we support any devices with that version of glibc? That's really old...

**Comment by uberhacker** [comment]
@kamran-nishat: Also, please provide the output from `cat /etc/lsb-release`.

**Comment by kamran-nishat** [comment]
It is a Google WiFi device. Model :NLS-1304-25

**Comment by satmandu** [comment]
Are you using some variant of https://github.com/marcosscriven/galeforce ?

Chromebrew has not been tested on those devices at all. We're welcome to patches to help get those up and running, but as we don't have those devices, I have to warn you it's going to be a long road, especially as the memory and disk space offered by a 3 year old device targetted towards embedded deployment is going to be quite low...

**Comment by kamran-nishat** [comment]
CHROMEOS_RELEASE_APPID={9BC3D9F3-D113-8EA2-42D6-F2CDB8189814}
CHROMEOS_BOARD_APPID={9BC3D9F3-D113-8EA2-42D6-F2CDB8189814}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=OTHER
HWID_OVERRIDE=GALE DOGFOOD
CHROMEOS_RELEASE_BUILDER_PATH=gale-release/R63-10032.86.2
GOOGLE_RELEASE=10032.86.2
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_BOARD=gale
CHROMEOS_RELEASE_BUILD_NUMBER=10032
CHROMEOS_RELEASE_BRANCH_NUMBER=86
CHROMEOS_RELEASE_CHROME_MILESTONE=63
CHROMEOS_RELEASE_PATCH_NUMBER=2
CHROMEOS_RELEASE_TRACK=testimage-channel
CHROMEOS_RELEASE_DESCRIPTION=10032.86.2 (Official Build) dev-channel gale
test
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_VERSION=10032.86.2
CHROMEOS_AUSERVER=https://tools.google.com/service/update2

**Comment by kamran-nishat** [comment]
I  am using this "curl -Ls git.io/vddgY | bash" script to install the crew.
It goes without any problem until



*HEAD is now at cc09c4a llvm 12.0.1 rebuild (#5956)Updating crew package
information...*


Then give following error:


*ruby: /lib/libc.so.6: version `GLIBC_2.25' not found (required by
/usr/local/lib/libruby.so.3.0)*
*ruby: /lib/libc.so.6: version `GLIBC_2.27' not found (required by
/usr/local/lib/libruby.so.3.0) *

**Comment by saltedcoffii** [comment]
Sounds like the ruby binaries don't work on your computer, perhaps something to do with the libc version.

**Comment by kamran-nishat** [comment]
yes. How can I install a newer version of libc? Or is there any script
available using the prior version of the ruby like "ruby 2.5.1p57
(2018-03-29 revision 63029)" which is working on another Google wifi device.

Kamran

**Comment by uberhacker** [comment]
That is not a stable release of ChromeOS.  Was the operating system updated from the original stock install on the device?

**Comment by kamran-nishat** [comment]
it is connected to the Internet and according to the app it is uptodate.
Files compiled with gcc in another google wifi device are running fine here.

How can I change it to a stable release?

**Comment by uberhacker** [comment]
You could try: `sudo update_engine_client --channel=stable-channel --update`
