### ISSUE TITLE
crew needs a command to build and install in one go which updates the package file

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#6079]
Right now `crew build` and `crew install` are two separate commands.

`crew build` creates a binary package and a sha256 file.
`crew install` when being used to install a binary package requires a package.rb file which has both a URL to the binary package, and the sha256 hash stored in the package file.

Ideally we would have crew offer the option of creating the binary package archive when building, and also adding the binary package info to the package.rb file, which it could then use to install the package.

(The package could just be stored in `/usr/local/tmp/packages`, with URLs pointing to `file:///usr/local/tmp/packages/...`)

This would help with users testing builds too...

**Comment by saltedcoffii** [comment]
Perhaps a `crew build -i` would work, -i being for install binary after successful build.

**Comment by Zopolis4** [comment]
This currently works with `CREW_CACHE_ENABLED=1 crew build`, right?
