### ISSUE TITLE
What is the use-case for eudev and the WSL udev stub?

### ISSUE THREAD

**Issue by chromakey-io** [chromebrew/chromebrew#6088]
There is already a udev process running as root on chrome os.  You can't run one in userspace ... and you can't run TWO in root-space :)

These are both tools that need to be running as root, and without another udev system *already* running.  They cannot be run in userspace, as they access /dev devices... usb ... serial ... sda ... and so on.  These are simply not user-space tools, and with chromebrew seemingly trrying to provide an entirely userspace oriented system .... I'm a little confused about why they've been included in the project.

If someone can provide some documentation or some sort of use-case as to why these tools have been included in chromebrew I'd love to hear it.

**Comment by satmandu** [comment]
I suspect the simplest reason is that lots of packages look for udev libraries, and won't build without them... but then when running, they don't care if udev isn't functional.

So even a stub eudev install is useful during package builds.

**Comment by chromakey-io** [comment]
Aye, but if they are actually *using* udev when they run, they'll be using the system's root udev .... and you will have to modify the rules.d files to give access to chronos.

Which begs the question, what should be the policy surrounding that?

For example I've built a pull request that implements ssh support for FIDO2 keys.  It needs access to thee hidraw devices through udev, but obviously the eudev and WSL-stub systems are useless, and it has to rely upon the root system's udev for access.

I guess maybe we could work with a chroot environment like crouton, and maybe that would work  .... or a container based system (but I still think you'd have to modify some root-system level rules.d to pass udev through).  Though hidraw is blocked from access through the traditional crosvm->vsh termina->debian system built into chrome.  So for those of us that *need* FIDO2 for SSH and perhaps other use-cases  I feel like we *need* to come up with some sort of acceptable solution.

If packages are requiring udev for their builds, they are likely using the root system's udev daemon.  Maybe most are lucky in that they don't have to modify rules.d stuff, but I can'tt imagine *most* of these apps will work without modifying the root's rules.d to give access to chronos as it's all locked down pretty tightly to give access only to root, and filtered by various usb-blockers and other oddities before they reach user-space and crosvm/containers/etc.

**Comment by satmandu** [comment]
Crouton bind mounts udev folders... Maybe we could do that?
