### ISSUE TITLE
App Request (Binance)

### ISSUE THREAD

**Issue by Thisuu** [chromebrew/chromebrew#6304]
**Binance** is the largest cryptocurrency exchange by trading volume.

Since Binance app on PlayStore is not available for ChromeOS, it would be really useful to have it as a native software.

Source: https://ftp.binance.com/electron-desktop/linux/production/binance-amd64-linux.deb

Here's the aur PKGBUILD file of Binance for reference, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=binance

**Comment by saltedcoffii** [comment]
This would not be difficult to put together. Maybe you would be willing to create the packagefile? Check out `/usr/local/lib/crew/packages/template.rb.template` to give you an idea of how you might make the package.

**Comment by Thisuu** [comment]
Just to see how it goes, I tried executing the Binance binary. And here was the result:
![Screenshot 2021-10-16 8 00 50 AM](https://user-images.githubusercontent.com/13273054/137570238-412fb801-be22-4e04-a3e2-d95c64df95b0.png)
