### ISSUE TITLE
Postinstall for crew_profile_base not running on i686 during installs

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#6970]
Here's a build log from a container build:

[crewbuild-alex-i686.m58-build.log](https://github.com/skycocker/chromebrew/files/8482804/crewbuild-alex-i686.m58-build.log)

Ideas @supechicken ?

**Comment by supechicken** [comment]
That's weird. It runs on my `setarch i686+chroot` setup (issue with `qemu`?)

Does the postinstall run with `crew postinstall crew-profile-base`?

**Comment by satmandu** [comment]
Yeah, that works fine.

Maybe it is just an issue during my container setup?
