### ISSUE TITLE
JDK8 package does not have any binaries

### ISSUE THREAD

**Issue by saltedcoffii** [chromebrew/chromebrew#7097]
As JDK8 is a buildessential package, I am marking this as high priority. @satmandu can you work on building binaries or send me the source code on slack? I'm having trouble getting the oracle java sources.

**Comment by satmandu** [comment]
The solution would be to remove it from `buildessential`.  See https://github.com/skycocker/chromebrew/issues/7094

**Comment by kjperkin** [comment]
Seems like it is a transitive dependency coming in from `gtk-doc`, which depends on `fop`, which depends on `jdk8`. `fop` is needed for PDF support in `gtk-doc`.

It seems to me like there's too many packages in `buildessential`. If you take a look at debian and Ubuntu, there's only six direct dependencies, which amount to a C/C++ compiler, GNU make, and a libc.

**Comment by satmandu** [comment]
Is jdk8 a build or runtime dependency for fop and gtk-doc?

**Comment by uberhacker** [comment]
jdk8 is a runtime dependency of fop and gtk_doc has a runtime dependency of fop.  I agree with @kjperkin.  We need to reduce the build dependencies.

**Comment by satmandu** [comment]
Why not just delete gtk_doc from `buildessential`?

**Comment by saltedcoffii** [comment]
We've needed to pare down buildessential for a looong time anyway

**Comment by saltedcoffii** [comment]
Okay, here's what I'm thinking: right now our Java SE from Oracle requires a login, and we can't distribute their binaries. Thankfully, OpenJDK is open source, and we can compile some binaries, but there are a couple different ways we could do this, and I wanted input from @satmandu @uberhacker @Zopolis4 and @supechicken about what y'all thought. I've also been looking at [some](https://github.com/alpinelinux/aports/blob/master/community/openjdk8/APKBUILD) [various](https://github.com/archlinux/svntogit-packages/blob/master/java8-openjdk/trunk/PKGBUILD) [build](https://github.com/gentoo/gentoo/blob/master/dev-java/openjdk-bin/openjdk-bin-8.332_p09.ebuild) [files](https://github.com/void-linux/void-packages/blob/master/srcpkgs/openjdk8/template) to see how other distros are doing it.
Building OpenJDK is a bit awkward because it requires the existence of another already-built JRE of the same version or one major version prior.
Here are a few of our options:
- We can use [adoptium](https://adoptium.net) prebuilt binaries, but they don't have any prebuilt binaries for x86 (our i686). If we choose this path, we may have to drop JDK support for i686.
- We can use the [standard OpenJDK](https://github.com/openjdk/jdk8u)
- We can use [icedtea](https://icedtea.classpath.org/) a version of the JDK patched specifically for Linux and Web use.
If we do options 2 or 3, we'll have to have a prebuilt JDK version to bootstrap off of, so maybe we can use ones from debian, archlinux or fedora.
One thing is for sure: we can't be asking users to log in and download proprietary software: that kinda destroys the "ease" part of chromebrew.

**Comment by satmandu** [comment]
We can build a version of OpenJDK with someone locally using an Oracle version of the JDK...

Then we just upload the OpenJDK binaries.

Better yet, create a jdk_bootstrap package which does that, which never has to be updated, and just have the regular jdk/openjdk packages have a build dependency on that.

**Comment by Zopolis4** [comment]
We could also use Amazon Corretto, it's recommended by Ghidra and has support for x86.

**Comment by saltedcoffii** [comment]
I'd like to use something fully open source, corretto doesn't seem to be that way, neither does oracle jdk.

**Comment by saltedcoffii** [comment]
https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b

**Comment by kjperkin** [comment]
Is it possible to use a different JDK on x86 vs. other platforms?

**Comment by saltedcoffii** [comment]
> Is it possible to use a different JDK on x86 vs. other platforms?

yeah it's possible! it would just make bugs a bit harder

**Comment by supechicken** [comment]
> We can build a version of OpenJDK with someone locally using an Oracle version of the JDK...
> 
> Then we just upload the OpenJDK binaries.
> 
> Better yet, create a jdk_bootstrap package which does that, which never has to be updated, and just have the regular jdk/openjdk packages have a build dependency on that.

However, it still requires user action to install the Oracle JDK if the user wants to build OpenJDK from the source, and I think we should avoid any user interactions when possible.

In summary, I'd prefer to use the adoptium JDK binaries instead of Oracle one as the bootstrap JDK package.

**Comment by kjperkin** [comment]
Same. Adoptium is well-known and popular. Much prefer we avoid trying to
roll our own for something this complex. For x86 we can use a different
flavor JDK as long as the license allows redistribution or there is a
direct download link that doesn't violate the source's terms of service.

**Comment by saltedcoffii** [comment]
we tried :( adoptium/adoptium-support#521

**Comment by cobalt2727** [comment]
Would this be acceptable?
https://www.azul.com/downloads/?version=java-17-lts&os=linux&architecture=x86-32-bit&package=jdk

**Comment by uberhacker** [comment]
The free version is only SE and not the SDK.

**Comment by uberhacker** [comment]
Thanks @cobalt2727: See #7351.
