### ISSUE TITLE
GNU GPL version 3 or any later version or version 3 only

### ISSUE THREAD

**Issue by saltedcoffii** [chromebrew/chromebrew#7126]
There's a bit of confusion throughout the Chromebrew project as to whether Chromebrew is under a GPLv3 only license or GPLv3+ license. In the [README](https://github.com/skycocker/chromebrew/blob/729178cae73bdd4e98fa95ed58a4622bd813e2c3/README.md?plain=1#L156) it says GPLv3+, and in the [LICENSESTRING](https://github.com/skycocker/chromebrew/blob/729178cae73bdd4e98fa95ed58a4622bd813e2c3/bin/crew#L58) it says GPLv3 only.

@skycocker could you tell us what your original license was, so we can fix it? Other contributors ( @uberhacker @satmandu @supechicken @Zopolis4 ), what do you think is the best for the project? We should probably fix this sooner than later.

**Comment by Zopolis4** [comment]
I think GPLv3+ is best, just in case there is a GPLv4. Always good to future-proof things lest there is a v4 and that leads to license incompatibilities.
