### ISSUE TITLE
Flatpak is not working

### ISSUE THREAD

**Issue by saltedcoffii** [chromebrew/chromebrew#7127]
It is more and more painfully obvious that our Flatpak setup is not working, and many users are reporting this. This issue is to track returning Flatpak functionality to Chromebrew.

**Comment by uberhacker** [comment]
I wouldn't sweat it.  This is just another package manager than can conflict with this project.

**Comment by cobalt2727** [comment]
I'd disagree, having Flatpak working properly is _huge_ for desktop application usage. There's no conflict - you can have the same app installed from Flathub and the distro's package manager at the same time if you want to, each with their own config settings. That aside, the current chromebrew package for Flatpak should either be fixed or removed outright until a working version is published. This was my experience with installing it today:

```ruby
chronos@localhost / $ crew install flatpak
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
flatpak: Flatpak is a system for building, distributing, and running sandboxed desktop applications on Linux.
https://flatpak.org
Version: 1.10.2-1
License: LGPL-2.1+
Performing pre-flight checks...
Precompiled binary available, downloading...
Flatpak archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 73 files.
Now have 73 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 9560346 bytes or 9 MiB
Removed 66 files due to unique sizes from list. 7 files left.
Now eliminating candidates based on first bytes: removed 5 files from list. 2 files left.
Now eliminating candidates based on last bytes: removed 2 files from list. 0 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 0 files left.
It seems like you have 0 files that are not unique
Totally, 0 B can be reduced.
Now making hard links.
Making 0 links.
Performing post-install for flatpak...
bash: _parse_usage: line 16: syntax error near unexpected token `('
bash: _parse_usage: line 16: ` -?(\[)+([a-zA-Z0-9?]))'
bash: error importing function definition for `_parse_usage'
bash: _longopt: line 6: syntax error near unexpected token `('
bash: _longopt: line 6: ` --!(no-*)dir*)'
bash: error importing function definition for `_longopt'
bash: _parse_usage: line 16: syntax error near unexpected token `('
bash: _parse_usage: line 16: ` -?(\[)+([a-zA-Z0-9?]))'
bash: error importing function definition for `_parse_usage'
bash: _longopt: line 6: syntax error near unexpected token `('
bash: _longopt: line 6: ` --!(no-*)dir*)'
bash: error importing function definition for `_longopt'
ownership of '/var/run/chrome/dconf/user' retained as chronos:chronos
ownership of '/var/run/chrome/dconf/' retained as chronos:chronos

Configuring flathub
bash: _parse_usage: line 16: syntax error near unexpected token `('
bash: _parse_usage: line 16: ` -?(\[)+([a-zA-Z0-9?]))'
bash: error importing function definition for `_parse_usage'
bash: _longopt: line 6: syntax error near unexpected token `('
bash: _longopt: line 6: ` --!(no-*)dir*)'
bash: error importing function definition for `_longopt'

Note that the directories 

'/usr/local/var/lib/flatpak/exports/share'
'/usr/local/.config/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.


Flatpak installed!
chronos@localhost / $ flatpak --version
/bin/bash: _parse_usage: line 16: syntax error near unexpected token `('
/bin/bash: _parse_usage: line 16: ` -?(\[)+([a-zA-Z0-9?]))'
/bin/bash: error importing function definition for `_parse_usage'
/bin/bash: _longopt: line 6: syntax error near unexpected token `('
/bin/bash: _longopt: line 6: ` --!(no-*)dir*)'
/bin/bash: error importing function definition for `_longopt'
ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists
error: Unknown option --user

See '/usr/local/libexec/flatpak/flatpak --help'
chronos@localhost / $ 
```

**Comment by uberhacker** [comment]
I'm not sure what you are talking about with the same app installed from different package managers.  That doesn't even make any sense.  There will be conflicts and the results will be confusing at the least.

**Comment by cobalt2727** [comment]
I'll let the devs speak for themselves:
https://docs.flatpak.org/en/latest/introduction.html

**Comment by satmandu** [comment]
IIRC flatpak requires some bind mounts to get working, and also requires getting bubblewrap to work. These broke after some security tightening by Google around M92. Feel free to help get those packages fixed!

**Comment by uberhacker** [comment]
@cobalt2727: I have tried Flatpak.  I've also tried Snaps and AppImages.  I tend to think all of these extra ways of installing apps is not helping to create anything universal and ubiquitous.  All it does is create more confusion and a complete mess of your userspace.  The following statement goes against the whole philosophy of sandboxes apps:
```
Space efficiency: Flatpak deduplicates libraries and other files used by multiple applications to save megabytes or even gigabytes worth of storage depending on the amount of applications installed.
```
If this is what Flatpak claims then they need to not say:
```
Stability: breakage in a Flatpak application will not risk the system from breaking. This is because Flatpak applications and runtimes are contained to not interfere with the system altogether.
```
These statements are not mutually inclusive.  Sharing libraries is one of the biggest reasons instabilities are introduced between apps.  If they were truly sandboxing apps, this scenario would never happen.  With that said, it's the sandboxing that creates the bloat that this project is trying hard to limit in every way.

**Comment by cobalt2727** [comment]
`Space efficiency: Flatpak deduplicates libraries and other files used by multiple applications to save megabytes or even gigabytes worth of storage depending on the amount of applications installed.`

I'm pretty sure this is only true between multiple _Flatpak_ applications that share the same libraries (also installed via Flatpak)

It doesn't mess with system libs - take a look at [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) for an example of how the sandboxing works.

**Comment by JakoDel** [comment]
> @cobalt2727: I have tried Flatpak. I've also tried Snaps and AppImages. I tend to think all of these extra ways of installing apps is not helping to create anything universal and ubiquitous. All it does is create more confusion and a complete mess of your userspace. The following statement goes against the whole philosophy of sandboxed apps:
> 
> ```
> Space efficiency: Flatpak deduplicates libraries and other files used by multiple applications to save megabytes or even gigabytes worth of storage depending on the amount of applications installed.
> ```
> 
> If this is what Flatpak claims then they need to not say:
> 
> ```
> Stability: breakage in a Flatpak application will not risk the system from breaking. This is because Flatpak applications and runtimes are contained to not interfere with the system altogether.
> ```
> 
> These statements are not mutually inclusive. Sharing libraries is one of the biggest reasons instabilities are introduced between apps. If they were truly sandboxing apps, this scenario would never happen. With that said, it's the sandboxing that creates the bloat that this project is trying hard to limit in every way.

We users are of course in no position to demand something, your work is amazing guys.
I feel like having flatpak working would take a huge weight off your shoulders, many apps are available on there, even wine which hasn't been working for quite a long time here. Yeah those two statements from Flatpak feel like the opposite to me, but the extra packages and functionality outweigh the bloat it may produce, in my opinion.

**Comment by cobalt2727** [comment]
> Yeah those two statements from Flatpak seem like the opposite to me, someone should look into it.

the two statements are consistent - the section regarding space efficiency refers to libraries being shared between Flatpaks, not between Flatpak apps and system apps

**Comment by IngwiePhoenix** [comment]
I just installed FydeOS in a VM (using their official VMWare image) and added Chromebrew to it. When attempting to install flatpak, I get an error that `org.gnome.system.proxy` is missing; which prevents adding the default flathub repository.

Any idea how I can fix that?

**Comment by eudy97** [comment]
for what's is worth, managed to get flatpak working without getting any of these errors:

ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists
Note that the directory 

'/usr/local/var/lib/flatpak/exports/share'

to get rid of those errors I did the following:

1. ctrl + alt + t
2. shell
3. crew install flatpak
4. rm -r /usr/local/bin/flatpak
5. ln -s /usr/local/libexec/flatpak/flatpak /usr/local/bin/flatpak
6. sudo mount -o remount,exec ~
7. exit
8. shell
9. flatpak update 

I can install and run apps like lutris to a certain extent but those that use bubblewrap like Chrome give me this error:

bwrap: Can't bind mount /oldroot/var/run/chrome/dconf on /newroot/var/run/chrome/dconf: Unable to mount source on destination: Too many levels of symbolic links

**Comment by NishantMajumdar** [comment]
Hello.
Can you look into this error, when launching any app: 
```
F: Not replacing "/usr/local/.config/.local/share/flatpak" with tmpfs: Path "/usr" is reserved by Flatpak
F: Can't find a11y bus: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.a11y.Bus received signal 5
bwrap: Failed to mount tmpfs: Operation not permitted
```

**Comment by UCYT5040** [comment]
Having similar error to @NishantMajumdar for any app. Hopefully this can be fixed.

**Comment by yeesterPlus** [comment]
verbose:
```
ln: failed to create symbolic link '/home/chronos/user/.local/share/fonts': File exists

Note that the directory 

'/usr/local/var/lib/flatpak/exports/share'

is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

F: No installations directory in /usr/local/etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /usr/local/var/lib/flatpak
F: Opening user flatpak installation at path /usr/local/.config/.local/share/flatpak
F: Opening user flatpak installation at path /usr/local/.config/.local/share/flatpak
F: Opening user flatpak installation at path /usr/local/.config/.local/share/flatpak
F: /usr/local/.config/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/232eeb0ac8c31b9768099c037e90fdfb96423bdd16d6d80e07628824ef2ed0b1/files/lib32 does not exist
F: Cleaning up unused container id 1626518264
F: Cleaning up per-app-ID state for org.blender.Blender
F: Allocated instance id 3384108792
F: Add defaults in dir /org/blender/Blender/
F: Add locks in dir /org/blender/Blender/
F: Document portal not available, not mounting /run/flatpak/doc
F: Allowing dri access
F: Allowing host-fs access
F: Not sharing "/postinst" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/run/media" with sandbox: Unable to open path "/run/media": No such file or directory
F: Not sharing "/run/spnav.sock" with sandbox: Unable to open path "/run/spnav.sock": No such file or directory
F: Not replacing "/usr/local/.config/.local/share/flatpak" with tmpfs: Path "/usr" is reserved by Flatpak
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/usr/local/.config/pulse/client.conf': Error opening file /usr/local/.config/pulse/client.conf: No such file or directory
F: Pulseaudio user configuration file '/etc/pulse/client.conf': Error opening file /etc/pulse/client.conf: No such file or directory
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running '/usr/local/bin/bwrap --args 39 /usr/local/libexec/flatpak-dbus-proxy --args=43'
F: Running '/usr/local/bin/bwrap --args 40 blender'
bwrap: setting up uid map: Operation not permitted
```

**Comment by 995qa** [comment]
Having some issues with flatpak as well.

<img width="883" height="49" alt="Image" src="https://github.com/user-attachments/assets/8b3909f8-ff8c-4808-a96e-0f15315dfb75" />
