### ISSUE TITLE
Unable to install chromebrew

### ISSUE THREAD

**Issue by t1qeri** [chromebrew/chromebrew#7155]
## Description
Unable to install chromebrew (Pixel Chromebook 2013 | x86-x64).
I get an error GLIBC_2.27 not found.

I executed this command:
```shell
curl -Ls git.io/vddgY | bash
```

Part of Output:
```
Adding new information on rsync to device.json...
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-3.1.2-2-chromeos-x86_64.tar.zst: OK
Extracting ruby ...
Installing ruby ...
Adding new information on ruby to device.json...

Creating symlink to 'crew' in /usr/local/bin/

'/usr/local/bin/crew' -> '../lib/crew/bin/crew'

Setup and synchronize local package repo...

Cloning into '/usr/local/lib/crew'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), 52.51 KiB | 17.50 MiB/s, done.
remote: Enumerating objects: 1938, done.
remote: Counting objects: 100% (1938/1938), done.
remote: Compressing objects: 100% (1757/1757), done.
remote: Total 1938 (delta 215), reused 517 (delta 181), pack-reused 0
Receiving objects: 100% (1938/1938), 1.50 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (215/215), done.
Updating files: 100% (1938/1938), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
warning: pass a leading slash before paths such as 'install.sh' if you want a single file (see NON-CONE PROBLEMS in the git-sparse-checkout manual).
HEAD is now at 4bc7ac3 Codium 1.67.2 => 1.68.1 (#7148)

Updating crew package information...

ruby: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/libruby.so.3.1)
ruby: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib64/libruby.so.3.1)
ruby: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/libruby.so.3.1)
ruby: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib64/libruby.so.3.1)
```

## Versions and system information
***
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F26D159B-52A3-491A-AE25-B23670A66B32}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F26D159B-52A3-491A-AE25-B23670A66B32}
CHROMEOS_RELEASE_BOARD=link-signed-mp-v5keys
CHROMEOS_RELEASE_BRANCH_NUMBER=78
CHROMEOS_RELEASE_BUILDER_PATH=link-release/R69-10895.78.0
CHROMEOS_RELEASE_BUILD_NUMBER=10895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=69
CHROMEOS_RELEASE_DESCRIPTION=10895.78.0 (Official Build) stable-channel link 
CHROMEOS_RELEASE_KEYSET=mp-v5
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10895.78.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10895.78.0
***

**Comment by saltedcoffii** [comment]
Could you check the version of glibc for me? run:
```
/lib64/libc.so.6 --version
```

**Comment by t1qeri** [comment]
glibc version:
```
GNU C Library (Gentoo 2.23-r18 p6) stable release version 2.23, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.9.x 20150123 (prerelease).
Available extensions:
        C stubs add-on version 2.1.2
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://crbug.com/new>.
```

**Comment by satmandu** [comment]
This machine is EOL. Is there a newer ChromeOS release you can update to?

**Comment by t1qeri** [comment]
No, I have the latest available update installed.

Is it possible to update glibc manually? Or can I build ruby from the source code on the machine itself? 

As I understand it, if I manage to install ruby, then crew will work. And then I would be able to install older versions of packages that support glibc 2.23.

**Comment by satmandu** [comment]
Sorry to have dropped this. Are you still trying to use this hardware? Maybe installing another linux distribution might be more useful, since that would bring an updated kernel and glibc? You will need to[ update the firmware ](https://wiki.mrchromebox.tech/Supported_Devices)to do that.

We are definitely not supporting glibc 2.23 on x86_64, and all software for x86_64 is mostly built against glibc 2.27.

You might also consider using brunch, but that will also require you to update the firmware: https://github.com/sebanc/brunch

Let us know if you need more assistance?
