### ISSUE TITLE
[install.sh]: latest version of `git` throw errors

### ISSUE THREAD

**Issue by supechicken** [chromebrew/chromebrew#7181]
```
Setup and synchronize local package repo...

Cloning into '/usr/local/lib/crew'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), 52.64 KiB | 555.00 KiB/s, done.
remote: Enumerating objects: 1943, done.
remote: Counting objects: 100% (1943/1943), done.
remote: Compressing objects: 100% (1762/1762), done.
remote: Total 1943 (delta 215), reused 537 (delta 181), pack-reused 0
Receiving objects: 100% (1943/1943), 1.50 MiB | 2.56 MiB/s, done.
Resolving deltas: 100% (215/215), done.
Updating files: 100% (1943/1943), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
fatal: 'install.sh' is not a directory; to treat it as a directory anyway, rerun with --skip-checks
```

**Comment by uberhacker** [comment]
x86_64 architecture?  @satmandu?

**Comment by satmandu** [comment]
That's so weird...

**Comment by satmandu** [comment]
Crew update is working fine... There's something weird about the sparse checkout maybe?

**Comment by pierro78** [comment]
same issue here 

last output when running "curl -Ls git.io/vddgY |bash -x" :  

`
Already on 'master'
Your branch is up to date with 'origin/master'.
+ git sparse-checkout set packages lib bin crew tools install.sh
fatal: 'install.sh' is not a directory; to treat it as a directory anyway, rerun with --skip-checks
`

is there a workaround maybe ??

thanks !

**Comment by satmandu** [comment]
Simplest workaround otherwise would be to also pipe through sed to remove install.sh before piping to bash.

**Comment by uberhacker** [comment]
You could also execute after downloading with:
```
curl -Ls git.io/vddgY -o install.sh && bash install.sh && rm install.sh
```
Just make sure you execute in a directory you have write access.
