### ISSUE TITLE
[ldc] Unable to execute ldmd2

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7191]
```
$ ldmd2
ldmd2: error while loading shared libraries: libLLVMLTO.so.5: cannot open shared object file: No such file or directory
```

**Comment by satmandu** [comment]
Does a rebuild fix it?

**Comment by uberhacker** [comment]
No, this is an unusual build since the d compiler is needed to compile d itself.  A true chicken before the egg scenario.

**Comment by cstrouse** [comment]
Is there a bootstrap compiler available like Go and some of the Lisps both make available?

**Comment by uberhacker** [comment]
There is another project: https://github.com/dlang/dmd.  Even this needs a d compiler to build.

**Comment by saltedcoffii** [comment]
doesn't the GNU Compiler Collection provide a D compiler?

**Comment by satmandu** [comment]
Rebuilding gcc with d support might be sufficient to provide a bootstrapping d compiler for ldc... Feel free to try that?

**Comment by Zopolis4** [comment]
Building GCC 10 with D enabled then using the `gdc` from that to build the latest GCC with D enabled should allow us to have a proper package for `ldc`, but since we don't right now, this issue is no longer relevant.
