### ISSUE TITLE
JDK17 package needs updating. Version change.

### ISSUE THREAD

**Issue by graffixjones** [chromebrew/chromebrew#7244]
## Description

Tried to install JDK17. Package looks for JDK version 17.0.3.1, but 17.0.4 is the current available version.

## Versions and system information

***
chronos@localhost ~ $ crew sysinfo
fatal: ambiguous argument 'HEAD^..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.4.192-18528-g99def3bea7a0`

- Chromebrew version: `1.24.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ``

- OS variant: `Chrome OS`
- OS version: `fizz-release/R103-14816.131.0`
- OS channel: `stable-channel`***

## Additional information

I manually updated the version in the JDK17.rb package, along with the file checksum, which allowed 17.0.4 to install without a problem. Easy fix.

**Comment by satmandu** [comment]
@uberhacker

**Comment by uberhacker** [comment]
@graffixjones:  You are welcome to submit a pull request.

**Comment by cobalt2727** [comment]
https://github.com/chromebrew/chromebrew/pull/7369

**Comment by uberhacker** [comment]
Fixed by #7369.
