### ISSUE TITLE
crew remove issue

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#7264]
I previously had `gcc11` installed.
Trying to uninstall I see this:
```
crew remove gcc11
/usr/local/bin/crew:1608:in `remove': private method `remove' called for nil:NilClass (NoMethodError)

  @pkg.remove
      ^^^^^^^
        from /usr/local/bin/crew:1835:in `block in remove_command'
        from /usr/local/bin/crew:1834:in `each'
        from /usr/local/bin/crew:1834:in `remove_command'
        from /usr/local/bin/crew:1908:in `<main>'
```

**Comment by satmandu** [comment]
Any ideas @supechicken ?

**Comment by saltedcoffii** [comment]
I was working on this for a bit actually, and I have an idea!  lemme see if i can work on it later, we'll see.

**Comment by supechicken** [comment]
#### My tentative idea on this error
- The `gcc11.rb` package recipe was removed in #7076 
- `crew` tries to `set_package('gcc11.rb')`, but skipped due to `!File.exist?()`
- `crew` trying to call `def self.remove` function in `gcc11.rb`
- `@pkg.remove` is called, but `@pkg` was not set (`set_package` was skipped)
- Error occured

#### Possible solution
- Modify the line `@pkg.remove` to `@pkg&.remove` so the `.remove` will not be executed when `@pkg == nil`
- Stop when the package recipe not exist (not sure will it break `crew`)

**Comment by satmandu** [comment]
Should we clear out an entry in the json file if it exists but no pakage.rb file exists and we have invoked remove?

**Comment by supechicken** [comment]
> Should we clear out an entry in the json file if it exists but no package.rb file exists, and we have invoked remove?

Do you mean running the removal automatically for user? Not sure if it is a good idea...

**Comment by saltedcoffii** [comment]
I was thinking something along the lines of:


crew remove is invoked:
if pkg in pkglist:
  remove package as normal
elif pkg not in pkglist but pkg is installed:
  delete filelist and also delete directory list if the directories are empty after deleting filelist
else:
  error

**Comment by supechicken** [comment]
> I was thinking something along the lines of:
> 
> crew remove is invoked: if pkg in pkglist: remove package as normal elif pkg not in pkglist but pkg is installed: delete filelist and also delete directory list if the directories are empty after deleting filelist else: error

The `directorylist` and `filelist` will be removed by default after `crew remove` already :)
https://github.com/chromebrew/chromebrew/blob/de5bf96d410246167ccab403ee0cefa298b3ad39/bin/crew#L1593-L1595

**Comment by Zopolis4** [comment]
I had this issue, and solved it with just reinstalling crew. Maybe there should be some method to save all of the installed packages to a list, then removing and reinstalling the entirety of crew?

**Comment by uberhacker** [comment]
> I had this issue, and solved it with just reinstalling crew. Maybe there should be some method to save all of the installed packages to a list, then removing and reinstalling the entirety of crew?

How about `crew list installed > packages.txt`?

**Comment by satmandu** [comment]
> > I had this issue, and solved it with just reinstalling crew. Maybe there should be some method to save all of the installed packages to a list, then removing and reinstalling the entirety of crew?
> 
> How about `crew list installed > packages.txt`?

`crew list installed -d > packages.txt`

There's also a json way to do it with jq...

**Comment by Zopolis4** [comment]
I presume this case is covered by `lib/fixup.rb` now, right?
