### ISSUE TITLE
mpv cannot run

### ISSUE THREAD

**Issue by digby5** [chromebrew/chromebrew#7324]
## Description
 running mpv from terminal  outouts error. mpv: error while loading shared libraries: libcdio.so.18: cannot open shared object file: No such file or directory

also tried to do  a crew-launcher add mpv and it outputs:
/usr/local/bin/crew-launcher:84:in `CreateProfile': undefined method `sub' for nil:NilClass (NoMethodError)

    exec: desktop['Desktop Entry']['Exec'].sub(/%[A-Za-z]/, ''),
                                          ^^^^
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'

If you executed a specific command:
```shell
# your command here
```
mpv
Output:
```
# output of your command here
```
mpv: error while loading shared libraries: libcdio.so.18: cannot open shared object file: No such file or directory

## Versions and system information

***
***

**Comment by satmandu** [comment]
Does `crew reinstall -s mpv` fix the issue?

**Comment by digby5** [comment]
the reinstall bugged out:

/usr/local/lib/crew/lib/package.rb:266:in `system': Command failed with exit 1: bash
mpv failed to install: `CFLAGS="-O2 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto" CXXFLAGS="-O2 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto" FCFLAGS="-O2 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto" FFLAGS="-O2 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto" LDFLAGS="-flto " bash -c ./bootstrap.py` exited with 1

**Comment by satmandu** [comment]
Looks like libcdio_paranoia needs to be updated... I'm building some updates for this now...
