### ISSUE TITLE
remmina is missing rdp plugin

### ISSUE THREAD

**Issue by digby5** [chromebrew/chromebrew#7328]
## Description

remmina has rdp plugin by default in linux but its missing here. i tried the -s option too but it bugged out. i tried searching for the plugin with crew but couldnt find anything
If you executed a specific command:
```shell
# your command here
```
remmina
Output:
```
# output of your command here
```

## Versions and system information

***
***

**Comment by uberhacker** [comment]
@digby5:  Thank you for the issue.  Can you please complete the command output and include the output of `cat /etc/lsb-release` along with the result of `arch`?

**Comment by digby5** [comment]
remmina was launched via crew-launcher so no cli output. when u select the plugin menu or add a new connection, there is just no rdp listed. the output is:

CHROMEOS_ARC_ANDROID_SDK_VERSION=30
CHROMEOS_ARC_VERSION=8843059
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={77BE25D7-AFB8-4E3C-A7D2-1FACE1B186E3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={77BE25D7-AFB8-4E3C-A7D2-1FACE1B186E3}
CHROMEOS_RELEASE_BOARD=volteer-signed-mp-v8keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=volteer-release/R104-14909.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=14909
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=104
CHROMEOS_RELEASE_DESCRIPTION=14909.100.0 (Official Build) stable-channel volteer 
CHROMEOS_RELEASE_KEYSET=mp-v8
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14909.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14909.100.0

this is on  a lenovo flex 5 with pentium 7505

**Comment by satmandu** [comment]
remmina rebuild incoming...

**Comment by satmandu** [comment]
Will you see if this fixes your issue?
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=remmina CREW_TESTING=1 crew update ; crew upgrade
```

**Comment by satmandu** [comment]
This is a symlink problem with freerdp.

Do this:
```
rm /usr/local/lib64/libcrypt.so.1
ln -s /usr/lib64/libcrypt.so.1 /usr/local/lib64/libcrypt.so.1
```

remmina should then have rdp available.

**Comment by digby5** [comment]
tried those commands, still no rdp plugin. ran remmina in cli and got this:
utput by using "G_MESSAGES_DEBUG=all" as an environment variable.
More info available on the Remmina wiki at:
https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-debugging
Load modules from /usr/local/lib64/remmina/plugins Failed to load plugin: /usr/local/lib64/remmina/plugins/remmina-plugin-rdp.so.
Error: libswscale.so.5: cannot open shared object file: No such file or directory
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.
[glibsecret] unable to get secret service: Unknown or unsupported transport ?disabled? for address ?disabled:?

i checked the directory and the remmina-plugin-rdp.so is there so i dont know whats up

**Comment by satmandu** [comment]
The new version of remmina is built against the newer version of ffmpeg, which contains `libswscale.so.6`...
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ lddtree /usr/local/lib/remmina/plugins/remmina-plugin-rdp.so | grep swscale
        /usr/local/lib/libswscale.so.6 => /usr/local/lib/libswscale.so.6
```
