### ISSUE TITLE
error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short

### ISSUE THREAD

**Issue by him5** [chromebrew/chromebrew#7366]
## Description
crew autoremove removes almost every package? i feel like i forked this device now, but almost ANY (except git for some reason?) command just says the text in the title... it happened after running the commands below... so i cant get any packages, cant even run crew, or crouton, nothing works, except for git for some reason (edit: some commands work w/ sudo, but i cant execute them normally)

If you executed a specific command:
```shell
crew autoremove
crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync 
```

Output:
```
Proceeding...
attr: Commands for Manipulating Filesystem Extended Attributes.
Precompiled binary available, downloading...
Attr archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync is not working. Please (re)install it with 'crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync'
acl: Commands for Manipulating POSIX Access Control Lists.
Precompiled binary available, downloading...
Acl archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync is not working. Please (re)install it with 'crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync'
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Precompiled binary available, downloading...
Glibc archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync is not working. Please (re)install it with 'crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync'
lz4: LZ4 is lossless compression algorithm, providing compression speed at 400 MB/s per core (0.16 Bytes/cycle).
Precompiled binary available, downloading...
Lz4 archive downloaded.
Unpacking archive using 'tar', this may take a while...
sh: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
/usr/local/bin/crew:838:in `system': Command failed with exit 127: PATH=/usr/local/share/musl/bin:$PATH tar -Izstd -xf lz4-1.9.4-chromeos-x86_64.tar.zst -C lz4.20220904014903.dir (RuntimeError)
        from /usr/local/bin/crew:838:in `block in unpack'
        from /usr/local/bin/crew:811:in `chdir'
        from /usr/local/bin/crew:811:in `unpack'
        from /usr/local/bin/crew:1365:in `install'
        from /usr/local/bin/crew:1344:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1340:in `each'
        from /usr/local/bin/crew:1340:in `resolve_dependencies'
        from /usr/local/bin/crew:1277:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1756:in `block in install_command'
        from /usr/local/bin/crew:1751:in `each'
        from /usr/local/bin/crew:1751:in `install_command'
        from /usr/local/bin/crew:1875:in `<main>'
```

## Versions and system information

CHROMEOS_ARC_ANDROID_SDK_VERSION=30
CHROMEOS_ARC_VERSION=8966747
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9A3BE5D2-C3DC-4AE6-9943-E2C113895DC5}
CHROMEOS_RELEASE_BOARD=octopus-signed-mp-v31keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=octopus-release/R105-14989.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=14989
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=105
CHROMEOS_RELEASE_DESCRIPTION=14989.58.0 (Official Build) beta-channel octopus 
CHROMEOS_RELEASE_KEYSET=mp-v31
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14989.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14989.58.0
***
***

**Comment by supechicken** [comment]
The `autoremove` command is broken for a long while...

Could you see if the following command fixes the error?
```shell
sudo ln -sf /lib64/libc.so.6 /usr/local/lib64/libc.so.6
```

**Comment by him5** [comment]
the command worked
