### ISSUE TITLE
nvim: error while loading shared libraries: /usr/local/lib64/libluv.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Metal-Toilet** [chromebrew/chromebrew#7382]
## Description
Thank you so much to the person who fixed my last issue but a very similar issue is back. Getting an error trying to open neovim again.

```shell
nvim
```
Output:
```
nvim: error while loading shared libraries: /usr/local/lib64/libluv.so.1: cannot open shared object file: No such file or directory
```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `4.19.241-13212-ge9b0bab46475`

- Chromebrew version: `1.25.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: eb4bae1 `coreutils => 9.1 (#7381) (14 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `cyan-release/R103-14816.131.0`
- OS channel: `stable-channel`
***

## Additional information
Its almost certainly the same issue as in #7367.

**Comment by satmandu** [comment]
Does `crew update ; crew upgrade ; crew reinstall libluv neovim` help?

**Comment by Metal-Toilet** [comment]
YES! Thank you for all your help samandu! It seems like you spent a lot of time helping me and i'm now successfully in neovim.
