### ISSUE TITLE
> ```

### ISSUE THREAD

**Issue by Bdieir** [chromebrew/chromebrew#7433]
I am an idiot that sends spamming messages :)

**Comment by Bdieir** [comment]
> ```
>     > ```
> ```
> 
> 
>      
>   
> 
> > Package to be built is: crosvm.rb
> > # Adapted from Arch Linux crosvm-git PKGBUILD at:
> > # https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=crosvm-git
> > require 'package'
> > class Crosvm < Package
> > description 'The Chrome OS Virtual Machine Monitor'
> > homepage 'https://chromium.googlesource.com/crosvm/crosvm'
> > version '7b5f6b1'
> > compatibility 'all'
> > license 'custom:chromiumos'
> > source_url 'https://chromium.googlesource.com/crosvm/crosvm'
> > git_hashtag '7b5f6b198fa2e3acc797175670fad8686db3e72e'
> > depends_on 'libcap'
> > depends_on 'dtc'
> > depends_on 'rust' => :build
> > depends_on 'wayland_protocols' => :build
> > def self.build
> > system 'cargo build --release'
> > end
> > def self.install
> > system "install -Dm755 target/release/crosvm #{CREW_DEST_PREFIX}/bin/crosvm"
> > system "install -d #{CREW_DEST_PREFIX}/share/policy/crosvm/"
> > system "cp -r seccomp/x86_64/* #{CREW_DEST_PREFIX}/share/policy/crosvm/"
> > system "install -m644 -D LICENSE #{CREW_DEST_PREFIX}/share/licenses/crosvm-git/LICENSE"
> > system "install -m644 -D README.md #{CREW_DEST_PREFIX}/share/licenses/crosvm-git/README.md"
> > end
> > end
> > /usr/local/lib/crew/lib/downloader.rb:64:in `downloader': undefined method `green' for nil:NilClass (NoMethodError)
> > ```
> >       Expected checksum (SHA256): #{sha256sum.green}
> >                                              ^^^^^^
> >     from /usr/local/bin/crew:744:in `block in download'
> >     from /usr/local/bin/crew:688:in `chdir'
> >     from /usr/local/bin/crew:688:in `download'
> >     from /usr/local/bin/crew:1484:in `build_package'
> >     from /usr/local/bin/crew:1465:in `resolve_dependencies_and_build'
> >     from /usr/local/bin/crew:1729:in `block in build_command'
> >     from /usr/local/bin/crew:1725:in `each'
> >     from /usr/local/bin/crew:1725:in `build_command'
> >     from /usr/local/bin/crew:1908:in `<main>'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > 
> >      
> >   
> > 
> > @supechicken ideas?
> > ```
> 
> 
> _Originally posted by @Bdieir in [#7278 (comment)](https://github.com/chromebrew/chromebrew/issues/7278#issuecomment-1260188832)_

**Comment by supechicken** [comment]
What's wrong with you?
