### ISSUE TITLE
Packages of active projects that need updates

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7440]
- [ ] android_studio | https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.16/android-studio-2021.3.1.16-linux.tar.gz | 2021.2.1.15 | 2021.3.1.16
- [ ] charm | https://github.com/charmbracelet/charm/releases/download/v0.12.4/charm_0.12.4_linux_x86_64.tar.gz | 0.12.1 | 0.12.4
- [ ] dart | https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.2/sdk/dartsdk-linux-x64-release.zip | 2.17.6 | 2.18.2
- [ ] dbeaver | https://github.com/dbeaver/dbeaver/releases/download/22.2.1/dbeaver-ce-22.2.1-linux.gtk.x86_64.tar.gz | 22.0.0 | 22.2.1
- [ ] dropbox | https://clientupdates.dropboxstatic.com/dbx-releng/client/dropbox-lnx.x86_64-158.4.4564.tar.gz | 48.4.58 | 158.4.4564
- [ ] dsq | https://github.com/multiprocessio/dsq/releases/download/v0.22.0/dsq-linux-x64-v0.22.0.zip | 0.18.0 | 0.22.0
- [ ] exodus | https://downloads.exodus.com/releases/exodus-linux-x64-22.9.28.zip | 22.3.31 | 22.9.28
- [ ] ferdi | https://github.com/getferdi/ferdi/releases/download/v5.8.1/Ferdi-5.8.1.AppImage | 5.8.0 | 5.8.1
- [ ] flutter | https://github.com/flutter/flutter/archive/3.3.3.tar.gz | 3.0.5 | 3.3.3
- [ ] freecad | https://github.com/FreeCAD/FreeCAD/releases/download/0.20.1/FreeCAD_0.20-1-2022-08-20-conda-Linux-x86_64-py310.AppImage | 0.19.2 | 0.20.1
- [ ] gcloud | https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-404.0.0-linux-x86_64.tar.gz | 402.0.0 | 404.0.0
- [ ] gitkraken | https://www.gitkraken.com/download | 6.5.4 | 13.6.7
- [ ] heroku | https://github.com/heroku/cli/archive/v7.63.4.tar.gz | 7.44.0 | 7.63.4
- [ ] hplip | https://downloads.sourceforge.net/project/hplip/hplip/3.22.6/hplip-3.22.6.tar.gz | 3.20.2 | 3.22.6
- [ ] imagemagick6 | https://github.com/ImageMagick/ImageMagick6/archive/<!DOCTYPE html> <html lang=.tar.gz | 6.9.11-29 | <!DOCTYPE html> <html lang=
- [ ] imagemagick7 | https://github.com/ImageMagick/ImageMagick/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] inxi | https://github.com/smxi/inxi/archive/<!DOCTYPE html> <html lang=.tar.gz | 811a19 | <!DOCTYPE html> <html lang=
- [ ] ipfs | https://github.com/ipfs/go-ipfs/archive/refs/tags/v0.15.0.tar.gz | 0.4.13 | refs/tags/v0.15.0
- [ ] jfrog | https://github.com/JFrogDev/jfrog-cli-go/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.39.5 | <!DOCTYPE html> <html lang=
- [ ] js78 | https://archive.mozilla.org/pub/firefox/releases/ |   version @_ver | not checked
- [ ] js91 | https://archive.mozilla.org/pub/firefox/releases/ |   version @_ver | not checked
- [ ] kbfsfuse | https://github.com/keybase/kbfs/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.0.40 | <!DOCTYPE html> <html lang=
- [ ] kbfsgit | https://github.com/keybase/kbfs/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.0.40 | <!DOCTYPE html> <html lang=
- [ ] keybase | https://github.com/keybase/client/archive/<!DOCTYPE html> <html lang=.tar.gz | 5.5.1 | <!DOCTYPE html> <html lang=
- [ ] kotlin | https://github.com/JetBrains/kotlin/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.5.20 | <!DOCTYPE html> <html lang=
- [ ] kr | https://github.com/kryptco/kr/archive/<!DOCTYPE html> <html lang=.tar.gz | 2.4.10 | <!DOCTYPE html> <html lang=
- [ ] kubectl | https://github.com/kubernetes/kubernetes/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.7.0 | <!DOCTYPE html> <html lang=
- [ ] ldc | https://github.com/ldc-developers/ldc/archive/refs/tags/v1.30.0.tar.gz | 1.7.0 | refs/tags/v1.30.0
- [ ] libadwaita | https://gitlab.gnome.org/exalm/libadwaita/ |   version @_ver | not checked
- [ ] libaom | https://aomedia.googlesource.com/aom/ | 3.0.0 | not checked
- [x] libcurl* | https://github.com/curl/curl/archive/<!DOCTYPE html> <html lang=.tar.gz |   version "#{@_ver}-1" | <!DOCTYPE html> <html lang=
- [ ] libefl | https://download.enlightenment.org/rel/libs/efl/ | 1.24.3 | not checked
- [ ] libepoxy | https://github.com/anholt/libepoxy/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.5.5 | <!DOCTYPE html> <html lang=
- [ ] libgpgerror* | https://www.gnupg.org/ftp/gcrypt/libgpg-error/ |   version @_ver | not checked
- [ ] libhandy | https://gitlab.gnome.org/GNOME/libhandy/-/tags |   version @_ver | not checked
- [ ] libimagequant | https://github.com/ImageOptim/libimagequant/archive/<!DOCTYPE html> <html lang=.tar.gz |   version "#{@_ver}-1" | <!DOCTYPE html> <html lang=
- [ ] libinput | https://www.freedesktop.org/software/libinput/ |   version @_ver.to_s | not checked
- [ ] libmbedtls | https://tls.mbed.org/download-archive | 2.16.8 | not checked
- [ ] libminigbm | https://chromium.googlesource.com/chromiumos/platform/minigbm.git |   version @_ver | not checked
- [ ] libnghttp2* | https://github.com/nghttp2/nghttp2/archive//<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] libnvme | https://github.com/linux-nvme/libnvme/archive/<!DOCTYPE html> <html lang=.tar.gz | v1.0-rc4 | <!DOCTYPE html> <html lang=
- [ ] librespot | https://github.com/librespot-org/librespot/archive/<!DOCTYPE html> <html lang=.tar.gz | 0.1.3 | <!DOCTYPE html> <html lang=
- [ ] librsvg | https://download.gnome.org/sources/librsvg/ | 2.54.4 | not checked
- [ ] libsoup | https://ftp.gnome.org/pub/GNOME/sources/libsoup |   version @_ver | not checked
- [ ] libva | https://github.com/intel/libva/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver.to_s | <!DOCTYPE html> <html lang=
- [ ] libx264 | http://ftp.videolan.org/pub/videolan/x264/snapshots |   version @_commit[0, 7] | not checked
- [ ] libyuv | https://chromium.googlesource.com/libyuv/libyuv/ | d470 | not checked
- [ ] live555 | http://www.live555.com/liveMedia/public/ | 2019.08.28 | not checked
- [ ] llvm_stage1 | https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-15.0.1.tar.gz |   version @_ver | refs/tags/llvmorg-15.0.1
- [ ] lmdb | https://git.openldap.org/openldap/openldap/-/tags | 0.9.29 | not checked
- [ ] lynis | https://github.com/CISOfy/lynis/archive/<!DOCTYPE html> <html lang=.tar.gz | 3.0.1 | <!DOCTYPE html> <html lang=
- [ ] mailutils | https://ftpmirror.gnu.org/mailutils//mailutils-3.9.tar.xz | 3.13 | 3.9
- [ ] mate_calc | https://pub.mate-desktop.org/releases/ | 1.21 | not checked
- [ ] mate_common | https://pub.mate-desktop.org/releases/ | 1.20 | not checked
- [ ] mate_desktop | https://pub.mate-desktop.org/releases/ | 1.20-0 | not checked
- [ ] memcached | https://memcached.org/downloads | 1.5.16 | not checked
- [ ] mercurial | https://www.mercurial-scm.org/release |   version @_ver | not checked
- [ ] mesa | https://mesa.freedesktop.org/archive/ |   version @_ver | not checked
- [x] meson* | https://github.com/mesonbuild/meson/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] metasploit | https://github.com/rapid7/metasploit-framework/archive/<!DOCTYPE html> <html lang=.tar.gz | 6.0.9 | <!DOCTYPE html> <html lang=
- [ ] micro | https://github.com/zyedidia/micro/archive/refs/tags/v2.0.11.tar.gz | 1.4.1 | refs/tags/v2.0.11
- [ ] miniupnpc | https://github.com/miniupnp/miniupnp/archive/<!DOCTYPE html> <html lang=.tar.gz | 2.1 | <!DOCTYPE html> <html lang=
- [ ] mold* | https://github.com/rui314/mold/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.5.0 | <!DOCTYPE html> <html lang=
- [ ] mpv | https://github.com/mpv-player/mpv/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] mutter | https://download.gnome.org/core/ | 41.0 | not checked
- [ ] nano | https://www.nano-editor.org/dist | 6.1 | not checked
- [ ] nautilus | https://gitlab.gnome.org/GNOME/nautilus/-/tags |   version @_ver | not checked
- [ ] networkmanager | https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/tags |   version @_ver | not checked
- [ ] nftables | https://netfilter.org/projects/nftables/files/ | 0.9.6-1 | not checked
- [ ] oci_cli | https://github.com/oracle/oci-cli/archive//<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] openal | https://github.com/kcat/openal-soft/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.20.1 | <!DOCTYPE html> <html lang=
- [ ] openhab | https://www.openhab.org/download/ |   version @_ver | not checked
- [ ] openmp* | https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-15.0.1.tar.gz | 13.0.0 | refs/tags/llvmorg-15.0.1
- [ ] papirus_icon_theme | https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/<!DOCTYPE html> <html lang=.tar.gz | 20200801 | <!DOCTYPE html> <html lang=
- [ ] pdm | https://github.com/pdm-project/pdm/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.13.5 | <!DOCTYPE html> <html lang=
- [ ] peazip | https://github.com/peazip/PeaZip/archive//refs/tags/8.8.0.tar.gz | 8.4.0 | refs/tags/8.8.0
- [ ] php | https://php.net/distributions | 5.6.40-8.1.10 | not checked
- [ ] pipewire | https://gitlab.freedesktop.org/pipewire/pipewire/-/tags |   version @_ver | not checked
- [ ] pkgsrc | https://github.com/NetBSD/pkgsrc | 2021Q1 | not checked
- [ ] platformsh | https://github.com/platformsh/platformsh-cli/archive/<!DOCTYPE html> <html lang=.tar.gz | 3.79.7 | <!DOCTYPE html> <html lang=
- [ ] pmd | https://github.com/pmd/pmd/archive/<!DOCTYPE html> <html lang=.tar.gz | 6.28.0 | <!DOCTYPE html> <html lang=
- [ ] powershell | https://github.com/PowerShell/PowerShell/archive//refs/tags/v7.2.6.tar.gz | 7.2.1 | refs/tags/v7.2.6
- [ ] pulseaudio | https://freedesktop.org/software/pulseaudio/releases |   version "#{@_ver}-2" | not checked
- [ ] pygobject | https://gitlab.gnome.org/GNOME/pygobject/tags |   version "#{@_ver}-1" | not checked
- [ ] qtbase | http://download.qt.io/official_releases/qt/ | 5.15.3 | not checked
- [ ] qtcreator | http://download.qt.io/official_releases/qt/ | 4.9.1 | not checked
- [ ] qtsvg | http://download.qt.io/official_releases/qt/ | 5.15.2 | not checked
- [ ] qttools | http://download.qt.io/official_releases/qt/ | 5.15.2 | not checked
- [ ] qtx11extras | http://download.qt.io/official_releases/qt/ | 5.15.2 | not checked
- [ ] re2 | https://github.com/google/re2/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] remmina | https://github.com/FreeRDP/Remmina/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.4.27 | <!DOCTYPE html> <html lang=
- [x] rust | https://github.com/rust-lang/rust/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] sass | https://github.com/sass/dart-sass/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.32.8 | <!DOCTYPE html> <html lang=
- [ ] sejda_console | https://github.com/torakiki/sejda/archive/<!DOCTYPE html> <html lang=.tar.gz | 3.2.46 | <!DOCTYPE html> <html lang=
- [ ] sfk | https://sourceforge.net/projects/swissfileknife/files/1-swissfileknife | 1.8.7 | not checked
- [ ] shotcut | https://github.com/mltframework/shotcut/archive/<!DOCTYPE html> <html lang=.tar.gz | 20.11.25 | <!DOCTYPE html> <html lang=
- [ ] smbclient | https://download.samba.org/pub/samba/stable | 4.16.4 | not checked
- [ ] snappy | https://github.com/google/snappy/archive/<!DOCTYPE html> <html lang=.tar.gz | 1.1.7 | <!DOCTYPE html> <html lang=
- [ ] sphinx | https://github.com/sphinx-doc/sphinx/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] stressng | http://kernel.ubuntu.com/~cking/tarballs/stress-ng |   version @_ver | not checked
- [ ] stunnel | https://www.stunnel.org/downloads.html | 5.42 | not checked
- [ ] symfony | https://github.com/symfony/cli/archive//refs/tags/v4.28.1.tar.gz | 4.28.1 | refs/tags/v4.28.1
- [ ] syncthing | https://github.com/syncthing/syncthing/archive/refs/tags/v1.21.0.tar.gz | 0.14.41 | refs/tags/v1.21.0
- [ ] torbrowser | https://dist.torproject.org/torbrowser/ |   version @_ver | not checked
- [ ] tracker3 | https://gitlab.gnome.org/GNOME/tracker/-/tags | 3.1.1 | not checked
- [ ] tracker3_miners | https://gitlab.gnome.org/GNOME/tracker-miners/-/tags | 3.1.0 | not checked
- [ ] urlwatch | https://github.com/thp/urlwatch/archive/<!DOCTYPE html> <html lang=.tar.gz |   version "#{@_ver}-2" | <!DOCTYPE html> <html lang=
- [ ] v2ray | https://github.com/v2ray/v2ray-core/archive//<!DOCTYPE html> <html lang=.tar.gz | v4.28.2 | <!DOCTYPE html> <html lang=
- [ ] vala | https://download.gnome.org/sources/vala/ | 0.53.2 | not checked
- [ ] vim | https://github.com/vim/vim/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] vim_runtime | https://github.com/vim/vim/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] vulkan_headers | https://github.com/KhronosGroup/Vulkan-Headers/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] vulkan_icd_loader | https://github.com/KhronosGroup/Vulkan-Loader/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] w3m | https://salsa.debian.org/debian/w3m/-/tags | 0.5.3-20220429 | not checked
- [ ] wayland | https://wayland.freedesktop.org/releases.html |   version @_ver.to_s | not checked
- [ ] wayland_protocols | https://wayland.freedesktop.org/releases.html | 1.26 | not checked
- [ ] webkit2gtk_4 | https://webkitgtk.org/releases/ |   version @_ver | not checked
- [ ] webkit2gtk_5 | https://webkitgtk.org/releases/ |   version @_ver | not checked
- [ ] wine | https://dl.winehq.org/wine/source | 6.5 | not checked
- [ ] wing | https://wingware.com/pub/wing-personal/ | 7.2.1.0 | not checked
- [ ] wireshark | https://github.com/wireshark/wireshark/tags | 3.6.0 | not checked
- [ ] wishlist | https://github.com/charmbracelet/wishlist/archive/refs/tags/v0.7.0.tar.gz | 0.5.0 | refs/tags/v0.7.0
- [ ] wpebackend_fdo | https://github.com/Igalia/WPEBackend-fdo/archive//<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] xxd_standalone | https://github.com/vim/vim/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [x] youtube_dl | https://github.com/rg3/youtube-dl/archive/<!DOCTYPE html> <html lang=.tar.gz |   version @_ver | <!DOCTYPE html> <html lang=
- [ ] zoneinfo | https://data.iana.org/time-zones/releases/ | 2021a | not checked

**Comment by satmandu** [comment]
libcurl is up to date. adwaita, vulkan and webkit2gtk are (or are going to be) in the gnome43 PR.

**Comment by satmandu** [comment]
anything gnome is being updated and rebuilt in that PR...

**Comment by satmandu** [comment]
rust is also up to date.

**Comment by uberhacker** [comment]
I'm still working on this list.  It's just a rough draft currently.

**Comment by uberhacker** [comment]
See how your `@_ver` stuff has ruined my script? LoL

**Comment by Zopolis4** [comment]
I'll do some GNU tools.

**Comment by cobalt2727** [comment]
While you're looking at this, would you be able to investigate something for me? Trying to build and run [vkcube](https://github.com/krh/vkcube) for some graphics tests, but I keep getting the following:
```bash
The Meson build system
Version: 0.63.1
Source dir: /usr/local/mystuff/vkcube
Build dir: /usr/local/mystuff/vkcube/build
Build type: native build
Project name: vkcube
Project version: 0.1
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.gold 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency libdrm found: YES 2.4.112
Run-time dependency gbm found: YES 21.3.9
Run-time dependency libpng found: YES 1.6.37
Run-time dependency wayland-client found: YES 1.21.0
Run-time dependency xcb found: YES 1.14
Run-time dependency vulkan found: YES 1.3.224
Library m found: YES
Has header "vulkan/vulkan_intel.h" : NO 
Program glslc found: NO
Program cp found: YES (/bin/cp)
Build targets in project: 1

Found ninja-1.11.1 at /usr/local/bin/ninja
Cleaning... 0 files.
[7/7] Linking target vkcube
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2 physical devices
vendor id 8086, device name Intel(R) HD Graphics 400 (BSW)
Vulkan not supported on given Wayland surface
```

To the best of my understanding, that `vulkan_intel.h` file _should_ be coming from the [vulkan_icd_loader](https://github.com/KhronosGroup/Vulkan-Loader) package, but I already have that installed and it's just... not seeing it, I guess. Is there anything I'm missing?

**Comment by Zopolis4** [comment]
Try `crew files vulkan_icd_loader`

**Comment by cobalt2727** [comment]
```bash
chronos@localhost /usr/local/mystuff/vkcube/build $ crew files vulkan_icd_loader 
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
vulkan_icd_loader: Vulkan Installable Client Driver ICD Loader
/usr/local/lib64/libvulkan.so
/usr/local/lib64/libvulkan.so.1
/usr/local/lib64/libvulkan.so.1.3.224
/usr/local/lib64/pkgconfig/vulkan.pc
Total found: 4
Disk usage: 1.83 MB
```

**Comment by satmandu** [comment]
Anyways the vulkan headers are in the `vulkan_headers` package.

**Comment by cobalt2727** [comment]
`youtube_dl` is [up to date](https://github.com/ytdl-org/youtube-dl/releases)

**Comment by donaldysmith** [comment]
It is great for the effort.

I tried firefox, edge, opera. All is good.

But I couldn't install torbrowser. It is most important for I want to pass the company firewall.

**Comment by uberhacker** [comment]
@donaldysmith: Check out #7594.
