### ISSUE TITLE
Glibc failed to install

### ISSUE THREAD

**Issue by soitchu** [chromebrew/chromebrew#7445]
## Description

I get this error when trying to install glibc:
```Performing post-install for glibc...
Package glibc version is 2.33.
System glibc version is 2.33.
Creating symlinks to system glibc version to prevent breakage.
Paring locales to a minimal set.
/usr/local/lib/crew/lib/package.rb:266:in `system': Command failed with exit 123: bash
glibc failed to install: `CREW_DISABLE_ENV_OPTIONS="1" bash -c localedef --list-archive | grep -v -i -e ^en -e ^cs -e ^de -e ^es -e ^fa -e ^fe -e ^it -e ^ja -e ^ru -e ^tr -e ^zh -e ^C| xargs localedef --delete-from-archive` exited with 123
```

## Versions and system information

***
- Architecture: `aarch64` (`aarch64`)
- Kernel version: `5.10.131-19115-g2e2fb0ed324d`

- Chromebrew version: `1.25.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 64c9dfe `neovim -> 0.8.0 (#7444) (5 hours ago)`

- OS variant: `Chrome OS`
- OS version: `kukui-release/R105-14989.107.0`
- OS channel: `stable-channel`
***

**Comment by satmandu** [comment]
Hmm. Maybe we can just add a `|| true` to the end of that postinstall line...

**Comment by satmandu** [comment]
Can you try this and let us know if it works?
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_233_fix  CREW_TESTING=1 crew update ; crew reinstall glibc
```

**Comment by soitchu** [comment]
That worked! Thank you!
