### ISSUE TITLE
Can't install xorg_intel_driver

### ISSUE THREAD

**Issue by cobalt2727** [chromebrew/chromebrew#7458]
## Description

If you executed a specific command:
```shell
crew install xorg_intel_driver
```

Output:
I don't have the full log on me at the moment because I can't figure out how to SSH into my Chromebook from my regular laptop, but here's the most concerning parts of the output copied from a conversation I had about it:
```ruby
libtool: warning: remember to run 'libtool --finish /usr/local/lib64'
```
```css
configure.ac:44: warning: The macro `AC_PROG_CC_C99` is obsolete.
configure.ac:44: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
aclocal.m4:1831: XORG_COMPILER_BRAND is expanded from...
aclocal.m4:1950: XORG_COMPILER_FLAGS is expanded from...
aclocal.m4:2122: XORG_DEFAULT_OPTIONS is expanded from...
configure.ac:44: the top level
configure.ac:62: warning: The macro `AC_PROG_LIBTOOL` is obsolete.
configure.ac:62: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:62: the top level
configure.ac:218: warning: The macro `AC_TRY_LINK` is obsolete.
configure.ac:218: You should run autoupdate.
```

## Versions and system information

***
also don't have on hand right now, but I can edit this later if needed
I'm on the latest version of everything, ran `crew update && crew upgrade` last night

**Comment by satmandu** [comment]
You shouldn't need xorg-intel-driver for the most part. mesa tends to handle that.

Having said that, I'm rebuilding this right now.

This driver has undergone code rot and no longer builds against libxvmc.

**Comment by cobalt2727** [comment]
Sounds good!
