### ISSUE TITLE
Missing lib codelite & cobc

### ISSUE THREAD

**Issue by iz0eyj** [chromebrew/chromebrew#7501]
Hi,
on FydeOS 15 (ChromiumOS 102) I cannot start CodeLite & cobc:

CodeLite:
 
- Alot of outdated library , installed version 3.2, the package looking for 3.0 (I think it can be fixed using symlinks).
- libwx_gtk3u_webview-3.0.so.0 is missing in any version, so it cannot be fixed.

cobc:

- The package looking for  libdb-6.2.so, installed version 5.3.
  Apparently it can be fixed with a symlink, but will it work?

Regards, Federico

**Comment by satmandu** [comment]
Linux distributions tend not to distribute newer versions of `libdb` due to licensing issues, thanks to Oracle. See: https://en.wikipedia.org/wiki/Berkeley_DB

**Comment by satmandu** [comment]
Have more recently rebuilt packages fixed this issue for you? If not, feel free to reopen this...
