### ISSUE TITLE
installing curl through crew messes with crouton

### ISSUE THREAD

**Issue by Icyfiremario** [chromebrew/chromebrew#7551]
whenever I try to launch crouton it gives me an error about a curl library file not being found I made an issue on the crouton GitHub and the developer said that crew might be the issue but ideally it wouldn't interfere. Personally, I think because I installed curl manually it messed with the library file but I'm not too sure I wanted to mention this just in case it could cause more problems

**Comment by satmandu** [comment]
Chromebrew's curl in `/usr/local/bin` isn't a static binary, so it will always depend upon libraries in /usr/local/lib[64].

If you want to use another curl binary, either the one from ChromeOS in `/usr/bin` or one from inside crouton, you will have to run that version of curl setting LD_LIBRARY_PATH appropriately for those binaries.

e.g. `LD_LIBRARY_PATH=/usr/lib64:/lib64 /usr/bin/curl`

**Comment by Icyfiremario** [comment]
> Chromebrew's curl in `/usr/local/bin` isn't a static binary, so it will always depend upon libraries in /usr/local/lib[64].
> 
> If you want to use another curl binary, either the one from ChromeOS in `/usr/bin` or one from inside crouton, you will have to run that version of curl setting LD_LIBRARY_PATH appropriately for those binaries.
> 
> e.g. `LD_LIBRARY_PATH=/usr/lib64:/lib64 /usr/bin/curl`

sorry, I should have pasted the error but that is where the error is taking place.
curl: error while loading shared libraries: /usr/local/lib64/libunistring.so.2: cannot open shared object file: No such file or directory

**Comment by satmandu** [comment]
Try a reinstall of Chromebrew to try to fix the issue...

**Comment by Icyfiremario** [comment]
> Try a reinstall of Chromebrew to try to fix the issue...

ok, if I'm still having issues I'll let you know

**Comment by satmandu** [comment]
Please reopen if this is still an issue...
