### ISSUE TITLE
glibc: ldd executable broken

### ISSUE THREAD

**Issue by saltedcoffii** [chromebrew/chromebrew#7554]
## Description:
The `ldd` shebang points to an executable that doesn't always exist,

## Output:
```
$ ldd
bash: /usr/local/bin/ldd: /usr/local/bin/bash: bad interpreter: No such file or directory

$ head -n 1 $(command -v ldd)
#! /usr/local/bin/bash
```

## Possible solutions:
- Change the shebang on ldd from `#! /usr/local/bin/bash` to `#! /usr/bin/env bash` (in the glibc binaries)
- Add fix in `def self.patch` and rebuild glibc
- make `bash` a dependency of `glibc` (therefore expanding core)

**Comment by uberhacker** [comment]
Yes, we should not be setting `#!/usr/local/bin/bash`.  That should be `#!/bin/bash` instead.  Setting to `#!/usr/bin/env bash` could be problematic with newer versions of bash.

**Comment by saltedcoffii** [comment]
why is `#!/usr/bin/env bash` problematic?

**Comment by satmandu** [comment]
This was fixed in the last update to glibc for i686.

Rebuilds of glibc for armv7l and x86_64 without the bash package installed will fix this.

(The current containers don't have the bash package installed, so rebuilding on these containers should be fine.)
