### ISSUE TITLE
Removal of libc.so.6 library on install

### ISSUE THREAD

**Issue by NBT22** [chromebrew/chromebrew#7562]
## Description
When I try to install Chromebrew on my Chromebook (not in Crostini, but on the Chromebook directly), it seemingly deletes the libc.so.6 library. I am on stable (106.0.5249.112), and am wondering if this is something that I am doing wrong?

If you executed a specific command:
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```
Welcome to Chromebrew!
Please enter the developer mode password
Password: 


Doing initial setup for install in /usr/local.
This may take a while if there are preexisting files in /usr/local...

Resetting ownership of /usr/local/bin
Resetting ownership of /usr/local/etc
Resetting ownership of /usr/local/include
Resetting ownership of /usr/local/lib
Resetting ownership of /usr/local/lib64
Resetting ownership of /usr/local/share
Resetting ownership of /usr/local/tmp

Downloading information for Bootstrap packages...
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
--  --      0     0     9     0     0 --:--:-- --:--:-- --:--:--     0      

Downloading Bootstrap packages...

Downloading zstd...
######################################################################## 100.0%
Verifying zstd...
zstd-1.5.2-1-chromeos-x86_64.tar.xz: OK
Extracting zstd ...
Installing zstd ...
Updating version number of zstd in device.json...
Downloading pixz...
######################################################################## 100.0%
Verifying pixz...
pixz-1.0.7-f1b1b5f-chromeos-x86_64.tar.xz: OK
Extracting pixz ...
Installing pixz ...
Updating version number of pixz in device.json...
Downloading ca_certificates...
######################################################################## 100.0%
Verifying ca_certificates...
ca_certificates-20210119-2-chromeos-x86_64.tar.xz: OK
Extracting ca_certificates ...
Installing ca_certificates ...
Updating version number of ca_certificates in device.json...
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-3.1.3-9fc7df7-chromeos-x86_64.tar.xz: OK
Extracting ruby ...
Installing ruby ...
Updating version number of ruby in device.json...
Downloading rsync...
######################################################################## 100.0%
Verifying rsync...
rsync-3.2.5-chromeos-x86_64.tar.xz: OK
Extracting rsync ...
Installing rsync ...
Updating version number of rsync in device.json...
Downloading openssl...
######################################################################## 100.0%
Verifying openssl...
openssl-1.1.1q-2-chromeos-x86_64.tar.xz: OK
Extracting openssl ...
Installing openssl ...
Adding new information on openssl to device.json...
Downloading xxhash...
######################################################################## 100.0%
Verifying xxhash...
xxhash-0.8.1-chromeos-x86_64.tar.xz: OK
Extracting xxhash ...
Installing xxhash ...
Adding new information on xxhash to device.json...
Downloading lz4...
######################################################################## 100.0%
Verifying lz4...
lz4-1.9.4-chromeos-x86_64.tar.zst: OK
Extracting lz4 ...
Installing lz4 ...
Adding new information on lz4 to device.json...
Downloading popt...
######################################################################## 100.0%
Verifying popt...
popt-1.18-7182e46-1-chromeos-x86_64.tar.xz: OK
Extracting popt ...
Installing popt ...
Adding new information on popt to device.json...

Creating symlink to 'crew' in /usr/local/bin/

'/usr/local/bin/crew' -> '../lib/crew/bin/crew'

Setup and synchronize local package repo...

 #=#=-#   #                                                                   
sh: 1: python3: not found
sh: 1: python3: not found
Installing core Chromebrew packages...

core: Core Chromebrew Packages.
https://github.com/chromebrew/chromebrew
Version: 1.7
License: GPL-3+
Performing pre-flight checks...
The following packages also need to be installed: 
glibc brotli bz2 c_ares crew_profile_base expat gmp isl libssp mpfr mpc zlibpkg musl_zstd gcc ncurses readline gdbm libdb libffi mpdecimal libedit sqlite xzutils python3 libcap_ng linux_pam pcre2 libeconf icu4c libxml2 py3_libxml2 libgpgerror libgcrypt xmlcatmgr docbook_xml412 docbook_xml42 docbook_xml43 docbook_xml44 docbook_xml45 docbook_xml50 docbook_xml51 docbook_xsl_nons docbook_xml docbook_xsl libxslt gperf eudev util_linux e2fsprogs attr acl libarchive krb5 libcyrussasl libunistring libidn2 jansson jemalloc libnghttp2 libpsl libssh openldap libcurl libmicrohttpd elfutils filecmd libsigsegv m4 flex openmp gettext git libtasn1 libunbound nettle p11kit trousers gnutls uchardet groff less libmetalink libpipeline libseccomp libtirpc libyaml lzip mandb manpages mawk libpng pcre slang most patchelf perl py3_pyparsing py3_packaging py3_setuptools py3_wheel py3_pip rtmpdump unzip zip
Do you agree? [Y/n] Proceeding...
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Precompiled binary available, downloading...
Glibc archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
rsync is not working. Please (re)install it with 'crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync'
brotli: Brotli compression format
Precompiled binary available, downloading...
Brotli archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
tar: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
/usr/local/bin/crew:876:in `system': Command failed with exit 127: tar (RuntimeError)
        from /usr/local/bin/crew:876:in `block in unpack'
        from /usr/local/bin/crew:839:in `chdir'
        from /usr/local/bin/crew:839:in `unpack'
        from /usr/local/bin/crew:1398:in `install'
        from /usr/local/bin/crew:1378:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1375:in `each'
        from /usr/local/bin/crew:1375:in `resolve_dependencies'
        from /usr/local/bin/crew:1314:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1752:in `block in install_command'
        from /usr/local/bin/crew:1747:in `each'
        from /usr/local/bin/crew:1747:in `install_command'
        from /usr/local/bin/crew:1867:in `<main>'
```

## Versions and system information
***
crew sysinfo:
/usr/bin/coreutils: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
cat /etc/lsb-release:
/usr/bin/coreutils: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
cat /etc/lsb-release (after a powerwash):
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=9040939
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9496CDE8-85E6-4118-960F-E26DC0C69FD6}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9496CDE8-85E6-4118-960F-E26DC0C69FD6}
CHROMEOS_RELEASE_BOARD=grunt-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=98
CHROMEOS_RELEASE_BUILDER_PATH=grunt-release/R106-15054.98.0
CHROMEOS_RELEASE_BUILD_NUMBER=15054
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=106
CHROMEOS_RELEASE_DESCRIPTION=15054.98.0 (Official Build) stable-channel grunt 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15054.98.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15054.98.0
***

## Additional information
All you have to do to replicate this (on my machine, and my friend's (both of us have a model HP 11A G8 Chromebook)) is this:
- [ ] Put your Chromebook in developer mode.
- [ ] Open up shell, using whatever method you prefer.
- [ ] Run the command `curl -Ls git.io/vddgY | bash`.
- [ ] Wait for it to throw an error.
- [ ] The library is now gone!

**Comment by uberhacker** [comment]
@NBT22: Thank you for the detailed feedback.  This is a known issue for AMD processors and the grunt board.  cc: @satmandu

**Comment by memehouse** [comment]
Hi, are you guys working to fix this? I have a Grunt board so this kinda upsets me, thank you.

**Comment by satmandu** [comment]
It's coming up on the list of things to look at.

You could try this and see if the install continues: `ln -s /lib64/libc.so.6 /usr/local/lib64/libc.so.6`

Otherwise, it is going to be a bit of a slog. We're getting segfaults on running the software we have built for the rest of the `x86_64` machines on the AMD machines...

**Comment by NBT22** [comment]
Ok, so I have some new information. I am able to get through most of the process, and even get rsync to run (only once, though...) but when I get to the step where it is installing the core Chromebrew packages (`yes | crew install core`), that is when it dies, as shown in the original issue.

I did try using the command you recommended, and when I run it after the installation of core packages, it just throws the `/usr/bin/coreutils: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short` error. If I run it sooner, it does seem to help me run rsync though?

A very interesting behavior that I noticed with rsync is that it will usually run correctly, a single time, in a virtual terminal that has just been reset. If too many commands have been run in that terminal, then that seems to trigger a segmentation fault. I have only been able to get it to run in the crosh shell once, and that was right after running that command that you recommended, and after having manually run all of install.sh up to the installation of the core packages. 

If you have any thoughts, please let me know, and I will continue experimenting with this!

**Comment by satmandu** [comment]
We might have to create a version of the glibc package specifically for amd64 machines which includes the symlinks, and get that installed before anything else.

Could you give me the output of `cat /proc/cpuinfo` on your machine please?

**Comment by NBT22** [comment]
After another powerwash, `cat /proc/cpuinfo` outputs
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 112
model name      : AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G
stepping        : 0
microcode       : 0x6006705
cpu MHz         : 1852.054
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips        : 3193.90
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro acc_power [13]

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 112
model name      : AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G
stepping        : 0
microcode       : 0x6006705
cpu MHz         : 1850.674
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 17
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips        : 3193.90
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro acc_power [13]
```

**Comment by satmandu** [comment]
Great! So it looks like a check for AMD could just use this:
```
if ARCH == 'x86_64' && `grep -c 'AuthenticAMD' /proc/cpuinfo`.to_i.positive?
```

**Comment by satmandu** [comment]
I've added some code to identify AMD machines into https://github.com/chromebrew/chromebrew/pull/7585 for use in further debugging this issue...

**Comment by gangel478** [comment]
do we have an update if this has been fixed on grunt boards?

**Comment by NBT22** [comment]
Due to life circumstances, I haven't done extensive testing, but it does seem to install, although many of the programs don't work (seg_fault)

**Comment by satmandu** [comment]
Please let us know what programs are segfaulting!

It's exciting that we are getting further...

**Comment by satmandu** [comment]
I loaded one of the binaries from a grunt image (/bin/bash) in another chromeos container, and it looks like the binaries on the grunt image are using AMD specific instructions. For instance here it is VPCOMEQD.
![image](https://user-images.githubusercontent.com/1096701/203403398-cfef53d4-6301-42c3-b2d7-a53640a90efa.png)
This is why we've been having trouble testing against the AMD hardware on Intel CPU computers... The binaries just crash.

Instructions on how to examine a binary for the illegal instructions:
https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu/40223712#40223712

Can any of you run /bin/bash inside this docker image?
```
#!/bin/bash
docker pull satmandu/crewbase:aleena-x86_64.m107
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --platform linux/amd64 --rm -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-x86_64 -it satmandu/crewbase:aleena-x86_64.m107 /bin/sh -i
```
(This will obviously work better on an AMD non-ChromeOS linux machine... but definitely not on an Intel machine.)

**Comment by NBT22** [comment]
Sorry that I have been silent for a while, I've just been really busy, but yes, I can look into testing that. Unfortunately, the only AMD device that I have is my chromebook, but I should be able to look into that on my chromebook soon.

**Comment by satmandu** [comment]
This should be resolved?
