### ISSUE TITLE
sommelier made acer 720p chromebook flex power off disabled

### ISSUE THREAD

**Issue by donaldysmith** [chromebrew/chromebrew#7591]
The developer mode was enabled.

I powerwashed the system several times. 

After run

crew install gvim

I pushed the power button, the system will black out, but power button again it will not response.

Either hold the power button several seconds or Fresh+power, the system will back.

It is good to install non GUI programms.

So I guess it was the sommelier. Something relate to the driver for Fresh+Power is about hard reset for drivers.

Thanks a lot. Chromebrew is really a great suit.

**Comment by satmandu** [comment]
I see something similar on a Samsung Chromebook, where shutdown or restart through the gui somehow breaks. This is somehow a driver issue, I think.

Do you have this issue if you uninstall sommelier?

**Comment by donaldysmith** [comment]
> I see something similar on a Samsung Chromebook, where shutdown or restart through the gui somehow breaks. This is somehow a driver issue, I think.
> 
> Do you have this issue if you uninstall sommelier?

I powerwashed several times. I know it was related to GUI programs, so it is related to sommelier. I didn't try to uninstall sommelier. I can try next time if I want to powerwash the system. Just it is a little annoying to powerwash again and again.

**Comment by donaldysmith** [comment]
> I see something similar on a Samsung Chromebook, where shutdown or restart through the gui somehow breaks. This is somehow a driver issue, I think.
> 
> Do you have this issue if you uninstall sommelier?

I tried install gvim, torbrowser, it got the problem.

Then I just powerwashed the chromebook and reinstall chromebrew and 
crew install sommelier

It produced the problem. Then I 
crew remove sommelier

It persist there. So I think it is relate to the driver or X(wayland?), something sommelier depended.

There is no
crew autoremove
to test. 

Where can I find crew log file to remove packages? I googled and couldn't find a clue.

Thanks a lot.

**Comment by satmandu** [comment]
The database of installed packages is` /usr/local/etc/crew/meta/device.json`. You can use `jq` to interact with that json file.

e.g.`jq --arg key gawk -e '.installed_packages[] | select(.name == $key )' /usr/local/etc/crew/device.json` will tell you if `gawk` is installed.

**Comment by donaldysmith** [comment]
> The database of installed packages is `/usr/local/etc/crew/device.json`. You can use `jq` to interact with that json file.
> 
> e.g.`jq --arg key gawk -e '.installed_packages[] | select(.name == $key )' /usr/local/etc/crew/device.json` will tell you if `gawk` is installed.

Thanks a lot. I will try for next time powerwash
