### ISSUE TITLE
iwconfig: error while loading shared libraries: libiw.so.29: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Uriasej** [chromebrew/chromebrew#7592]
## Description
I'm trying to run Clu3bot/owt which I have modified to utilize ifconfig and iwconfig instead of airmon-ng so that way the script will work on my chromebook, but I'm getting this error

Output:

```
iwconfig: error while loading shared libraries: libiw.so.29: cannot open shared object file: No such file or directory
```
## Versions and system information

***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `4.19.255-13653-ga5ef616743fe`

- Chromebrew version: `1.26.2`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 28be436 `Fix gem install command line (#7506) (3 weeks ago)`

- OS variant: `Chrome OS`
- OS version: `hatch-release/R106-15054.114.0`
- OS channel: `stable-channel`
***

**Comment by satmandu** [comment]
Where did you get your `iwconfig`? It was built against a package with `libiw.so.29`, which isn't a part of Chromebrew...

**Comment by satmandu** [comment]
Feel free to reopen this if you feel like giving us more information about your issue...
