### ISSUE TITLE
fpc (free pascal compiler) with error, possibly the file system permission problem

### ISSUE THREAD

**Issue by donaldysmith** [chromebrew/chromebrew#7593]
I have a Ace C720p with chromebook flex developer mode enabled, inside developer mode installed chromebrew, then

crew install fpc

smoothly.  When I run "fpc", the message is

Error: ppcx64 can't be executed, error message: Failed to execute "ppcx64", error code: 127

I ever tried g++ with "HelloWorld" code. The compiled output "a.out" is not executable. I have to remount the directory

sudo mount -o remount,rw -o exec /home/chronos/user 

So I can run "a.out". 

So I guess whether the file system causes the fpc problem?

Any ideas? Thanks a lot.

**Comment by uberhacker** [comment]
Try this:
```
ln -sf /usr/local/lib/fpc/3.2.2/ppcx64 /usr/local/bin/fpc
```

**Comment by donaldysmith** [comment]
Thanks a lot. I got link error

chronos@localhost ~/Downloads $ fpc HelloWorld.pas
/usr/local/bin/ld: error: link30975.res:21:8: syntax error, unexpected STRING
/usr/local/bin/ld: fatal error: unable to parse script file link30975.res
HelloWorld.pas(6,1) Error: Error while linking
HelloWorld.pas(6,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted

**Comment by donaldysmith** [comment]
> Try this:
> 
> ```
> ln -sf /usr/local/lib/fpc/3.2.2/ppcx64 /usr/local/bin/fpc
> ```

Thanks a lot.
chronos@localhost ~/Downloads $ fpc HelloWorld.pas
/usr/local/bin/ld: error: link30975.res:21:8: syntax error, unexpected STRING
/usr/local/bin/ld: fatal error: unable to parse script file link30975.res
HelloWorld.pas(6,1) Error: Error while linking
HelloWorld.pas(6,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted

**Comment by satmandu** [comment]
`ppcx64` isn't by chance a power-pc binary, is it?

**Comment by donaldysmith** [comment]
> `ppcx64` isn't by chance a power-pc binary, is it?

It looks like ppc, but it is x86-64. I don't know the detail structure for I just use the lazarus IDE mostly.

chronos@localhost /usr/local/lib/fpc/3.2.2 $ file ppcx64
ppcx64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 2.4.0, stripped

**Comment by Zopolis4** [comment]
What directory are you running this in? It looks like you're running it in `~/Downloads`, which iirc is not executable on ChromeOS. `/usr/local` is executable, maybe try that?
