### ISSUE TITLE
new thing for crew update?

### ISSUE THREAD

**Issue by donaldysmith** [chromebrew/chromebrew#7603]
I couldn't remember the same message before. I think it is silent without those fatal things.

chronos@localhost ~/Downloads $ crew update
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Package lists, crew, and library updated.
Checking for package updates...
Your software is up to date.

## Description

If you executed a specific command:
```shell
# your command here
```

Output:
```
# output of your command here
```

## Versions and system information

***
***

**Comment by satmandu** [comment]
We need more information. Is this a recent install?

Please do a reinstall and follow the reporting steps in the issue template.

**Comment by satmandu** [comment]
Does a fresh install of chromebrew after the powerwash work?

**Comment by donaldysmith** [comment]
> Does a fresh install of chromebrew after the powerwash work?

No, the same result.

**Comment by satmandu** [comment]
@uberhacker @supechicken Do we need an install function to create a build log by default?

**Comment by donaldysmith** [comment]
> Does a fresh install of chromebrew after the powerwash work?

I just reinstalled the chromebrew. It was good now.

Thanks a lot.

**Comment by donaldysmith** [comment]
> Does a fresh install of chromebrew after the powerwash work?

I think the "crew update" fixed. But I realized there was always some "man" or "mandb" problem. 

I have Acer C720p chromebook flex
chronos@localhost ~ $ uname -a
Linux localhost 5.10.142-19740-g3a142da07016 #1 SMP PREEMPT Wed Oct 26 21:23:31 PDT 2022 x86_64 Intel(R) Celeron(R) 2957U @ 1.40GHz GenuineIntel GNU/Linux

During installing chromebrew, the message of  "man" part is
mandb: warning: $MANPATH set, ignoring /usr/local/etc/man_db.conf
Processing manual pages under /usr/local/share/man...
Updating index cache for path `/usr/local/share/man/man1'. Wait...mandb: warning: /usr/local/share/man/man1/lastb.1.gz: whatis parse for lastb(1) failed
mandb: iconv_open ("UTF-8//IGNORE", "ISO-8859-1"): Invalid argument
mandb: warning: /usr/local/share/man/man1/mmroff.1.gz: whatis parse for mmroff(1) failed
mandb: iconv_open ("UTF-8//IGNORE", "ISO-8859-1"): Invalid argument
mandb: warning: /usr/local/share/man/man1/grolbp.1.gz: whatis parse for grolbp(1) failed
Updating index cache for path `/usr/local/share/man/man3'. Wait...mandb: warning: /usr/local/share/man/man3/pcre2demo.3.gz: whatis parse for pcre2demo(3) failed
mandb: warning: /usr/local/share/man/man3/uuid_generate_random.3.gz: whatis parse for uuid_generate_random(3) failed
mandb: warning: /usr/local/share/man/man3/uuid_generate_time.3.gz: whatis parse for uuid_generate_time(3) failed
mandb: warning: /usr/local/share/man/man3/uuid_generate_time_safe.3.gz: whatis parse for uuid_generate_time_safe(3) failed
mandb: warning: /usr/local/share/man/man3/pcredemo.3.gz: whatis parse for pcredemo(3) failed
Updating index cache for path `/usr/local/share/man/man7'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "ISO-8859-1"): Invalid argument
mandb: warning: /usr/local/share/man/man7/groff_mmse.7.gz: whatis parse for groff_mmse(7) failed
Updating index cache for path `/usr/local/share/man/man8'. Wait...mandb: warning: /usr/local/share/man/man8/swapoff.8.gz: whatis parse for swapoff(8) failed
mandb: warning: /usr/local/share/man/man8/saslauthd.8.gz: whatis parse for saslauthd(8) failed
Updating index cache for path `/usr/local/share/man/man2'. Wait...done.
Processing manual pages under /usr/local/share/man/cat5...
Processing manual pages under /usr/local/share/man/it...
Updating index cache for path `/usr/local/share/man/it/man8'. Wait...done.
Processing manual pages under /usr/local/share/man/cat1...
Processing manual pages under /usr/local/share/man/cat7...
Processing manual pages under /usr/local/share/man/cat8...
11 man subdirectories contained newer manual pages.
8353 manual pages were added.

So next step, I test

chronos@localhost ~ $ man printf
man: can't execute /usr/bin/less: No such file or directory
man: command exited with status 255: sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page printf(3) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page printf(3) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=printf(3) /usr/bin/less
chronos@localhost ~ $ which less
/usr/local/bin/less

The path of less was not set right for man? 

Thanks a lot.

**Comment by donaldysmith** [comment]
I couldn't find "clang". Was I confused?

chronos@localhost ~ $ crew install clang
Package clang not found. 😞
chronos@localhost ~ $ crew list available | grep clang
chronos@localhost ~ $
