### ISSUE TITLE
`crew sysinfo` markup not rendering in bash

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7605]
```
$ crew sysinfo
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Kernel version: `5.10.0-18-amd64`

- Chromebrew version: `1.28.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ba0beb9 `Fix `crew sysinfo`, add more info (#7604) (6 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `nocturne-release/R90-13816.82.0`
- OS channel: `stable-channel`

</details>
```

**Comment by satmandu** [comment]
This was intentional so that people using the issue template can copy and paste from `crew sysinfo` right into the GitHub issue.

Though an alternative might be to figure out a way to open a browser to populate the issue fields automatically from `crew sysinfo` or another `crew` command.

**Comment by uberhacker** [comment]
> This was intentional so that people using the issue template can copy and paste from `crew sysinfo` right into the GitHub issue.
> 
> Though an alternative might be to figure out a way to open a browser to populate the issue fields automatically from `crew sysinfo` or another `crew` command.

It looks like trash in the terminal and should be stripped when running the command.

**Comment by satmandu** [comment]
@supechicken Ideas?

**Comment by uberhacker** [comment]
Would a `-v` switch work?

**Comment by satmandu** [comment]
That would work, especially if the GitHub issue template suggested using such a flag.

**Comment by satmandu** [comment]
Also, if you really wanted to, you could install `rich-cli`with pip3 or use some gem to render markdown in the cli and have the output go through that.
e.g.
![image](https://user-images.githubusercontent.com/1096701/200648215-f76940d5-725f-4cea-a56c-c1aea1a5966e.png)

**Comment by satmandu** [comment]
ok I got this worked out in https://github.com/chromebrew/chromebrew/pull/7585
```
chronos@rpi4b-armv7l ~ $ crew sysinfo
- Architecture: armv8l (armv7l)
- Processor vendor: ARM
- User space: 32-bit
- Chromebrew Kernel version: 4.14
- Chromebrew Running in Container: true

- Chromebrew version: 1.28.1
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib

- Last update in local repository: be04863 refactor markdown code (2 minutes ago)

- OS variant: Chrome OS
- OS version: veyron_fievel-release/R91-13904.55.0
- OS channel: stable-channel
chronos@rpi4b-armv7l ~ $ crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `armv8l` (`armv7l`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `4.14`
- Chromebrew Running in Container: `true`

- Chromebrew version: `1.28.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: be04863 `refactor markdown code (2 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `veyron_fievel-release/R91-13904.55.0`
- OS channel: `stable-channel`

</details>
chronos@rpi4b-armv7l ~ $
```

**Comment by uberhacker** [comment]
Nice!
