### ISSUE TITLE
Can't install linuxheaders

### ISSUE THREAD

**Issue by Uriasej** [chromebrew/chromebrew#7620]
**Describe the bug**

**To Reproduce**

1. I executed this command:

      ```shell
      yes | crew install linuxheaders
      ```

      Output:

      ```
      /usr/local/lib/crew/lib/package.rb:279:in `system': Command failed with exit 2: bash
      S="1" bash -c PATH=/usr/local/tmp/crew/linuxheaders.20221111023934.dir/crew_bin:$PATH make defconfig` exited with 2
      ```

**Expected behavior**
Install linuxheaders

**Screenshots**
n/a

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.28.2`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 538d786 `revert package.rb set_property as unnecessary (#7618) (6 hours ago)`

- OS variant: `Chrome OS`
- OS version: `hatch-release/R107-15117.87.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
I can't install buildessential either

```shell
xhost +
``` returns with

```shell
xhost:  unable to open display ""
```

What I think needs to be done:

I'm confident ya'll have a solution already or are working on one, but as I am no chromebrew expert, I have no idea what needs to be done.
Thanks for your time!

**Comment by satmandu** [comment]
We don't have a package for the 4.19 kernel headers, which explains why the install fails... hmmm... it should automatically try to download and install if the binaries aren't there...
