### ISSUE TITLE
[mesa]: `iris` driver does not work on pre-Gen8 iGPU

### ISSUE THREAD

**Issue by supechicken** [chromebrew/chromebrew#7654]
The `iris` driver does not support pre-Gen8 iGPU, [see here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/283) for more info

The following error was reported when running `sommelier` on my old laptop with `mesa-22`:
```shell
$ uname -p
Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz

$ sommelier -X --glamor --force-drm-device=...
MESA: warning: Driver does not support the 0x569c PCI ID
(fall back to LLVM...)
```

Works with `mesa-amber` and `MESA_LOADER_DRIVER_OVERRIDE=i965`:
```shell
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics (ILK) (0x46)
    Version: 21.3.9
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 21.3.9 (git-acfef002a0)
OpenGL shading language version string: 1.20
```

Maybe we need to check the iGPU model also?

**Comment by supechicken** [comment]
EDIT: Also works with the `crocus` driver, which present in `mesa-22`

**Comment by satmandu** [comment]
We can update the logic. We just need a breakdown of which kernels support which, and which mesa versions support which GPUs.

Should we have a wiki entry for this?

**Comment by satmandu** [comment]
We could also use output from `glxinfo -B` to create a decision tree to see which one gives `Accelerated: yes`?

Crocus requires newer kernels though, if I recall correctly...

**Comment by satmandu** [comment]
Also, maybe we could have a check done in the postinstall which would write the appropriate driver into `~/.sommelier.env` ?

**Comment by satmandu** [comment]
Is there any good way of automatically checking the PCI ID against a whitelist for a particular card? Maybe this is better addressed to mesa upstream, suggesting a better fallback algorithm inside mesa-amber?

**Comment by supechicken** [comment]
> Is there any good way of automatically checking the PCI ID against a whitelist for a particular card? Maybe this is better addressed to mesa upstream, suggesting a better fallback algorithm inside mesa-amber?

See #7669

**Comment by Zopolis4** [comment]
Looking at the [mesa documentation](https://docs.mesa3d.org/amber.html), we shouldn't need to use the amber branch, as the drivers it removes for our use cases should be covered by `iris`, `crocus` or `i915g`.

```
After Mesa 21.3, all non-Gallium DRI drivers were removed from the Mesa source-tree. These drivers are still being maintained to some degree, but only on the amber branch, and only for critical fixes.

These drivers include:

Radeon
r200
i915
i965
Nouveau (the DRI driver for NV04-NV20)

At the same time, the OpenSWR Gallium driver was removed from the Mesa source-tree, because it was already practically speaking unmaintained and the actively maintained LLVMpipe offers much of the same functionality.

Users with Intel GPUs that were using i965 should migrate to either Iris or Crocus, depending on their GPU. These drivers generally speaking both perform better and have more features than i965 had, and due to sharing more code with the rest of the Mesa infrastructure, gets more bug fixes and features.

Similarly, users of i915 should migrate to i915g (the Gallium driver for the same hardware), as it’s still being maintained.
```

**Comment by satmandu** [comment]
Note that many newer mesa drivers have kernel requirements that aren't satisfied by older Chromebooks.
