### ISSUE TITLE
why so few packages

### ISSUE THREAD

**Issue by mjonsson1986** [chromebrew/chromebrew#7663]
e.g  crew install sox. dont work. and crew install dialog. i can take more examples

**Comment by uberhacker** [comment]
Please report all broken packages.  We welcome issues.

**Comment by mjonsson1986** [comment]
where to report packages?

**Comment by uberhacker** [comment]
You can list on this issue.   Thank you for the feedback.

**Comment by mjonsson1986** [comment]
hm let's see..
missing packages:
sox: seems not possible to compile
dialog
i cant remember more just now

**Comment by supechicken** [comment]
@mjonsson1986 We need a detailed error message in order to debug the issue

**Comment by satmandu** [comment]
Closing for lack of more helpful feedback...
