### ISSUE TITLE
gdk_base env file needs DISPLAY set before xdpyinfo usage

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#7693]
```
xdpyinfo:  unable to open display "".
```
This is due to this code in `env.d/09-gdk_base`:
```
RESOLUTION=$(xdpyinfo | awk '/dimensions:/ { print $2 }' | cut -d'x' -f1)
[[ $RESOLUTION -gt 1500 && $RESOLUTION -lt 2500 ]] && SCALE=1.5
[[ $RESOLUTION -ge 2500 && $RESOLUTION -lt 3500 ]] && SCALE=2
[[ $RESOLUTION -ge 3500 && $RESOLUTION -lt 4500 ]] && SCALE=2.5
[[ $RESOLUTION -ge 4500 && $RESOLUTION -lt 5500 ]] && SCALE=3
[[ $RESOLUTION -gt 5500 ]] && SCALE=3.5
[ -z "$DISPLAY" ] && DISPLAY=':0'
```
The `[ -z "$DISPLAY" ] && DISPLAY=':0'` line needs to be before the RESOLUTION line.

**Comment by satmandu** [comment]
Also, it might make sense to have the `GDK_BACKEND` line be thus if it is already set:
```
[ -z "$GDK_BACKEND" ] && GDK_BACKEND=x11
```

**Comment by uberhacker** [comment]
Makes sense.  If `GDK_BACKEND` is not set to `x11` then apps that require that backend will not launch.  Just an FYI.

**Comment by satmandu** [comment]
`GDK_BACKEND=wayland` also works for many apps, as that bypasses sommelier...

**Comment by satmandu** [comment]
(gtk3 & gtk4 apps should work fine with wayland.)

**Comment by uberhacker** [comment]
Does it work for foliage or torbrowser?

**Comment by satmandu** [comment]
![image](https://user-images.githubusercontent.com/1096701/204597032-9affd493-0753-41ef-b3dc-90f619ad96ee.png)
