### ISSUE TITLE
🐞 Bug:  Errors after `crew update`

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7735]
```
Package lists, crew, and library updated.
Error with py3_pip.rb: wrong number of arguments (given 2, expected 0..1)
Error with py3_setuptools.rb: wrong number of arguments (given 2, expected 0..1)
Checking for package updates...
Your software is up to date.
```

**Comment by supechicken** [comment]
That's expected when running `crew update` on base older than #7725 since `package.rb` have not updated yet

Try again and the error should gone😃

**Comment by satmandu** [comment]
This shouldn't be an issue in the containers either after we update the containers.

But it also raises another question: Should we spawn a new process for `crew update compatible` after doing the portion of `crew update` which updates the `crew` script and the other `lib` scripts?

**Comment by supechicken** [comment]
> This shouldn't be an issue in the containers either after we update the containers.
> 
> But it also raises another question: Should we spawn a new process for `crew update compatible` after doing the portion of `crew update` which updates the `crew` script and the other `lib` scripts?

We can just reload the libraries with `load` function after `git pull`:
```ruby
Dir["#{CREW_LIB_PATH}/lib/*.rb"].each do |lib|
  load 'lib/package.rb'
end
```

**Comment by satmandu** [comment]
> > This shouldn't be an issue in the containers either after we update the containers.
> > 
> > But it also raises another question: Should we spawn a new process for `crew update compatible` after doing the portion of `crew update` which updates the `crew` script and the other `lib` scripts?
> 
> We can just reload the libraries with `load` function after `git pull`:
> ```ruby
> Dir["#{CREW_LIB_PATH}/lib/*.rb"].each do |lib|
>   load lib
> end
> ```

Yes, but that wouldn't pull in any changed logic in `crew` itself...

**Comment by uberhacker** [comment]
This is mitigated with the message to rerun `crew upgrade`, if necessary.
