### ISSUE TITLE
🐞 Bug: `crew help` lists extra unknown commands

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7775]
```
$ crew help
Usage: crew help <command>
Available commands: build, const, deps, download, files, help, install, list, postinstall, reinstall, remove, search, sysinfo, update, upgrade, whatprovides, license., version.
$ crew license
Could not understand "crew license".
Did you mean?
  license.
$ crew license.
Could not understand "crew license.".
Usage:
  crew build [options] [-k|--keep] <name> ...
  crew const [options] [<name> ...]
  crew deps [options] [-t|--tree] [-b|--include-build-deps] [--exclude-buildessential] <name> ...
  crew download [options] <name> ...
  crew files [options] <name> ...
  crew help [<command>]
  crew install [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew list [options] (available|installed|compatible|incompatible)
  crew postinstall [options] <name> ...
  crew reinstall [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew remove [options] <name> ...
  crew search [options] [<name> ...]
  crew sysinfo [options]
  crew update [options] [<compatible>]
  crew upgrade [options] [-k|--keep] [-s|--build-from-source] [<name> ...]
  crew whatprovides [options] <pattern> ...
$ crew version
Could not understand "crew version".
Did you mean?
  version.
$ crew version.
Could not understand "crew version.".
Usage:
  crew build [options] [-k|--keep] <name> ...
  crew const [options] [<name> ...]
  crew deps [options] [-t|--tree] [-b|--include-build-deps] [--exclude-buildessential] <name> ...
  crew download [options] <name> ...
  crew files [options] <name> ...
  crew help [<command>]
  crew install [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew list [options] (available|installed|compatible|incompatible)
  crew postinstall [options] <name> ...
  crew reinstall [options] [-k|--keep] [-s|--build-from-source] [-S|--recursive-build] <name> ...
  crew remove [options] <name> ...
  crew search [options] [<name> ...]
  crew sysinfo [options]
  crew update [options] [<compatible>]
  crew upgrade [options] [-k|--keep] [-s|--build-from-source] [<name> ...]
  crew whatprovides [options] <pattern> ...
```

**Comment by uberhacker** [comment]
@supechicken: Any ideas on how to fix this issue?  FWIW, it'd be nice to have `crew license` and `crew version` commands. :)

**Comment by RuthNjeri** [comment]
Hello @uberhacker  and @supechicken, I would love to create a PR for this issue :)
I did some digging and discovered this file https://github.com/chromebrew/chromebrew/blob/master/bin/crew it contains the list of commands. On my terminal, if I type, crew --version or crew --license. It works
![image](https://user-images.githubusercontent.com/7622875/213107947-d7da022e-c4df-454a-87a3-0d2e4ef645e8.png)

The commands are listed with the double hyphens, if you type them without the hyphens, they don't work.
![image](https://user-images.githubusercontent.com/7622875/213108159-1eb47c56-16bb-4e71-97e8-032160345463.png)


Possible solutions, 
1. Update the commands in the crew file to include an option without the hyphen
2. Update the list of commands under usage to show that the commands need the double hyphen

Let me know which option you prefer, I can create the PR ASAP

**Comment by uberhacker** [comment]
Hi @RuthNjeri: Thank you for your interest in this issue.  I'm for both options!  The issue here is only the commands without hyphens should be displayed when entering `crew help` without a help topic.

**Comment by uberhacker** [comment]
It would be nice to at least keep the version switch options `--version` and `-V` but it's fine to add `crew version` too.
