### ISSUE TITLE
Request Distrobox (and podman)

### ISSUE THREAD

**Issue by trashbus99** [chromebrew/chromebrew#7821]
https://github.com/89luca89/distrobox

**Comment by uberhacker** [comment]
This requires virtualization in the kernel which most Chromebooks don't support.  Also, 4 gb of ram is really an absolute minimum to run and 8 gb is probably a more realistic usable minimum.  Unfortunately, most Chromebooks are limited to 4 gb or less so this would only work on a high-end device.

**Comment by trashbus99** [comment]
or a repurposed machine with chromeos-flex for example or brunch?

**Comment by satmandu** [comment]
Added podman to https://github.com/chromebrew/chromebrew/pull/7824

**Comment by satmandu** [comment]
(without init scripts... have fun with it...)

**Comment by satmandu** [comment]
Also added distrobox, but UNTESTED.

**Comment by s1gnate-sync** [comment]
@uberhacker I got the impression that KVM is widespread, crosvm won't work otherwise (meaning no android and linux support)

**Comment by s1gnate-sync** [comment]
@satmandu I think the simplest solution is to run docker/podman inside virtual machine. crosvm is very fast and overhead is little. I've been using docker+vm setup for quiet a while and it's the most stable part of my modifications in chromeos + it doesn't require writable rootfs so more users can use it safely.

My VM (crosvm + alpine linux) with just docker and nothing running consumes 50mb. For comparison empty termina (with stopped or removed penguin container) consumes around 900mb. I actually surprised that it so resource heave as penguin consumes only 130mb if executed directly on crosvm (without termina and lxd).

**Comment by satmandu** [comment]
@s1gnate-sync Correct me if I'm wrong, but that requires nested kvm support, which older ChromeOS kernels don't have enabled, right?

**Comment by s1gnate-sync** [comment]
@satmandu I think it's enabled and it's definitely works for me :)

My kernel is "Linux localhost 5.15.112-19403-gb69e1c36e415 #1 SMP PREEMPT Wed Jul 26 19:03:36 PDT 2023 aarch64 GNU/Linux"

If you want to try yourself I created a no dependency single shell script to bootstrap custom virtual machine with docker, it takes about half a minute :)

https://gist.github.com/s1gnate-sync/2b17ffb4cfc21a764f784370c61c4fb2

**Comment by s1gnate-sync** [comment]
I wonder how LXD would work if nested KVM is not enabled? Just to clarify the solution I propose doesn't need crostini/termina/penguin to run.

**Comment by satmandu** [comment]
Many machines are not on 5.15 though. Older kernels did not have it enabled.

**Comment by s1gnate-sync** [comment]
Ah I see... I thought 5.15 is already too old :D
