### ISSUE TITLE
Socat: the source of 1.7.3.2 is no longer available. 

### ISSUE THREAD

**Issue by yanyuechuixue** [chromebrew/chromebrew#7855]
https://github.com/chromebrew/chromebrew/blob/f895af6d6f2bd27d88a974303d7c6d5cf09a5fe2/packages/socat.rb#L9

see http://www.dest-unreach.org/socat/download/

**Comment by satmandu** [comment]
We need to update to http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.gz
