### ISSUE TITLE
Sommelier isn't starting 🐞

### ISSUE THREAD

**Issue by gaslec** [chromebrew/chromebrew#7880]
**Describe the bug**
Sommelier isn't starting, only giving this error message:
```
Sommelier can use direct scaling.
some sommelier processes failed to start
```
I have an aarch64 chromebook (acer spin 513 lazor / trogdor) with version 107.0.5304.110 (Official build) (32 bits).

**What I did**

- powerwash the chromebook + full reinstall of crew and sommelier

- `source ~/.bashrc && restartsommelier
`

**Expected behavior**
It should start without errors and letting me launch GUI apps by running `sommelier <commands>`.
However, I'm only getting this:
```
sommelier mpv
error: could not initialize wayland channel: No such file or directory
```

**Environment:**
***
- Architecture: `aarch64` (`aarch64`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.30.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: aebb3d9 `Update filezilla packages (#7879) (8 hours ago)`

- OS variant: `Chrome OS`
- OS version: `trogdor-release/R107-15117.112.0`
- OS channel: `stable-channel`
***

**Comment by satmandu** [comment]
What does `/usr/local/var/log/sommelier.log` show?

**Comment by gaslec** [comment]
Here is the content of the log file:
```error: could not open  (No such file or directory)
error: could not open  (No such file or directory)
error: could not open  (No such file or directory)
error: could not open  (No such file or directory)
error: could not open  (No such file or directory)
error: could not open  (No such file or directory)
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
(EE) could not connect to wayland server
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
```

(I also upgraded to ChromeOS version 109.x instead of 107.x, not changing anything)

**Comment by satmandu** [comment]
Sommelier is complaining about being unable to connect to your ChromeOS exo wayland server....
hmmm.

Can you try this to see if the wayland server is working at all?
```
yes | crew install gnome_console
WAYLAND_DISPLAY=wayland-0 XDG_SESSION_TYPE=wayland kgx
```

**Comment by gaslec** [comment]
Oh okay, strange!
Here is the output of the second command:
```
(kgx:24354): Gtk-WARNING **: 04:46:55.896: cannot open display: :0
```

**Comment by satmandu** [comment]
Oops.

Try this:
```
WAYLAND_DISPLAY=wayland-0 GDK_BACKEND=wayland XDG_SESSION_TYPE=wayland kgx
```

**Comment by gaslec** [comment]
Thanks, this one is working!
Does you know what could be the issue?
![image](https://user-images.githubusercontent.com/60482848/215383879-42535196-b5de-4f06-a5c9-9ee64b3e31e4.png)

**Comment by satmandu** [comment]
Ok so your wayland interface IS working. So that's good.

Does a `restartsommelier` help at all?

Does `crew reinstall xwayland` do anything?

You might also have to try a `crew reinstall -s sommelier`

**Comment by gaslec** [comment]
Thanks for you answers!
I tried the 3 commands but none of them are fixing the issue :(
Still having the same problem. Maybe I'm missing a dependency? Or my config files aren't set the right way?

**Comment by satmandu** [comment]
@uberhacker @supechicken Any ideas on this I don't have an arm machine...

**Comment by satmandu** [comment]
You might also try `sudo chown root /tmp/.X11-unix`

**Comment by satmandu** [comment]
For mpv you could also try `WAYLAND_DISPLAY=wayland-0 GDK_BACKEND=wayland XDG_SESSION_TYPE=wayland mpv`

**Comment by gaslec** [comment]
> WAYLAND_DISPLAY=wayland-0 GDK_BACKEND=wayland XDG_SESSION_TYPE=wayland mpv

Sadly not working!
Your command with kgx is still the only working way to have a graphical output as of now, gimp is for example not working too.

For mpv, it's giving this:
```
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 32: Permission denied
Segmentation fault (core dumped)
```

**Comment by gaslec** [comment]
Wait, by running this as root, I'm now getting audio! Had to do something with permissions

**Comment by satmandu** [comment]
So no video then?

**Comment by gaslec** [comment]
No, still not getting video! I do think it don't get permissions to connect to wayland or something like that

**Comment by gaslec** [comment]
Hello!
I just build sommelier myself using https://github.com/akvadrako/sommelier
I can start `kgx` with it, but for other apps, I'm getting 
```
error: could not open /dev/wl0 (No such file or directory)
```
Is there a way to create that dir, since it's read-only filesystem?

**Comment by gaslec** [comment]
Oh thanks for your awnser! I made a build of the latest version from ChromiumOS website, and still having that issue. 
I don't know what I could do, is that an issue with my chromebook? Or with ARM64? I can maybe powerwash if that can help, not sure if it will change anything...

**Comment by gaslec** [comment]
Could that be the issue?
```
localhost /usr/local/bin # ./sommelier -h
./sommelier: line 18: /usr/local/bin/./../lib/ld-linux-armhf.so.3: No such file or directory
```

**Comment by uberhacker** [comment]
I'm guessing sommelier needs to be rebuilt (patch reworked?) against the 5.15 kernel.  It seems to run fine on earlier kernels.

**Comment by satmandu** [comment]
Does a `crew reinstall -s sommelier` work on a machine with kernel 5.15?

**Comment by gaslec** [comment]
I would be glad to test, however `less` is in `/usr/local/bin/less` and the build script is looking for `/usr/bin/less`. Not sure on how I can fix that since that's a read-only filesystem. 🤔 
```
chronos@localhost ~ $ crew reinstall -s sommelier
[...]
Found ninja-1.11.1 at /usr/local/bin/ninja

ERROR: Failed to start pager: [Errno 2] No such file or directory: '/usr/bin/less'
/usr/local/lib/crew/lib/package.rb:305:in `system': Command failed with exit 1: bash
There was a build error.

chronos@localhost ~ $ which less
/usr/local/bin/less
```

**Comment by gaslec** [comment]
Since I messed up a bit with crouton, I made a clean powerwash of my chromebook. So I now have a clean and up-to-date chromebrew install.

However, sommelier is still not starting with a classic installation, and I can't build it with `crew reinstall -s sommelier`, the build process is looking for `less` in `/usr/bin/` instead of `/usr/local/bin/`.

```
chronos@localhost ~ $ crew reinstall -s sommelier
(...)
ERROR: Failed to start pager: [Errno 2] No such file or directory: '/usr/bin/less'
/usr/local/lib/crew/lib/package.rb:305:in `system': Command failed with exit 1: bash
There was a build error.
chronos@localhost ~ $ which less
/usr/local/bin/less
```

**Comment by uberhacker** [comment]
Does `export PAGER=/usr/local/bin/less` fix it?

**Comment by gaslec** [comment]
Thanks for the hint, that's fixing it!
However, building sommelier from source isn't fixing anything and still having 
```
some sommelier processes failed to start
```
Could I provide some more logs of what's happening or something like that?
Thanks for the time you're taking to help me :)

**Comment by uberhacker** [comment]
Yes the output from `/usr/local/var/log/sommelier.log` is really the only effective way to debug.

**Comment by gaslec** [comment]
Here is the output:
```
chronos@localhost / $ cat /usr/local/var/log/sommelier.log 
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
(EE) could not connect to wayland server
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
(EE) could not connect to wayland server
```

**Comment by uberhacker** [comment]
Does `sudo chown -R root:root /tmp/.X11-unix` help?

**Comment by gaslec** [comment]
No, still not starting properly and the log is the same.
It should maybe be set as root during his creation if it's a directory made by sommelier?

**Comment by uberhacker** [comment]
What happens if you prefix the start with `sudo restartsommelier`?

**Comment by gaslec** [comment]
Interesting, the issue is different when I try with `sudo restartsommelier`
```Failed to create /root/.cache for shader cache (Read-only file system)---disabling.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: failed to connect to wayland-0
```
XDG_RUNTIME_DIR should be set to which value?

**Comment by uberhacker** [comment]
Try `export XDG_RUNTIME_DIR=/var/run/chrome`.  FWIW, this can also be achieved via `crew install xdg_base` so maybe that needs to be a dependency?

**Comment by gaslec** [comment]
Not fixing the issue (and `xdg_base` was already installed).
But starting sommelier without sudo is now not giving permissions error (don't know since when).
I now only have in the log:
```
sommelier.elf: ../sommelier.cc:627: void sl_registry_handler(void *, struct wl_registry *, uint32_t, const char *, uint32_t): Assertion `!ctx->xdg_shell' failed.
(EE) could not connect to wayland server
```

**Comment by uberhacker** [comment]
This looks outside the scope of this package and into wayland server debugging territory.

**Comment by satmandu** [comment]
It's possible we need to update sommelier for kernel 5.15.  @supechicken see any new relevant commits?

**Comment by gaslec** [comment]
Does you know to which version of ChromeOS I should downgrade to have sommelier working?
I don't care to be kinda outdated if I can graphically run some native applications, I can wait for a fix :)
And if you need to run some tests on an ARM Chromebook, don't hesitate to ask!

**Comment by ncdm-stldr** [comment]
It seems I have the same issue. I also have kernel version 5.15.
I tried crostini as well, and sommelier is working there.

About kernel versions I have:

From crosh:
```
chronos@localhost / $ uname -r
5.15.77-14430-g89aabe014a6d
```
From crostini terminal:
```
my_username@penguin:~$ uname -r
5.10.153-20434-g98da1eb2cf9d
```
I was surprised because I assumed chromeos and crostini shared the same kernel, and therefore I woud have expected the command to return the same version in both terminals.

**Comment by uberhacker** [comment]
I can confirm it works on armv7l with the 4.19 kernel on ChromeOS 84.   However, on aarch64 with the 4.19 kernel and the latest ChromeOS 108, it doesn't work.  In `/usr/local/var/log/sommelier.log`, I see `error: could not open  (no such file or directory)`.  So...apparently this issue is not isolated to the 5.x kernel.  It could be ChromeOS or an architecture specific issue, however.  In any event, sommelier needs work.  I'd like to see fewer `&>/dev/null`s to help debug.  Nothing wrong with a little extra verbosity.

**Comment by supechicken** [comment]
Merge with #7891
