### ISSUE TITLE
`crew install glibc` creates symlinks in /usr/local/lib/ whose target doesn't exist

### ISSUE THREAD

**Issue by ncdm-stldr** [chromebrew/chromebrew#7905]
**Describe the bug**
After installing glibc with `crew install glibc` , some symlinks are added in `usr/local/lib` , like for instance `libpthread.so` or `libutil.so`. However, in my case, the symlink target doesn't  exist:
```
$ crew whatprovides libpthread.so
glibc: /usr/local/lib/libpthread.so
glibc: /usr/local/lib/libpthread.so.0

$ ls -l /usr/local/lib/ | grep libpthread.so
lrwxrwxrwx.  1 chronos chronos        22 Jan  7 07:10 libpthread.so -> /usr/lib/libpthread.so
lrwxrwxrwx.  1 chronos chronos        20 Feb  6 21:14 libpthread.so.0 -> /lib/libpthread.so.0

ls  /usr/lib/libpthread.so
ls: cannot access '/usr/lib/libpthread.so': No such file or directory
```

**To Reproduce**

I removed and installed crew again (for a fresh start). Then I installed the glibc package with `crew install glibc`.
After that, I noticed the problem explained above.

In fact, I encountered the issue when installing the `build_essential` package straight after `glibc` (`libpthread.so` was needed during the installation).  

**Expected behavior**
The missing libraries should be there?

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`aarch64`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.30.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: c3bbf3f `Wp_cli 2.7.0 => 2.7.1 (#7899) (23 hours ago)`

- OS variant: `Chrome OS`
- OS version: `strongbad-release/R109-15236.80.0`
- OS channel: `stable-channel`

</details>
***

**Comment by satmandu** [comment]
`/usr/lib/libpthread.so` on glibc 2.27 is literally:
```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf32-littlearm)
GROUP ( /lib/libpthread.so.0 /usr/lib/libpthread_nonshared.a )
```

Also `/usr/local/lib/libpthread.so`:
```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf32-littlearm)
GROUP ( /usr/local/lib/libpthread.so.0 /usr/local/lib/libpthread_nonshared.a )
```

What does `crew const LIBC_VERSION` give you?

**Comment by satmandu** [comment]
I'm waiting for some recovery images after M107 to be made available so I can do some testing with some newer milestone images...

**Comment by ncdm-stldr** [comment]
```
$ crew const LIBC_VERSION
LIBC_VERSION=2.35
```

So `/usr/local/lib/libpthread.so` on your machine is not a symlink, but a proper file right?

**Comment by satmandu** [comment]
Yes, but it's a tiny text file, as you can see...

**Comment by supechicken** [comment]
Not sure if this is helpful: `libpthread` is now built-in to glibc linker (instead of a standalone library file) since glibc 2.35

Since glibc 2.35, a file called `libpthread.a` file was added for backward compatbility

**Comment by satmandu** [comment]
Yes, I think that is the right approach. Do you want to submit a PR to fix that?

**Comment by ncdm-stldr** [comment]
> Yes, I think that is the right approach. Do you want to submit a PR to fix that?

Yes I would like to try submiting a PR.

There is something I don't understand with the install scripts: since installing a package creates some files, when one removes a packages with `crew remove`, how does crew know which files to remove?

**Comment by satmandu** [comment]
crew normally has a filelist and dirlist for each installed package stored in `/usr/local/etc/crew/meta/`. It deletes those during removal.

**Comment by satmandu** [comment]
(changes made during postinstall though may not be reflected in those filelists...)

**Comment by smartguy1196** [comment]
> There is something I don't understand with the install scripts: since installing a package creates some files, when one removes a packages with `crew remove`, how does crew know which files to remove?

You could always powerwash, if you really want to be sure (assuming you still have a read-only filesystem)

**Comment by satmandu** [comment]
Yes, but we try not to powerwash for most things...   Most of my testing is from just starting a new container, which let's me use a fresh container on every instantiation... it's much quicker!

(I'd do that on device if I could get docker to work in ChromeOS...)

**Comment by satmandu** [comment]
I'm rebuilding glibc 2.35 now that M109 recoveries are available.
