### ISSUE TITLE
🐞 gimp fails to start, because libjson-c is v5 but expecting v4

### ISSUE THREAD

**Issue by thomas725** [chromebrew/chromebrew#7922]
On a freshly setup Acer N20Q4 Chromebook, I've installed gimp:  `crew install gimp`.
Starting `gimp` fails:
> gimp: error while loading shared libraries: /usr/local/lib/libjson-c.so.4: cannot open shared object file: No such file or directory

```
chronos@localhost / $ ls -alih /usr/local/lib/libjson-c.*
1223991 -rw-r--r--. 1 chronos chronos 402K Nov 18 09:12 /usr/local/lib/libjson-c.a
1223988 lrwxrwxrwx. 1 chronos chronos   14 Nov 18 09:13 /usr/local/lib/libjson-c.so -> libjson-c.so.5
1223989 lrwxrwxrwx. 1 chronos chronos   29 Nov 18 09:13 /usr/local/lib/libjson-c.so.3 -> /usr/local/lib/libjson-c.so.4
1223990 lrwxrwxrwx. 1 chronos chronos   18 Nov 18 09:13 /usr/local/lib/libjson-c.so.5 -> libjson-c.so.5.2.0
1223992 -rwxr-xr-x. 1 chronos chronos  68K Nov 18 09:12 /usr/local/lib/libjson-c.so.5.2.0
```

I've worked around the issue on my machine by running `cd /usr/local/lib ; ln -s libjson-c.so libjson-c.so.4` but maybe you could adapt the package to do that automatically on install, just as it seems it has been done for version 3.

**Comment by satmandu** [comment]
I have a rebuild of `jsonc` incoming to fix this.

**Comment by uberhacker** [comment]
I already fixed it.

**Comment by satmandu** [comment]
> I already fixed it.

Where?
