### ISSUE TITLE
signal_desktop for arm = aarch64?

### ISSUE THREAD

**Issue by thomas725** [chromebrew/chromebrew#7923]
I'd like to use the signal messenger desktop app on my chromebook.

First I've found and followed a guide to install it through the "linux development environment" virtual-machine, but that one eats so much of the 4GB of RAM available on my system that it starts paging to swap all the time making it unusably slow.

I've already successfully migrated gimp from the vm to using the gimp package available through chromebrew (huge thanks for that beeing available!)

But the [signal_desktop package](https://github.com/chromebrew/chromebrew/blob/master/packages/signal_desktop.rb) doesn't work for arm = aarch64 chromebooks so far:
> Package signal_desktop is not compatible with your device architecture (aarch64) :/

So I'm wondering if it may be possible to adept it to do or add a separate signal_desktop_arm package like it [exists in the AUR](https://aur.archlinux.org/packages/signal-desktop-arm).

Related links:
https://github.com/signalapp/Signal-Desktop/issues/6063#issuecomment-1235329786

**Comment by supechicken** [comment]
Yes, `signal_desktop` supports `aarch64` (it is possible run it on your hardware), but a 64-bit runtime library is required for running it properly (`aarch64` means 64-bit, while `armv7l` means 32-bit).

However, only 32-bit runtime library is available in Chrome OS only, thus only 32-bit `armv7l` executables can be run on the Chrome OS dev shell.

**Comment by satmandu** [comment]
We could in theory rebuild signal for armv7l from scratch, but building that would be a massive undertaking... As it also requires building electron.

Electron takes a ton of memory and time to build.

You would probably be better off using the Android build of signal with the android runtime ChromeOS comes with, but that also uses its own large amount of RAM...

**Comment by thomas725** [comment]
The Signal Android app sadly can't be used as a replacement for the Signal Desktop app.
Only one Signal Android app can be used per account, the Desktop app allows you to connect to the Android app running on the phone and therefore use the same account on the phone and the desktop.

If I'd use the Android app on phone and desktop, I'd have to use two separate accounts on both devices.
