### ISSUE TITLE
Chromebrew installation command does nothing

### ISSUE THREAD

**Issue by notfromohio22** [chromebrew/chromebrew#7924]
**Describe the bug**
I try to run the install command and no error comes up, and yet mothing happens. No output, nothing. It just opens a new command. 

**To Reproduce**

1. I executed this command:

      ```shell
      # curl -Ls git.io/vddgY | bash
      ```

      Output:

      ```
      # N/A
      ```

**Expected behavior**
I expected it to run the installation script, as it had on my past two Chromebooks.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
I can't use the crew command since I can't install Chromebrew, but I can give you system info.
![image](https://user-images.githubusercontent.com/125190126/218309457-833b012c-809f-48d1-83d5-255d45d04ca2.png)

***

**Additional context**
This is a brand new developer mode Chromebook. I am doing all these commands after typing in shell.
What I think needs to be done:

      - [I would like a raw.githubusercontent link to curl or just a plain download link so I can chmod it. ] step one
      - [I would also like to know why this even happened in the first place, if you can give me that info. ] step two

**Comment by satmandu** [comment]
Can you first update your Chromebook to the current version, and then try the Chromebrew installer?

**Comment by notfromohio22** [comment]
I can't, this is a chromebook stuck at version 103.
![image](https://user-images.githubusercontent.com/125190126/218332441-dc9de34a-d050-48fb-bfdf-48fb97f57028.png)
Is there a way to manually force my chromebook to update?

**Comment by satmandu** [comment]
Can you try this: `curl -Ls git.io/vddgY | bash -x`

**Comment by satmandu** [comment]
Did that work at all for you, or give you any new information on why it was failing?

**Comment by satmandu** [comment]
Please reopen when you have time to provide more information...

**Comment by blankuserrr** [comment]
I'm also having this issue. ![Image](https://github.com/user-attachments/assets/4d570ce4-93b8-4dd5-baad-a20321e497f5)

**Comment by satmandu** [comment]
(Feel free to help us debug the install issue from looking at that script so we can get it to work for your systems.)

**Comment by blankuserrr** [comment]
> FYI the raw link to the current [install.sh](https://github.com/chromebrew/chromebrew/raw/refs/heads/master/install.sh) (which is on the main Chromebrew page) is this:
> 
> https://github.com/chromebrew/chromebrew/raw/refs/heads/master/install.sh

I tried running `curl -Ls https://raw.githubusercontent.com/chromebrew/chromebrew/refs/heads/master/install.sh | bash -x`, but again it outputs what it did last time, and I can't do ctrl-c or anything similar.

**Comment by uberhacker** [comment]
Did you run in crosh or a VT-2 session?

**Comment by blankuserrr** [comment]
I ran it in a VT-2 session, although I suspect my VT-2 instance may have some problems
