### ISSUE TITLE
'some sommelier processes failed to start'

### ISSUE THREAD

**Issue by Acalann** [chromebrew/chromebrew#7940]
**Describe the bug**
I cannot start sommelier, it says 'some sommelier processes failed to start'
**To Reproduce**

1. I executed this command:

      ```shell
      startsommelier
      ```

      Output:

      ```
      chronos@localhost / $ startsommelier
      Sommelier can use direct scaling.
      some sommelier processes failed to start
      ```

**Expected behavior**
For sommelier to work
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.29.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: bc88bc4 `Add act package (#7769) (7 weeks ago)`

- OS variant: `Chrome OS`
- OS version: `hatch-release/R109-15236.80.0`
- OS channel: `stable-channel`

</details>
***

**Comment by uberhacker** [comment]
Thank you for the feedback @Acalann.  This is a duplicate of #7891.  If you can provide the output of `/usr/local/var/log/sommelier.log`, that will help us to troubleshoot this issue.

**Comment by Acalann** [comment]
`/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
/usr/local/bin/sommelier.elf: symbol lookup error: /usr/local/bin/../lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE`

**Comment by Acalann** [comment]
https://pastebin.com/1jUQvaEd

**Comment by uberhacker** [comment]
Your crew version is a few releases behind.  Try `crew update && crew upgrade` and then `restartsommelier` to see if that fixes it.

**Comment by Acalann** [comment]
Nope, updated and still not working.

**Comment by uberhacker** [comment]
Same error in the log?

**Comment by Acalann** [comment]
Yes.

**Comment by satmandu** [comment]
Can you try this and tell us if it works:
```
CREW_TESTING_REPO=https://github.com/uberhacker/chromebrew.git CREW_TESTING_BRANCH=update-sommelier CREW_TESTING=1 crew update
crew upgrade sommelier
restartsommelier
```

**Comment by satmandu** [comment]
Sommelier has been updated. Please do a `crew update ; crew upgrade ; restartsommelier` to see if that fixes your issue.

**Comment by Acalann** [comment]
Thanks, it works now.
