### ISSUE TITLE
Package nvm not working

### ISSUE THREAD

**Issue by thonkinator** [chromebrew/chromebrew#7959]
I just installed chromebrew and the first package I tried to install was nvm. After discovering #1342, I installed it with `-s`, but attempting to install any node versions fails with `bash: ./configure: Permission denied`. Is there any way to fix this? Also, I noticed the `nvm` version the package installs is 0.35.0, while the latest is 0.39.3.

**Comment by satmandu** [comment]
Have you tried using `nodebrew`?

**Comment by thonkinator** [comment]
That did work, thanks. But if the solution to `nvm` not working is to just not use it, I question why it is still available as a package.

**Comment by satmandu** [comment]
@uberhacker thoughts?

**Comment by uberhacker** [comment]
We can try and see if an update fixes it.  It's been awhile since that package was updated.

**Comment by uberhacker** [comment]
@thonkinator: The nvm package has been updated.  Run `crew update && crew upgrade` when you get a chance to see if it fixes your earlier issue.

**Comment by thonkinator** [comment]
@uberhacker do i still need to build from source with -s?

**Comment by uberhacker** [comment]
No need.  The important thing to get it working after the install is to run `source ~/.bashrc`.  This will activate the `nvm` command to make it executable.
