### ISSUE TITLE
🐞 crew attempts to build packages without compatibility with the current arch when they are dependencies

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#7967]
sommelier does not have compatibility with i686.
sommelier is a dependency of xterm.
Try to install sommelier with `crew install sommelier` and it fails.
Try to install xterm with `crew install xterm` and all dependencies get installed, and then crew attempts to build sommelier.

crew should refuse to install packages when ANY of the dependencies lacks compatibility with the current architecture.

**Comment by satmandu** [comment]
@supechicken Does this sound like a dependency resolver bug?

**Comment by satmandu** [comment]
(This is assuming https://github.com/chromebrew/chromebrew/pull/7955 gets merged.)

**Comment by uberhacker** [comment]
An easy fix would be to change from `compatibility 'all'` to `compatibility 'aarch64,armv7l,x86_64'` in xterm.  In fact, we should probably change this for all packages that have sommelier as a dependency.

**Comment by satmandu** [comment]
That's not a fix that's a narrowly focused workaround...

**Comment by uberhacker** [comment]
It's actually fixing xterm which really is not i686 compatible. :)

**Comment by satmandu** [comment]
I'm sure there will be other examples...

**Comment by Zopolis4** [comment]
This should count as a bug-- if the package is truly incompatible, building it from source will not work, and if the package is actually compatible and building it from source will work, it should not be marked as incompatible.
