### ISSUE TITLE
🐞 crew deps -t always shows build deps

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#8002]
`crew deps -tb codium` should show build deps, but `crew deps -t codium` should not.

And yet...
![image](https://user-images.githubusercontent.com/1096701/221469842-6cb7ee30-652e-4bfa-a0a5-43cc77c270af.png)

Any ideas @supechicken ?

**Comment by Zopolis4** [comment]
This still happens on latest master, but not when running `crew deps -t vala`. `crew deps -t vscodium` is still broken though. Maybe its because there is no build section in `vscodium`? (Also, we should probably fix that and mark it as `no_compile_needed`.
