### ISSUE TITLE
🐞 Bug: package file conflicts

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#8039]
```
$ crew whatprovides libatk-1.0.so.0
at_spi2_core: /usr/local/lib64/libatk-1.0.so.0
at_spi2_core: /usr/local/lib64/libatk-1.0.so.0.24609.1
atk: /usr/local/lib64/libatk-1.0.so.0
atk: /usr/local/lib64/libatk-1.0.so.0.23809.1
$ crew whatprovides libatk-bridge-2.0.so.0
at_spi2_atk: /usr/local/lib64/libatk-bridge-2.0.so.0
at_spi2_atk: /usr/local/lib64/libatk-bridge-2.0.so.0.0.0
at_spi2_core: /usr/local/lib64/libatk-bridge-2.0.so.0
at_spi2_core: /usr/local/lib64/libatk-bridge-2.0.so.0.0.0
```
Probably what makes sense it to remove the library files from at_spi2_core or remove the conflicting package if all the same files are provided by the other package.

**Comment by satmandu** [comment]
As per https://discourse.gnome.org/t/atk-and-at-spi2-atk-merged-into-at-spi2-core/10032

Atk & at-spi2-atk have BOTH been merged into at-spi2-core...

So I'll create a PR with a new build of core which supersedes all three packages, I guess...
