### ISSUE TITLE
crew-mvdir fails to install packages with files in CREW_DEST_HOME 🐞 Bug

### ISSUE THREAD

**Issue by Insiro** [chromebrew/chromebrew#8063]
**Describe the bug**
when install linter by crew
this error occured

**To Reproduce**

1. I executed this command:

      ```shell
      crew install linter
      ```

      Output:

      ```
      /home/chronos/user/.mdlrc: rename() failed: Invalid cross-device link
      /usr/local/bin/crew:1278:in 'system':Command failed with exit 18: crew-mvdir(RuntimeError)
      from /usr/local/bin/crew/1278:in 'install_files'
      ```

**Comment by satmandu** [comment]
workaround is `crew remove crew_mvdir ; yes | crew install linter ; crew install crew_mvdir`

**Comment by satmandu** [comment]
This also occurs with `mpv`, and potentially other packages...

**Comment by satmandu** [comment]
The merge of https://github.com/chromebrew/chromebrew/pull/8074 currently addresses this until @supechicken gets their new `crew-mvdir` build built and merged...
