### ISSUE TITLE
🐞 Bug: some packages broken by libtiff upgrade

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#8083]
Graphviz & other packages broken by current libtiff update:

- [x] evince
- [x] gdk_pixbuf
- [x] gdal
- [x] gegl
- [x] ghostscript
- [x] libgeotiff
- [x] libwebp

Graphviz error:
```
$ dot -c
Error: /usr/local/lib64/graphviz/config6 is zero sized.
Warning: Could not load "/usr/local/lib64/graphviz/libgvplugin_gdk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/usr/local/lib64/graphviz/libgvplugin_gs.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/usr/local/lib64/graphviz/libgvplugin_gtk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Segmentation fault
```

**Comment by satmandu** [comment]
Looks like some rebuilds need to happen to account for the libtiff update...

**Comment by satmandu** [comment]
It's times like this, I think it would be REALLY useful to have a list of symbol exports from libraries to check against when updating libraries, like debian does...

Or more simply just save the output of lddtree in some manner so we can crosscheck against that... maybe use a database?

**Comment by satmandu** [comment]
Sigh... it's times like this I think a CS degree might be useful... since I have these "Damn, I wish I could read" moments...
