### ISSUE TITLE
Using Chromebrew with multiple user accounts on the same Chromebook?

### ISSUE THREAD

**Issue by thomas725** [chromebrew/chromebrew#8087]
I've installed Chromebrew on my Chromebook using one user account, and now would have liked to continue using or alternatively installing it a second time with another user account, but that didn't work. Trying to reinstall fails like this:
```
$ curl -Ls git.io/vddgY | bash
curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

Alternatively trying to upgrade the already installed one or using it in any other way results in:
```
$ crew update
ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

Is there some way to use Chromebrew from multiple user accounts?

**Comment by satmandu** [comment]
All ChromeOS users share `/usr/local`, which is where Chromebrew installs.

You might need to clean out `/usr/local` and do a clean install of Chromebrew.

**Comment by thomas725** [comment]
thanks for the reply! that looked good in the beginning but ends with this error:
```
Setup and synchronize local package repo...

  -=O=- #   #   #     #                                                       
ruby: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

**Comment by satmandu** [comment]
If you blew away all of `/usr/local` before reinstalling and gave you that error, please open a separate issue for that with all the requested information so we can better debug that issue.

Thanks!

**Comment by thomas725** [comment]
I moved everything in /usr/local into a new /usr/local/broken/ folder (including the two hidden folders .cache & .config) before reinstalling, yes. Okey. I'll open a new issue and fill out the template.

**Comment by satmandu** [comment]
I don't know if you were dealing with an armv7l/aarch64 conversion issue, but if so, this should now be resolved with a reinstall of Chromebrew...
