### ISSUE TITLE
Packages do not install, shows RuntimeError

### ISSUE THREAD

**Issue by Vicky-Boi** [chromebrew/chromebrew#8134]
**Describe the bug**
Whenever I try to install any package, it returns an error after it says "Performing install..."

**To Reproduce**
Run the install script, or try to install any package after running the install script.

1. Here is the output for running the installation script:

      ```shell
      curl -Ls git.io/vddgY | bash 
      ```

      Output:

      ```
      Performing install...
      rsync: ACLs are not supported on this client
      rsync error: syntax or usage error (code 1) at main.c(1746) [client=3.2.3]
      /usr/local/bin/crew:1286:in `system': Command failed with exit 1: rsync (RuntimeError)
              from /usr/local/bin/crew:1286:in `install_files'
              from /usr/local/bin/crew:1328:in `block in install_package'
              from /usr/local/bin/crew:1297:in `chdir'
              from /usr/local/bin/crew:1297:in `install_package'
              from /usr/local/bin/crew:1482:in `install'
              from /usr/local/bin/crew:1425:in `block in resolve_dependencies'
              from /usr/local/bin/crew:1422:in `each'
              from /usr/local/bin/crew:1422:in `resolve_dependencies'
              from /usr/local/bin/crew:1346:in `resolve_dependencies_and_install'
              from /usr/local/bin/crew:1795:in `block in install_command'
              from /usr/local/bin/crew:1790:in `each'
              from /usr/local/bin/crew:1790:in `install_command'
              from /usr/local/bin/crew:1922:in `<main>'
      ```

**Expected behavior**
Packages are supposed to install without any issues.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
sh: 1: git: not found
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.14`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.32.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `octopus-release/R111-15329.44.0`
- OS channel: `stable-channel`
</details>
***

**Comment by shivam9465** [comment]
I am also facing the Exact  same issue!

**Comment by SplashTrashX** [comment]
try running the script as root:

sudo curl -Ls git.io/vddgY | bash

**Comment by uberhacker** [comment]
> try running the script as root:
> 
> sudo curl -Ls git.io/vddgY | bash

Chromebrew should never be installed as the root user.  I don't think it will let you even attempt to do it either.

**Comment by SplashTrashX** [comment]
> > try running the script as root:
> > sudo curl -Ls git.io/vddgY | bash
> 
> Chromebrew should never be installed as the root user. I don't think it will let you even attempt to do it either.

It worked for me but if it's risky better not to do it. I will delete the comment

**Comment by Vicky-Boi** [comment]
@uberhacker After nuking /usr/local/, I was successfully able to install chromebrew and got nano + gimp to work. Seems like everything is running smoothly. Is there a particular reason as to why it did not work earlier?

**Comment by uberhacker** [comment]
@Vicky-Boi:  That is great to hear.  My guess is you had rsync installed and it was missing one or more dependencies.  Sometimes things just get corrupted and you have to start fresh.

**Comment by carnhofdaki** [comment]
Works well on `FydeOS v16.0 (FydeOS unlicensed version) Platform 15183.77.16.21 (64-bit)`

Steps to make it work:
1. Download the attached file.
[rsync-from-Alpinelinux-x86_64.tar.gz](https://github.com/chromebrew/chromebrew/files/11160713/rsync-from-Alpinelinux-x86_64.tar.gz)

1. `sudo -i`
2. `cd /; tar xvzf <path_to_file>`
3. 'mount -o remount,rw /` # since we will be adding a musl dynamic loader to /lib
4. `cp /usr/local/rsync/ld* /lib`
5. `mount -o remount,ro /`
6. `exit`
7. Install chromebrew like normal

**Comment by wzqvip** [comment]
> @uberhackernuking /usr/local/ 之后，我成功地安装了 chromebrew 并让 nano + gimp 开始工作。似乎一切都在顺利进行。是否有特殊原因说明为什么它没有更早起作用？

I had the same. refer to https://github.com/chromebrew/chromebrew/issues/8235

**Comment by satmandu** [comment]
Is this still an issue?

**Comment by satmandu** [comment]
Resolved by https://github.com/chromebrew/chromebrew/pull/8386
