### ISSUE TITLE
hardware acceleration using sommelier doesn't work correctly on aarch64 and falls to using llvmpipe/swrender 

### ISSUE THREAD

**Issue by galaxy4627** [chromebrew/chromebrew#8171]
### Description 
I'm using this command to start `sommelier` and run `glxgears` and it's falling back to using llvmpipe
```
sommelier -X \
    --x-display=:0 \
    --scale=1.0 \
    --glamor \
    --force-drm-device=/dev/dri/renderD129 \
    --display=wayland-0 \
    --xwayland-path=/usr/local/bin/Xwayland \
    --xwayland-gl-driver-path=/usr/local/lib/dri \
    --peer-cmd-prefix=/usr/local/lib/ld-linux-armhf.so.3 \
    --noop-driver \
    --no-exit-with-child \
    glxgears
```
### Log
```
chronos@localhost / $ sommelier -X \
    --x-display=:0 \
    --scale=1.0 \
    --glamor \
    --force-drm-device=/dev/dri/renderD129 \
    --display=wayland-0 \
    --xwayland-path=/usr/local/bin/Xwayland \
    --xwayland-gl-driver-path=/usr/local/lib/dri \
    --peer-cmd-prefix=/usr/local/lib/ld-linux-armhf.so.3 \
    --noop-driver \
    --no-exit-with-child \
    glxgears
MESA-LOADER: failed to open zink: /usr/local/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/local/lib/dri, suffix _dri)
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
MESA-LOADER: failed to open zink: /usr/local/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/local/lib/dri, suffix _dri)
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
Refusing to try glamor on llvmpipe
EGL setup failed, disabling glamor
Failed to initialize glamor, falling back to sw
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Error:            Key <CAPS> added to map for multiple modifiers
>                   Using Mod3, ignoring Lock.
Errors from xkbcomp are not fatal to the X server
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
1208 frames in 5.0 seconds = 241.482 FPS
^C
chronos@localhost / $ 
```

### Additional Information

- System Information and Versions

  - Chrome OS version: 

    ```
    CHROMEOS_ARC_ANDROID_SDK_VERSION=28
    CHROMEOS_ARC_VERSION=8834525
    CHROMEOS_AUSERVER=https://tools.google.com/service/update2
    CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
    CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
    CHROMEOS_DEVSERVER=
    CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
    CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
    CHROMEOS_RELEASE_BRANCH_NUMBER=115
    CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R102-14695.115.0
    CHROMEOS_RELEASE_BUILD_NUMBER=14695
    CHROMEOS_RELEASE_BUILD_TYPE=Official Build
    CHROMEOS_RELEASE_CHROME_MILESTONE=102
    CHROMEOS_RELEASE_DESCRIPTION=14695.115.0 (Official Build) stable-channel hana 
    CHROMEOS_RELEASE_KEYSET=mp-v7
    CHROMEOS_RELEASE_NAME=Chrome OS
    CHROMEOS_RELEASE_PATCH_NUMBER=0
    CHROMEOS_RELEASE_TRACK=stable-channel
    CHROMEOS_RELEASE_VERSION=14695.115.0
    DEVICETYPE=CHROMEBOOK
    GOOGLE_RELEASE=14695.115.0
    ```

  - Chromebrew version: `1.32.3`

**Comment by satmandu** [comment]
Has acceleration ever worked on aarch64 with armv7l userspace?

FYI `startsommelier` will start sommelier using the script `/usr/local/sbin/sommelierd`...

**Comment by galaxy4627** [comment]
> Has acceleration ever worked on aarch64 with armv7l userspace?
> 
> FYI `startsommelier` will start sommelier using the script `/usr/local/sbin/sommelierd`...

I know, doesn't change anything tho. And are you saying it's always been broken?

**Comment by satmandu** [comment]
FYI I get 60fps on my x86_64 system with acceleration enabled...

**Comment by galaxy4627** [comment]
> FYI I get 60fps on my x86_64 system with acceleration enabled...

I was able to get lunar client working using crouton but since it's using llvmpipe I'm only able to get around 5-10 FPS where it's unplayable, is there anything I could do to try and "fix" acceleration on arm64

**Comment by satmandu** [comment]
You can see if crostini is any better since they tunnel the GPU through, and it is aarch64 kernel => aarch64 userspace.

**Comment by galaxy4627** [comment]
> You can see if crostini is any better since they tunnel the GPU through, and it is aarch64 kernel => aarch64 userspace.

I've tried using crostini with enabling crostini gpu support and most applications give me a black screen :/ and only with gpu support it does work fine with llvmpipe

**Comment by satmandu** [comment]
What does `glxinfo -B` give you in crostini?

**Comment by galaxy4627** [comment]
> What does `glxinfo -B` give you in crostini?

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0x1af4)
    Device: virgl (0x1010)
    Version: 20.3.5
    Accelerated: yes
    Video memory: 0MB
    Unified memory: no
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: virgl
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by galaxy4627** [comment]
additionally dmesg shows some errors:
```
[  528.977015] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x207)
[  528.985219] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.003126] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.019312] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.039048] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.057045] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.071354] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.096453] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.106085] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  529.127651] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  533.981897] virtio_gpu_dequeue_ctrl_func: 284 callbacks suppressed
[  533.981926] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  533.996239] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.014375] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.030727] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.049751] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.064574] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.083844] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.104232] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.115252] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  534.130762] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  538.983443] virtio_gpu_dequeue_ctrl_func: 357 callbacks suppressed
[  538.983474] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.000075] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.017327] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.032668] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.049462] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.067605] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.085594] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.101726] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.118701] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  539.135469] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  543.996546] virtio_gpu_dequeue_ctrl_func: 306 callbacks suppressed
[  543.996706] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.013637] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.027945] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.052570] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.062905] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.078554] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.095880] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.111707] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.128033] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
[  544.150785] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
``` now this doesn't occur to all applications however most applications work without gpu support

**Comment by satmandu** [comment]
> additionally dmesg shows some errors:
> ```
> [  528.977015] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x207)
> [  528.985219] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.003126] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.019312] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.039048] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.057045] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.071354] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.096453] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.106085] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  529.127651] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  533.981897] virtio_gpu_dequeue_ctrl_func: 284 callbacks suppressed
> [  533.981926] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  533.996239] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.014375] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.030727] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.049751] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.064574] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.083844] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.104232] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.115252] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  534.130762] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  538.983443] virtio_gpu_dequeue_ctrl_func: 357 callbacks suppressed
> [  538.983474] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.000075] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.017327] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.032668] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.049462] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.067605] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.085594] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.101726] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.118701] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  539.135469] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  543.996546] virtio_gpu_dequeue_ctrl_func: 306 callbacks suppressed
> [  543.996706] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.013637] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.027945] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.052570] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.062905] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.078554] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.095880] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.111707] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.128033] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> [  544.150785] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> ``` 
> now this doesn't occur to all applications however most applications work without gpu support
>   

The virtio errors are unsurprising. But at least you have acceleration using the virtwl pass through driver.

How is the glxgears performance in crostini?

**Comment by galaxy4627** [comment]
> > additionally dmesg shows some errors:
> > ```
> > [  528.977015] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x207)
> > [  528.985219] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.003126] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.019312] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.039048] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.057045] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.071354] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.096453] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.106085] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  529.127651] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  533.981897] virtio_gpu_dequeue_ctrl_func: 284 callbacks suppressed
> > [  533.981926] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  533.996239] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.014375] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.030727] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.049751] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.064574] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.083844] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.104232] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.115252] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  534.130762] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  538.983443] virtio_gpu_dequeue_ctrl_func: 357 callbacks suppressed
> > [  538.983474] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.000075] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.017327] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.032668] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.049462] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.067605] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.085594] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.101726] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.118701] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  539.135469] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  543.996546] virtio_gpu_dequeue_ctrl_func: 306 callbacks suppressed
> > [  543.996706] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.013637] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.027945] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.052570] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.062905] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.078554] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.095880] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.111707] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.128033] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > [  544.150785] [drm:virtio_gpu_dequeue_ctrl_func] *ERROR* response 0x1200 (command 0x206)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > now this doesn't occur to all applications however most applications work without gpu support
> 
> The virtio errors are unsurprising. But at least you have acceleration using the virtwl pass through driver.
> 
> How is the glxgears performance in crostini?

```
fake@penguin:~$ glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
282 frames in 5.0 seconds = 56.383 FPS
296 frames in 5.0 seconds = 58.999 FPS
282 frames in 5.0 seconds = 56.279 FPS
285 frames in 5.0 seconds = 56.895 FPS
``` 
and some applications just must be broken then with virtgl

**Comment by galaxy4627** [comment]
so I managed to get minecraft to run but there's some graphical glitches which make the game unplayable?
![image](https://user-images.githubusercontent.com/100154768/231041255-736265b8-2298-4d1e-b13d-1b420994deb6.png)

**Comment by satmandu** [comment]
> so I managed to get minecraft to run but there's some graphical glitches which make the game unplayable? ![image](https://user-images.githubusercontent.com/100154768/231041255-736265b8-2298-4d1e-b13d-1b420994deb6.png)

Worth noting that Minecraft is now available for chromebooks... https://www.minecraft.net/en-us/article/minecraft-launching-chromebook

**Comment by mio-19** [comment]
> so I managed to get minecraft to run but there's some graphical glitches which make the game unplayable? ![image](https://user-images.githubusercontent.com/100154768/231041255-736265b8-2298-4d1e-b13d-1b420994deb6.png)

Minecraft 1.16.5 does run fine on my aarch64 machine

**Comment by mio-19** [comment]
@satmandu I mean on crostini, not chromebrew

**Comment by satmandu** [comment]
@mio-19 Thanks for that info. Does the official Minecraft version work too? i.e., https://play.google.com/store/apps/details?id=com.mojang.minecraftpe&pli=1 ?

**Comment by mio-19** [comment]
> @mio-19 Thanks for that info. Does the official Minecraft version work too? i.e., https://play.google.com/store/apps/details?id=com.mojang.minecraftpe&pli=1 ?

Yes. The android version works well on Chromebook
