### ISSUE TITLE
nano gives segmentation fault

### ISSUE THREAD

**Issue by s0urce-c0de** [chromebrew/chromebrew#8177]
**Describe the bug**
After I removed and installed gcc a few times, I got gcc to work so the `-s` and `-S` flags worked, but now `nano` doesn't work with sudo, and I am trying to shortcut python to run from crosh by editing  `/usr/share/crosh/dev.d/50-crosh.sh`.

**To Reproduce**

1. I executed this command:

      ```shell
      sudo nano /usr/share/crosh/dev.d/50-crosh.sh
      ```

      Output:

      ```
      chronos@localhost / $ sudo nano /usr/share/crosh/dev.d/50-crosh.sh
      Password: 
      Segmentation fault
      chronos@localhost / $
      ```

**Expected behavior**
I expect it to open that nano editor with superuser permisions
**Screenshots**
![image](https://user-images.githubusercontent.com/122696391/231662738-b0d0f38c-aee4-42a0-aea5-a0b0ca344a84.png)

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.32.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 6ed4eb2 `meson => 1.0.1 (#8064) (4 weeks ago)`

- OS variant: `Chrome OS`
- OS version: `hatch-release/R114-15395.0.0`
- OS channel: `canary-channel`

</details>
***

**Additional context**
I am aware that I am in canary channel, but it requires a powerwash to remove, not what I want.

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by satmandu** [comment]
Does a `crew update ; crew upgrade` help?

**Comment by satmandu** [comment]
If that doesn't help you're just going to have to wait for stable to catch up. None of our machines are on canary...

**Comment by s0urce-c0de** [comment]
It won't fix that, but I got sommelier to work and now firefox will launch, but nano with super-user perms doesn't work 😢 (still), but now my touchpad doesn't work either. Now to touchscreen and tab-key😢. For some reason it gives a crostini icon launcher in the hotbar for firefox ?? What the heck is that supposed to mean.

**Comment by s0urce-c0de** [comment]
also github_cli package is outdated :(

**Comment by satmandu** [comment]
Updating both github_cli and nano...

**Comment by satmandu** [comment]
See if https://github.com/chromebrew/chromebrew/pull/8189 helps?

**Comment by s0urce-c0de** [comment]
Thanks, it worked.  It was very outdated. Sommelier and nano dont work if outdated. I wonder if you can automatically detect the version, and the urls should use 
```ruby
source_url "http://www.foo.bar/foo.bar.#{version}.tgz"
```
to decrease changes.

**Comment by satmandu** [comment]
@s0urce-c0de We do that sometimes... it depends upon how the source is released, how it is hosted, and whether we want to be using git tags or version numbers for source...

There's also an ur-question about how to check for new versions.

However, I think the fix was not building nano as a static binary...

**Comment by s0urce-c0de** [comment]
wdym? i'm not very experienced with packages and package hosting, etc
