### ISSUE TITLE
crew-launcher fails with RuntimeError

### ISSUE THREAD

**Issue by Vicky-Boi** [chromebrew/chromebrew#8244]
Whenever I try to add app shortcuts using crew-launcher, it always returns a RuntimeError. I've been digging through the internet for a while now and I cannot find anyone else with the same error or anything that could help me.

I've completely wiped chromebrew from my chromebook and reinstalled chromebrew, crew-launcher and firefox. Even after that, still no luck.

```shell
chronos@localhost / $ crew-launcher new firefox
crew-launcher server daemon with PID 19472 stopped.
identify identify: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found") [No such file or directory].
identify identify: Request did not return an image.
convert convert: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found") [No such file or directory].
/usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `system': Command failed with exit 1: convert (RuntimeError)
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `convert_img'
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:39:in `find'
        from /usr/local/bin/crew-launcher:73:in `CreateProfile'
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'
```

<details><summary>System info</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.14`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.32.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 6069a42 `Telegram 4.6.5 => 4.8.1 (#8241) (2 days ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R112-15359.58.0`
- OS channel: `stable-channel`

</details>

**Comment by Vicky-Boi** [comment]
Just powerwashed my chromebook and just remembered this thing existed. I installed chromebrew, firefox and crew-launcher and it still gives the same error.

**Comment by satmandu** [comment]
@supechicken any thoughts on this?

**Comment by supechicken** [comment]
Seems that the `graphicsmagick` package is broken, maybe try building it from source:
```
crew reinstall -s graphicsmagick
```

By the way many functions in `crew-launcher` are broken currently, I am ready to rebuild it from scratch...

**Comment by satmandu** [comment]
Meanwhile I'll work on getting `graphicsmagick` updated &  built.
