### ISSUE TITLE
/usr/local/bin/crew:1350:in `system': Command failed with exit 1: rsync (RuntimeError) making it impossible to install any package 

### ISSUE THREAD

**Issue by sparklescrewdriver** [chromebrew/chromebrew#8321]
This occurs when i try to install or reinstall a package that is available on chromebrew 

I have attempted to reinstall it (chromebrew) this output is still displayed 

**rsync: ACLs are not supported on this client
rsync error: syntax or usage error (code 1) at main.c(1791) [client=3.2.7]
/usr/local/bin/crew:1350:in `system': Command failed with exit 1: rsync (RuntimeError)
        from /usr/local/bin/crew:1350:in `install_files'
        from /usr/local/bin/crew:1392:in `block in install_package'
        from /usr/local/bin/crew:1361:in `chdir'
        from /usr/local/bin/crew:1361:in `install_package'
        from /usr/local/bin/crew:1546:in `install'
        from /usr/local/bin/crew:1489:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1486:in `each'
        from /usr/local/bin/crew:1486:in `resolve_dependencies'
        from /usr/local/bin/crew:1410:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1902:in `block in reinstall_command'
        from /usr/local/bin/crew:1894:in `each'
        from /usr/local/bin/crew:1894:in `reinstall_command'
        from /usr/local/bin/crew:1993:in `<main>'**

**Comment by sparklescrewdriver** [comment]
Have tried fixes suggested in

[This GitHub issue post but it didn't work](https://github.com/chromebrew/chromebrew/issues/8235)

**Comment by sparklescrewdriver** [comment]
it appers to be an issue where it is only trying to excute a operation form /usr/local/bin but i have no idea how to fix it does anyone have any recommendations

**Comment by satmandu** [comment]
What does `which rsync` give you?

Does `crew reinstall rsync` help?

**Comment by satmandu** [comment]
The rsync version reported is older than the version crew uses... so I suspect this is due to the system rsync version not being compiled with acl support. Let us see if we can handle that situation...

**Comment by sparklescrewdriver** [comment]
for `which rysnc`  gives this output which: no rsync in (/usr/local/bin:/usr/bin:/bin:/opt/bin)  

now for the second command i get: `bash: crew: command not found`
wich is odd so i going to try and reinstall it like in the intial setup command to see if that fixes it

**Comment by satmandu** [comment]
I've added code to handle older rsync builds not working... so hopefully that helps.

**Comment by satmandu** [comment]
Yes, the reinstall should have installed the newer rsync, built with ACL support, thus avoiding the problem.

The update to `crew` should handle updating from a much older install of Chromebrew...
