### ISSUE TITLE
Apt

### ISSUE THREAD

**Issue by Franceschinie** [chromebrew/chromebrew#8481]
With this project https://github.com/wh5a/uoc
We could port apt on chromebrew?

**Comment by satmandu** [comment]
That's what crouton already does:

https://github.com/dnschneid/crouton

**Comment by Franceschinie** [comment]
But crouton use virtualization isn't a build in package manager

**Comment by satmandu** [comment]
Crouton uses a chroot. It does not use virtualization.

You won't be able to use regular debian or Ubuntu deb packages without a chroot for the most part on Chromebrew, because you're going to run into glibc incompatibilities.
