### ISSUE TITLE
🐞 Chromebrew install fails. (Chrome os 116)

### ISSUE THREAD

**Issue by sea768** [chromebrew/chromebrew#8635]
**Describe the bug**

Chromebrew install fails with the error "Your device is not supported by Chromebrew yet, installing as armv7l." and then exits out to crosh
**To Reproduce**

1. I executed this command:

      ```shell
      chronos@juniper-rev4 / $ exec bash --init-file <(curl -Ls git.io/vddgY)

      ```

      Output:

Welcome to Chromebrew!
Please enter the developer mode password
Password: 
Your device is not supported by Chromebrew yet, installing as armv7l.

**Expected behavior**
Chromebrew installs correctly
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
bash: crew: command not found
***

**Additional context**
If my memory serves correctly, chromebrew installed correctly in ~2021 on the same chromebook

**Comment by satmandu** [comment]
What does `exec bash --init-file -x <(curl -Ls git.io/vddgY)` give you?

**Comment by sea768** [comment]
![Screenshot 2023-09-11 5 24 40 PM](https://github.com/chromebrew/chromebrew/assets/108390196/377f268c-d216-4c34-9c68-05f6e2c66037)
Same output.

**Comment by satmandu** [comment]
Try this:

```
cd /usr/local
curl -OLf https://github.com/chromebrew/chromebrew/raw/master/install.sh
bash -x install.sh
```

**Comment by supechicken** [comment]
I think the problem is in `install.sh`, the current logic will end the script when aarch64 userspace is detected (is it an expected result?):
https://github.com/chromebrew/chromebrew/blob/7bc8272d74270f875abbab51016aa68271ace170/install.sh#L105-L108

**Comment by satmandu** [comment]
We definitely want that code not to exit out...

Please see if this older installer works:
```bash
cd /usr/local
curl -OLf https://github.com/chromebrew/chromebrew/raw/f31d76c3eb23934dae4adf9e54fcc89c0d73c35b/install.sh
bash install.sh
```

**Comment by satmandu** [comment]
@Zopolis4 Looks like this is something your refactor broke?

**Comment by satmandu** [comment]
Actually, this would be the better installer to try:

```bash
cd /usr/local
curl -OLf https://github.com/chromebrew/chromebrew/raw/15ce1cc93b61baf503c6723adfc46f83d06fe7b3/install.sh
bash install.sh
```
