### ISSUE TITLE
🐞 Bug GParted gives errors and cannot be resized properly, also the entire UI doesn't load correctly

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#8687]
**Describe the bug**
GParted gives errors and cannot be resized properly, also the entire UI doesn't load correctly

**To Reproduce**

1. I executed this command:

      ```shell
      # gparted
      ```

      Output:

      https://pastebin.com/3WQ654gA

**Expected behavior**
GParted to work like it should on Linux

**Screenshots**
![image](https://github.com/chromebrew/chromebrew/assets/67353322/ee8c6886-def1-4aa4-9fd3-1dbc24cd85ef)
![image](https://github.com/chromebrew/chromebrew/assets/67353322/3ed16acf-9797-4bcd-8001-5c8d9e3d6c8f)

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
chronos@sycamore-rev5 / $ crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `aarch64` (`aarch64`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.35.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: a8d80308 `gtk4 => 4.13.0 (#8671) (4 days ago)`

- OS variant: `Chrome OS`
- OS version: `hana-release/R116-15509.72.0`
- OS channel: `stable-channel`

</details>
chronos@sycamore-rev5 / $ 
***

**Additional context**
None

What I think needs to be done:

      - Not sure

**Comment by satmandu** [comment]
This could be a compositor issue.


Can you try setting `export GDK_BACKEND=X11` and if that doesn't work `export GDK_BACKEND=wayland` to see if that makes a difference?

**Comment by VenomousSteam81** [comment]
> This could be a compositor issue.
> 
> Can you try setting `export GDK_BACKEND=X11` and if that doesn't work `export GDK_BACKEND=wayland` to see if that makes a difference?

Yes, I can.

**Comment by VenomousSteam81** [comment]
`export GDK_BACKEND=X11` didn't work but `export GDK_BACKEND=wayland` did. Thank you!
