### ISSUE TITLE
Failed to install chromebrew - py3_pyparsing checksum mismatch

### ISSUE THREAD

**Issue by Lolbird123** [chromebrew/chromebrew#8731]
**Describe the bug**
While attempting to install chromebrew, the package py3_pyparsing could not be installed due to a checksum mismatch.

**To Reproduce**

1. I executed this command:

      ```shell
      $ exec bash --init-file <(curl -Ls git.io/vddgY)
      ```

      Output:

      ```
      ...
      py3_pyparsing: The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions.
      Precompiled binary available, downloading...
      Checksum mismatch :/ Try again?
      Filename: py3_pyparsing-3.0.9-py3.11-chromeos-x86_64.tar.zst
      Expected checksum (SHA256): ed9b21c9b56086df2f7d8f31c3b6b7c5c9b2a6669140f2ef30c7c644c3334f79
      Calculated checksum (SHA256): db2e3cb634d5eae2e7b988a27b603d2a121267306fe521814736f47a3f970cbd
      ```

**Expected behavior**
Cromebrew successfully installs

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**
could not install crew, so:
***
chronos@treeya-rev6 ~ $ uname -a
Linux localhost 5.10.188-23327-g2d8cd0ea9c9a #1 SMP PREEMPT Wed Sep 27 18:29:44 PDT 2023 x86_64 AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G AuthenticAMD GNU/Linux
chronos@treeya-rev6 ~ $ cat /etc/os-release
NAME=Chrome OS
ID_LIKE=chromiumos
GOOGLE_CRASH_ID=ChromeOS
ID=chromeos
HOME_URL=https ://www.chromium.org/chromium-os
BUG_REPORT_URL=https ://crbug.com/new
VERSION=117
VERSION_ID=117
BUILD_ID=15572.57.0
***

**Comment by Kalion2000** [comment]
Its probably because of internet issues so you just have to rerun the script to install chromebrew, at least thats what i think

**Comment by satmandu** [comment]
It is possible I screwed this up while updating the python 3.12 PR!

Let me try to get this resolved ASAP...
