### ISSUE TITLE
Checksum mismatch py3_pyproject_hooks

### ISSUE THREAD

**Issue by mklocus** [chromebrew/chromebrew#8745]
**Describe the bug**
When try to install py3_pyproject_hooks i get a error "Checksum mismatch :/ Try again?"

**To Reproduce**

1. I executed this command:

      ```
      crew install py3_pyproject_hooks
      ```

      Output:

      ```
        py3_pyproject_hooks: This package contains wrappers to call hooks on build backends for pyproject.toml -based projects
        https://pyproject-hooks.readthedocs.io/
        Version: 1.0.0-py3.11
        License: MIT
        Performing pre-flight checks...
        Precompiled binary available, downloading...
        Checksum mismatch :/ Try again?
        
                              Filename: py3_pyproject_hooks-1.0.0-py3.11-chromeos-x86_64.tar.zst
            Expected checksum (SHA256): bc0168df62eb6b2c238a49bbfa289cdb1e3941648e8d6427552a9270fefc6579
          Calculated checksum (SHA256): a2cfcbc2c9b32c2d9c613c0181a3b27f8ca56c46607f70f4b8299d208f072242
      ```

**Expected behavior**
Install a package

**Environment:**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.35.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 5c6906d8 `rubocop => 1.56.4 (37 minutes ago)`

- OS variant: `Chrome OS`
- OS version: `reven-release/R116-15509.81.0`
- OS channel: `stable-channel`

</details>
***

**Comment by mklocus** [comment]
Hi, probably its a bigger problem. I wanted to install keepassxc, and i get two errors with this. Now I get new.
Mayby its possible to check this to keepassxc?
![image](https://github.com/chromebrew/chromebrew/assets/147055841/ff54f789-4c01-4faa-a643-9849cc7a3da2)

**Comment by satmandu** [comment]
There just appear to be a bunch of py3 packages which appear to have had accidental uploads of new versions, probably while I have been building the python3.12 versions...
Let me fix that for you too...

**Comment by mklocus** [comment]
![image](https://github.com/chromebrew/chromebrew/assets/147055841/ae4f10f2-cb60-4c65-aff8-8bdadf5904fd)

I still have this

Btw. Thanks a lot

**Comment by satmandu** [comment]
Try that one more time? (I just updated it.) You also might want the keepassxc package in: https://github.com/chromebrew/chromebrew/pull/8747

**Comment by mklocus** [comment]
Its works!, Thanks
