### ISSUE TITLE
🐞 Bug latest ChromeOS versions block sudo in Crosh terminal, you have to go to vty2 and once crew is installed there you can't source the .bashrc because it utilizes sudo somewhere in the chain

### ISSUE THREAD

**Issue by espoelstra** [chromebrew/chromebrew#8779]
**Describe the bug**
The latest ChromeOS versions block sudo in Crosh terminal, you have to go to vty2 to login directly as root.

Downloading crew via the pipe to bash also seems to fail, so I've had to use `cd /tmp; curl -Ls git.io/vddgY -o chromebrew.sh; sudo -u chronos bash chromebrew.sh` to grab it to a file and execute it as not setuid 0 (root) but still allow root to make changes that would have required sudo for a non-root user.

BUT once crew is installed there you can't source the .bashrc because it utilizes sudo somewhere in the chain.

I was able to temporarily set an alias for the root user of `alias crew='sudo -u chronos crew '` so that I could install things which the regular user _should_ still be able to use, but the inability to sudo directly from crosh is going to make things a PITA.

**To Reproduce**

1. I executed this command:

      ```shell
      $ cd /tmp; curl -Ls git.io/vddgY -o chromebrew.sh; bash chromebrew.sh
      ```

      Output:

      ```
      sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
      sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
      ```

**Expected behavior**

Crew probably needs to update its behavior and warn people of the temporary workarounds required to get things working.

**Workaround**
Ctrl+Alt+F2 to get to vty2, then login as `root` with no password required.

    ```shell
      $ cd /tmp; curl -Ls git.io/vddgY -o chromebrew.sh; sudo -u chronos bash chromebrew.sh
    ```

Then set an alias for the root user of `alias crew='sudo -u chronos crew '` so that you can install things which the regular user _should_ still be able to use.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.36.2`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 9972544e `Add btop package (#8778) (25 hours ago)`

- OS variant: `Chrome OS`
- OS version: `brya-release/R117-15572.63.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] Update documentation for r115+ of ChromeOS where the sudo changes have taken place.
      - [ ] Test workaround(s) to see if they can be made less painful (like not putting crew evaluation into .bashrc when chronos can't sudo anymore)

**Comment by espoelstra** [comment]
Ok, I figured out a few things now that I've done this 2-3 times in the last few days. One is the directions on the Chromebrew.github.io are slightly out of sync with the README.

I haven't been able to use this direction verbatim, I have to use the `-o chromebrew.sh` option to save it to a file first.

![image](https://github.com/chromebrew/chromebrew/assets/7798975/fb7395c5-aa61-415f-9ae5-364ad0134f24)

Vs 

This does work IF you have run the suggested setdevpasswd command and logged in as chronos with the new password.

![image](https://github.com/chromebrew/chromebrew/assets/7798975/85fc02b4-a676-40c5-b185-10617f1af938)


Specifically you really REALLY should login as root on vty2 and run `chromeos-setdevpasswd` even if you are on an older system that still supports sudo in Crosh, because while you can't perform sudo in the graphical session (via Crosh Windows or Ctrl+Alt+T) on newer ChromeOS releases setting the dev password allows you to Ctrl+Alt+F2 and login as chronos and `sudo -i` or `sudo su` to root in vty2-6 using your user's password which makes the rest of the directions still pretty much valid.

**Comment by espoelstra** [comment]
I think the Github Pages just needs updated with the prereq of running chromeos-setdevpasswd as root in vty2, and the new command, and that should cover older and newer ChromeOS releases for a while.

**Comment by satmandu** [comment]
We still need to update documentation...

**Comment by thonkinator** [comment]
so what exactly should I do to install chromebrew on these newer versions?

**Comment by espoelstra** [comment]
> so what exactly should I do to install chromebrew on these newer versions?

You need to use vty2 to log in as `root` and run `chromeos-setdevpasswd` and then `exit` or switch to another vty and login as `chronos` with the password you just set and type in the install command from the readme and it should just work because it _can_ prompt for your sudo password in the vty sessions.

**Comment by satmandu** [comment]
@supechicken is working on some software to help with the install on newer milestones...

**Comment by espoelstra** [comment]
I'll go give that a shot, I've got a few Chromebooks that I can play with and not worry about breaking any essential tools I need.

**Comment by satmandu** [comment]
Fixed by https://github.com/chromebrew/chromebrew/pull/8849, but don't do an install until #8882 is merged.
