### ISSUE TITLE
🐞 Bug Multiple binaries segfaulting on AMD StoneyRidge when ASLR is enabled.

### ISSUE THREAD

**Issue by Juma7C9** [chromebrew/chromebrew#8823]
As reported many times before, various binaries (e.g. `sed`, `bison`, `lzip`, etc.) are segfaulting on AMD StoneyRidge machines.
This seems being related to ASLR, enabled by default on ChromeOS, as disabling it the issue disappears.

Running `echo 0 | sudo tee /proc/sys/kernel/randomize_va_space` those binaries are no longer segfaulting (while they do with `1` or `2`), but obviously is it not an optimal solution from a security standpoint.

https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization

**Comment by satmandu** [comment]
Does an install succeed with that step?

**Comment by satmandu** [comment]
@uberhacker @supechicken this appears to be a workaround we could add to crew that could be invoked early in env.d and also in the installer?

**Comment by Juma7C9** [comment]
Yes, everything works as expected (as far as I was able to test), but it needs to be enabled every time an affected binary is invoked, not simply when installing the package (if I understand correctly your last comment).

**Comment by satmandu** [comment]
> Yes, everything works as expected (as far as I was able to test), but it needs to be enabled every time an affected binary is invoked, not simply when installing the package (if I understand correctly your last comment).

Ok, we can probably add that to a bash env.d file to run that when crosh is opened.

Does it get preserved across sleep cycles?

What's the best way to identify a machine as AMD from the command line? Grep inside /proc?

**Comment by supechicken** [comment]
> @uberhacker @supechicken this appears to be a workaround we could add to crew that could be invoked early in env.d and also in the installer?

I am okay with this

> What's the best way to identify a machine as AMD from the command line? Grep inside /proc?

We can check for `vendor_id` in `/proc/cpuinfo`:
```shell
grep "vendor_id       : AuthenticAMD" /proc/cpuinfo
```

**Comment by Juma7C9** [comment]
If this workaround is implemented it would be nice to inform the user and allow them to disable it when not needed anymore, as it may render the device less secure.

Also, it would be nice to find the root cause as why only some binaries have this issue (and they always crash, so it should not be a hardware bug issue as in [1]).
The closest I found as of now is this gcc bug [2], but it may well be completely unrelated. Unfortunately I have not enough C experience to debug it effectively.

[1]: https://www.reddit.com/r/Amd/comments/6ib9p2/any_updates_on_ryzen_segv_errata/
[2]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101380

**Comment by Juma7C9** [comment]
> > @uberhacker @supechicken this appears to be a workaround we could add to crew that could be invoked early in env.d and also in the installer?
> 
> I am okay with this
> 
> > What's the best way to identify a machine as AMD from the command line? Grep inside /proc?
> 
> We can check for `vendor_id` in `/proc/cpuinfo`:
> 
> ```shell
> grep "vendor_id       : AuthenticAMD" /proc/cpuinfo
> ```

I think this should not be necessary, Crew has already such a const: `CREW_IS_AMD` is `True` on AMD systems.

**Comment by Juma7C9** [comment]
By the way, compiling one of the affected packages locally (`sed`), it does not seem to segfault anymore, so I guess the culprit may be one of the enabled optimizations.

To check which it may be, can you provide me with different versions of the `sed` package compiled with some subset of optimizations enabled, like no `-O2`, disabling LTO and/or the `mold` linker (or other you may think may be relevant)?

By the way is there a way to setup Chromebrew locally, i.e. outside of a ChromeOS machine?

**Comment by supechicken** [comment]
> By the way is there a way to setup Chromebrew locally, i.e. outside of a ChromeOS machine?

Yes, @satmandu has [some ChromeOS docker images with Chromebrew preinstalled](https://hub.docker.com/r/satmandu/crewbuild) on Docker Hub, you can deploy the images there onto your machine with `docker pull`

**Comment by satmandu** [comment]
```bash
cat crewbuild-nocturne-x86_64.m117.sh
#!/bin/bash
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  SESSION_TYPE=remote/ssh
elif pstree -p | egrep --quiet --extended-regexp ".*sshd.*\($$\)"; then
  SESSION_TYPE=remote/ssh
else
  case $(ps -o comm= -p $PPID) in
    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
  esac
fi
if [ -z ${PAGER+x} ]; then
  echo "PAGER is not set."
else
  PAGER_PASSTHROUGH=-e
  PAGER_PASSTHROUGH+=" "
  PAGER_PASSTHROUGH+=CONTAINER_PAGER=${PAGER}
fi
X11+=" "
X11=-e
X11+=" "
X11+=DISPLAY=${DISPLAY:-:0.0}
X11+=" "
if ! [[ $SESSION_TYPE == remote/ssh ]] && [ -d /tmp/.X11-unix ]; then
  X11+=" -v /tmp/.X11-unix:/tmp/.X11-unix "
fi
if [ -f "$HOME"/.Xauthority ]; then
  X11+=--volume=$HOME/.Xauthority:/home/chronos/user/.Xauthority:rw
  X11+=" "
  X11+=--volume=$HOME/.Xauthority:/home/chronos/.Xauthority:rw
fi
docker pull --platform linux/amd64 satmandu/crewbuild:nocturne-x86_64.m117
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --platform linux/amd64 --rm --net=host ${PAGER_PASSTHROUGH} ${X11} -e LOCALRC="${LOCALRC}" -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-x86_64 -it satmandu/crewbuild:nocturne-x86_64.m117
```

**Comment by satmandu** [comment]
Stoney Ridge appears to be an older set of AMD hardware: https://www.cpu-world.com/Cores/Stoney_Ridge.html

Is there a good way to check for this Stoney Ridge hardware, without disabling ASLR for all AMD hardware?

**Comment by satmandu** [comment]
It looks like the ASLR bugs may be due to some of the older static musl builds, such as for lzip.

With the newer lzip build, maybe it will not be an issue?

**Comment by Juma7C9** [comment]
I don't think the issue lies (only?) in musl, as other unrelated binaries are segfaulting as well (e.g. bison, bz2, sed,...).

By the way I tried to recompile `bz2` using the docker image above (on a Intel CometLake platform), and the resulting binary works correctly on both platforms.
I may try other packages, but my theory is that this bug is caused by the build platform, which for some reason generated flawed packages (at least at the time those packages were built).

To test this, can you recompile the `bz2` package to see if it has changed since?

**Comment by Juma7C9** [comment]
Bump, pinging @supechicken @satmandu.

Can you reopen the issue, as the PR did not fix it?

**Comment by satmandu** [comment]
@Juma7C9 Does using `echo 0 | sudo tee /proc/sys/kernel/randomize_va_space` solve your problems?

**Comment by Juma7C9** [comment]
Yes, it does, but it also creates a security hole.

As I wrote in a previous message, I have a feeling that the issue does not lie within a specific package or compilation option, but simply in a faulty build environment -- possibly at the time those packages were compiled.
Otherwise I cannot explain why if I recompile those packages either locally within ChromeOS, or in the provided Docker image on a completely different system, they do not show that issue (i.e. they no longer segfault with ASLR enabled).

If you could trigger a rebuild of one of the affected packages (e.g. Bison, Bzip2, etc.) then it will be possible to check whether the issue is still present, or otherwise investigate what part of the build system is producing those issues.

**Comment by satmandu** [comment]
You could get your system loaded with ASLR disabled, and then try rebuilding packages from source, e.g. `crew reinstall -s bzip2` and see if you still get segfaults booted without ASLR disabled.

It's very hard for us to debug this when we don't have hardware to replicate this on our end.

**Comment by Juma7C9** [comment]
Yes, as I told you in https://github.com/chromebrew/chromebrew/issues/8823#issuecomment-1776824412 (the) https://github.com/chromebrew/chromebrew/issues/8823#issuecomment-1785804349 (previous) https://github.com/chromebrew/chromebrew/issues/8823#issuecomment-1793103520 (messages), rebuilding from source both *locally* and within a Docker image *on a different (Intel) machine*, they *do not segfault*.

That's why I suspect the issue does not lie with the AMD systems, but within your (previous?) build system, otherwise I cannot explain why I cannot reproduce the issue on my build environment.

I understand that you do not have the relevant hardware, that's why I am asking to send me the rebuild binaries, so I can test them and see if your build environment is still at fault.

**Comment by satmandu** [comment]
Sorry for the delay in getting back to you on this.

Are you noticing anything special about packages that work after rebuilds?

It's so weird that software is broken when built in a container by one of us, but works for you when you rebuild it.

And packages like sed were built not too far in the past...

Does any software added in recent PRS work without rebuilding?

**Comment by Juma7C9** [comment]
Sorry I wasn't able to respond you earlier.
I've updated  `bzip2` to the new (repo) version, and indeed it does not segfault anymore.

This make me wonder if there was any modification in the build toolchain in the previous months, maybe there was a package broken upstream which has been fixed in the meantime.

Trying to dig deeper, I tested some other packages to find out when the issue appeared and when it ceased to be.
The earliest package I could find with this issue is `squashfs`, built on 2021-07-24, and the latest is `sed`, built on 2023-01-09. Obviously, as I tried only a very limited subset of all the packages it is possible that there are affected packages older and newer than that, but I think that the overall period is correct.
I think packages older than those (which are very few) are not affected, e.g. `js78` (2021-04-28) is unaffected, while `js91` (2021-12-21) does segfault.
Newer packages should also be fine, as after being rebuilt `bzip2` is not segfaulting anymore.

Some affected packages I could find are:
* `squashfs` (2021-07-24)
* `js91` (2021-12-21)
* `bison` (2021-12-28)
* `strace` (2022-02-07)
* `cpio` (2022-05-31)
* `putty` (2022-08-23)
* `elinks` (2022-29-08)
* `anagram` (2022-10-11)
* `upower` (2022-11-01)
* `sed` (2023-01-09)

Also, many packages are complaining of missing libraries, i.e. they search for `somelib.so.(n)` while the environment only provides `somelib.so.(n+1)`, so maybe you missed to rebuild them when the libraries they depend upon were updated.

**Comment by satmandu** [comment]
If you would please open separate issues (doesn't have to be expansive, just point out it needs to be rebuilt because it segfaults or has a broken library dependency) for each of the packages you notice is causing problems, we can go through and systematically work on rebuilding those...

**Comment by Juma7C9** [comment]
Sounds fine to me!
Would it also be a good idea to add a disclaimer when Crew is installed on Grunt systems to report you any broken or segfaulting packages, as I don't think I will be able to find them all?

**Comment by satmandu** [comment]
That's a good idea!

Do you have a good way of detecting such devices?

If so feel free to submit a PR to modify `install.sh`!

**Comment by Juma7C9** [comment]
I think the safest way is to use the `CPU Family` returned from `/proc/cpuinfo`, which is `22` for Bulldozed CPUs.
I don't know if other AMD families are affected, but as far as I know there are no Chromebooks with processors older than that, and I did not see any such report for newer ones (i.e. the Zen series).

I'll then try to concoct a warning later on, so to close the issue.

By the way, is the build infrastructure available on some repo, or is it just the Docker image?

**Comment by satmandu** [comment]
https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a

https://gist.github.com/satmandu/efb3ef644fa7f524041f189106a144da

**Comment by satmandu** [comment]
Some packages like `js91` are just not likely to get updated quickly (if at all). No other packages depend upon them, and they take days to build...

**Comment by satmandu** [comment]
FYI strace 6.6 does not build on x86_64: https://github.com/strace/strace/issues/273

**Comment by satmandu** [comment]
strace build resolved by using 4.14 headers for x86_64 build...

**Comment by Juma7C9** [comment]
The rebuilt binaries seem to work fine, I'll open some issues for the rest. Thank you!

**Comment by satmandu** [comment]
I have rebuilt/updated all packages mentioned...

**Comment by satmandu** [comment]
The fixes have been merged. Please let us know if anything else is broken?
