### ISSUE TITLE
🐞 Bug crew install from source is broken

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#8894]
```
$ crew install girara -s
girara: Girara is a library that implements a user interface that focuses on simplicity and minimalism
https://pwmt.org/projects/girara/
Version: 0.4.0
License: ZLIB
Performing pre-flight checks...
Package girara already installed, skipping...
Girara installed!
```

**Comment by uberhacker** [comment]
Not a but if using `crew reinstall girara -s`.

**Comment by satmandu** [comment]
Not being able to install from source is still a bug!

**Comment by uberhacker** [comment]
I think the logic to determine if the package is already installed precedes the decision to install from binary or source.

**Comment by supechicken** [comment]
Huh? It is expected and shouldn't be considered a bug. (same behavior after #8895...)

> Not being able to install from source is still a bug!

@uberhacker is trying to install an already installed package, `crew` will block it of course...
