### ISSUE TITLE
[Package request] Add llvm-bolt

### ISSUE THREAD

**Issue by zamazan4ik** [chromebrew/chromebrew#8940]
[LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) is a Post Link Optimizer that helps with optimizing applications (by reducing I-cache misses). Having LLVM BOLT in the Chrombrew repository will allow BOLT to be used for other Chromebrew packages as an additional optimization step, and allow end-users to optimize their apps.

LLVM BOLT is a part of LLVM and it can be enabled by enabling the BOLT project during the LLVM configuration. Other OSes like Fedora already enabled building `llvm-bolt` packages.

**Comment by satmandu** [comment]
FYI Bolt only currently works for X86_64 and ARM64 binaries. Since we aren't building ARM64 binaries yet, this will only help with X86_64 builds.

**Comment by satmandu** [comment]
Having said that, I'll add it to the builds for x86_64 when we next rebuild llvm...

**Comment by satmandu** [comment]
I have gotten llvm-bolt to be built on x86_64. It will be in the upcoming PR for llvm 17.0.5 when the other architecture builds finish...
