### ISSUE TITLE
Bug, support for newbies.

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [chromebrew/chromebrew#8967]
**Describe the bug**
bug:  It causes the use of "dev_install" to become unusable completely (Aarch64 but for some reason installs asArmv7*)
support question: I've installed everything I need for the gnome-desktop from what was available. But for the life of me I can't figure out how to use it in any way at all no matter where I look. Mate desktop stuff doesn't install because it needs a non-existent package to build it. Would anyone, absolutely anyone know how to use the Gnome Desktop?

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
- Architecture: `aarch64` (`aarch64`)
- Processor vendor: `ARM`
- User space: `32-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.39.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: b26e35e0 `Github_desktop 2.9.6-RC => 3.3.3-RC2 (#8966) (4 hours ago)`

- OS variant: `Chrome OS`
- OS version: `jacuzzi-release/R119-15633.44.0`
- OS channel: `stable-channel`
***

What I think needs to be done:

Entirely Unsure.

**Comment by satmandu** [comment]
Try again. Google broke Chromebrew with M118, and fixed it with M121.

**Comment by Dae-Hang-Sook** [comment]
> Try again. Google broke Chromebrew with M118, and fixed it with M121.

I since found out the dev_install problem. But never ever figured out the desktop problem.
