### ISSUE TITLE
🐞 Bug [aarch64] MESA-LOADER: failed to open zink

### ISSUE THREAD

**Issue by AsessionGuy** [chromebrew/chromebrew#9131]
**Describe the bug**
I installed chromebrew and then mpv, weston, gimp and gnome-terminal.
When I try to open a video or stream mpv crashes. Gimp's splashscreen pops up but when it finishes loading the app closes. gnome-terminal prints the same error as mpv and crashes. weston launches fine but opening applications from its console delivers the same errors.

**To Reproduce**

1. I executed this command:

      ```shell
      # mpv ./sample-5s.mp4
      ```

      Output:

      ```
      # libEGL warning: MESA-LOADER: failed to open zink: /usr/local/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/loca/lib/dri, suffix _dri)
      # failed to load driver: zink
      ```

**Expected behavior**
GUI Applications should launch

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`aarch64`)
- Processor vendor: ARM
- User space: `32-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.40.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 1c1549543 `Add vice package (#9130) (4 hours ago)`

- OS variant: `Chrome OS`
- OS version: `kukui-release/R119-15633.69.0`
- OS channel: `stable-channel`

</details> 
***

**Comment by Zopolis4** [comment]
This may have something to do with https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27478

(Not sure, just came across this while looking through mesa MRs)

**Comment by Zopolis4** [comment]
Upstream PR merged, this should be fixed once the fix makes its way to a release and we upgrade.

**Comment by Zopolis4** [comment]
The fix should now be available as https://gitlab.freedesktop.org/mesa/mesa/-/commit/02ab51a61eed8fed5940cf88df71f536ce14f0e2 via #9839. If the problem persists after upgrading, let me know.

**Comment by AsessionGuy** [comment]
Currently I don't have enough time to test this out but once I can, I'll let you know :)
