### ISSUE TITLE
display sleeps while mpv plays video

### ISSUE THREAD

**Issue by digby5** [chromebrew/chromebrew#9135]
**Describe the bug**
chromebook goes to sleep while mpv is playing video. guess mpv doesnt tell chromeos not to go to sleep like the built-in video player
**To Reproduce**
play video, wait 3-5mins, and chromebook is asleep
1. I executed this command:

      ```shell
      # mpv
      ```

      Output:

      ```
      # output of your command
      ```

**Expected behavior**
not for the device to go to sleep

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
***

**Additional context**

What I think needs to be done:

      - [ ] chromebook not to fall asleep
      - [ ] step two

**Comment by satmandu** [comment]
Short of a mouse jiggler command I'm not actually sure how to keep newer versions of ChromeOS from sleeping at all...

Feel free to debug the issue and let us know if you can figure out what a video player does differently to keep the device from sleeping.
