### ISSUE TITLE
🐞 Bug: Can't run "meld" due to wrong symlinks for Python 3.12.1

### ISSUE THREAD

**Issue by AltoRetrato** [chromebrew/chromebrew#9137]
**Describe the bug**

Programs using a shebang `#!/usr/bin/python3`, like `meld`, can't find Python3 due to wrong symlinks:
 - `/usr/bin/python3` is linked to 
 - `/usr/local/usr/bin/python3`, which doesn't exist, since the binary is actually at
 - `/usr/local/bin/python3`
```
$ meld
-bash: /usr/local/bin/meld: /usr/bin/python3: bad interpreter: No such file or directory

$ whereis python3
python3: /usr/bin/python3 /usr/local/bin/python3

$ ls -l /usr/bin/python3
lrwxrwxrwx. 1 root root 26 Jul 18  2022 /usr/bin/python3 -> /usr/local/usr/bin/python3

$ ls -l /usr/local/bin/python*
lrwxrwxrwx. 1 chronos chronos    7 Dec  8 12:39 /usr/local/bin/python -> python3
lrwxrwxrwx. 1 chronos chronos   10 Dec  8 12:39 /usr/local/bin/python3 -> python3.12
-rwxr-xr-x. 1 chronos chronos 5248 Dec  8 12:39 /usr/local/bin/python3.12
```

**To Reproduce**

1. Install Chromebrew
2. Invoke `/usr/bin/python3` (with full path), or install (`crew install meld`) and run `meld`

**Expected behavior**

Have any program using a shebang `#!/usr/bin/python3` being able to run Python3 at `/usr/local/bin/python3`.

**Environment**

<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.40.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 04aae3d38 `Telegram 4.13.0 => 4.13.1 (#9132) (2 days ago)`

- OS variant: `Chrome OS`
- OS version: `cyan-release/R103-14816.131.0`
- OS channel: `stable-channel`
</details>

**Additional context**

I installed Chromebrew 1.40.5 in an Acer R11 Chromebook (Cyan / Braswell), ChromeOS Version 103.0.5060.132 (Official Build) (64-bit).

I don't know if this `/usr/bin/python -> /usr/local/usr/bin/python` symbolic link is present in all ChromeOS versions, but I think the `python3` package could, during installation, try to find that link, and if it exists, it could:
 - create the folder `/usr/local/usr/bin/`
 - create a symlink `/usr/local/usr/bin/python3 -> /usr/local/bin/python3` (`ln -s /usr/local/bin/python3 /usr/local/usr/bin/python3`)

Alternatively, `/usr/local/bin/meld` (and any other programs using the same shebang) could be patched to use `/usr/local/bin/python3` instead.

**Comment by AltoRetrato** [comment]
Another issue with Meld - even though I have Python 3.12, Meld files are installed in the path of Python 3.10.

```
$ meld
Traceback (most recent call last):
  File "/usr/local/bin/meld", line 96, in <module>
    import meld.conf  # noqa: E402
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'meld'

$ ls -l /usr/local/lib/ | grep python
drwxr-xr-x. 3 chronos chronos   4096 Jan  1 12:36 python3.10
drwxr-xr-x. 3 chronos chronos   4096 Jan  1 12:21 python3.12

$ ls -l /usr/local/lib/python3.10/site-packages/
drwxr-xr-x. 5 chronos chronos 4096 Jan  1 12:36 meld
```

**Comment by satmandu** [comment]
Please see if https://github.com/chromebrew/chromebrew/pull/9293 helps.
