### ISSUE TITLE
🐞 Bug - Having issues installing ruby_rubocop

### ISSUE THREAD

**Issue by UCYT5040** [chromebrew/chromebrew#9172]
**Describe the bug**
Trying to install package `minecraft`, which is resulting in this error

**To Reproduce**
Run either of the below commands

1. I executed these commands:

      ```shell
      crew install minecraft
      crew install ruby_rubocop
      crew install -s ruby_rubocop
      crew install -S ruby_rubocop
      ```

      Output (for both commands):

      ```
      Checksum mismatch. Try again :/?
      ```

**Expected behavior**
The package should install

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

No idea how to copy text from the console. Using ctrl+alt+f3

**Additional context**

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by satmandu** [comment]
@uberhacker did we change the rubucop yaml file recently?

**Comment by satmandu** [comment]
> @uberhacker did we change the rubucop yaml file recently?

Also, we should maybe add some code to the ruby_rubocop.rb file to complain if the checksum doesn't match on `crew update`.

**Comment by uberhacker** [comment]
> > @uberhacker did we change the rubucop yaml file recently?
> 
> Also, we should maybe add some code to the ruby_rubocop.rb file to complain if the checksum doesn't match on `crew update`.

Latest change from @Zopolis4.  https://github.com/chromebrew/chromebrew/pull/9152/files

**Comment by uberhacker** [comment]
> > @uberhacker did we change the rubucop yaml file recently?
> 
> Also, we should maybe add some code to the ruby_rubocop.rb file to complain if the checksum doesn't match on `crew update`.

How about `source_url 'SKIP'` and in the `def self.build` section generate the file contents?

**Comment by UCYT5040** [comment]
Hello, just ran `crew update` and `crew upgrade`.
