### ISSUE TITLE
📖 Suggestion: add a wiki page about Docker images

### ISSUE THREAD

**Issue by AltoRetrato** [chromebrew/chromebrew#9174]
Hi!

It seems that, because my Chromebook (Cyan) has reached its EOL, I'm having issues with Chromebrew compiled packages requiring a more recent version of libc (see #9136). I could try building packages from source, but doing that for many large packages on a puny chromebook is a daunting task that would take forever.

But I found out @satmandu 's [chromeos_docker28](https://gist.github.com/satmandu/efb3ef644fa7f524041f189106a144da) script to build a Docker image using a ChromeOS recovery file. It seems that I can use it to build chromebrew packages on my desktop PC and bring them later to the Chromebook... is that correct?

I'm still in the process of building the Docker image, so I'm not even sure if I'll get that step to work at all! I don't know about the other steps as well, but I'm sure other people would be interested in trying to do the same to be able to run more chromebrew packages on their systems.

**I thought about creating a wiki page about the script** to help others, but it might be redundant, incomplete or even inaccurate, so first I'd like to ask if someone else have more info to contribute to such page, and if @satmandu and others in the project agree about creating such wiki page. I'd be glad to format and test that information, maybe even include a list of publicly available Docker images to make it easier for most users to just run pre-built images instead of building their own.

All your suggestions and input are welcome!

Thanks!

**Comment by satmandu** [comment]
My docker image scripts for running ChromeOS based Chromebrew containers are here:

https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a

**Comment by AltoRetrato** [comment]
> My docker image scripts for running ChromeOS based Chromebrew containers are here:
> 
> https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a

Thanks! I have found them before (and [their respective images](https://hub.docker.com/r/satmandu/crewbuild/tags)), but they are limited to only a few devices:
- [crewbuild-alex-i686.m58.sh](https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a#file-crewbuild-alex-i686-m58-sh)
- [crewbuild-fievel-armv7l.m91.sh](https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a#file-crewbuild-fievel-armv7l-m91-sh)
- [crewbuild-nocturne-x86_64.m120.sh](https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a#file-crewbuild-nocturne-x86_64-m120-sh)
- [crewbuild-nocturne-x86_64.m90.sh](https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a#file-crewbuild-nocturne-x86_64-m90-sh)
- [crewbuild-strongbad-armv7l.m120.sh](https://gist.github.com/satmandu/d8365cb70b899901a05290d31c04909a#file-crewbuild-strongbad-armv7l-m120-sh)

Do you think we can use [chromeos_docker28](https://gist.github.com/satmandu/efb3ef644fa7f524041f189106a144da) to build Docker images for all Chromebooks devices? I'm currently having issues building for Cyan on Ubuntu.

```
docker login -u altoretrato
export REPOSITORY="altoretrato"
./chromeos_docker28.sh https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14816.131.0_cyan_recovery_stable-channel_mp-v3.bin.zip cyan 103 x86_64
```
```
[...]
This is the .bashrc
This is the .bashrc
CONTAINER_ARCH: x86-64
PASSTHROUGH_ARCH: x86_64
This is the .bash_profile
This is the .bashrc
fatal: not a git repository (or any of the parent directories): .git 
fatal: not a git repository (or any of the parent directories): .git 
fatal: not a git repository (or any of the parent directories): .git 
fatal: not a git repository (or any of the parent directories): .git 
/usr/local/bin/crew:647:in `system': Command failed with exit 128: git (RuntimeError)
           from /usr/local/bin/crew:647:in `block in update'
           from /usr/local/bin/crew:642:in `chdir'
           from /usr/local/bin/crew:642:in `update'
           from /usr/local/bin/crew:2028:in `update_command'
           from /usr/local/bin/crew:2046:in `<main>'
```

**Comment by satmandu** [comment]
> 
> Do you think we can use [chromeos_docker28](https://gist.github.com/satmandu/efb3ef644fa7f524041f189106a144da) to build Docker images for all Chromebooks devices? I'm currently having issues building for Cyan on Ubuntu.
> 
> ```
> docker login -u altoretrato
> export REPOSITORY="altoretrato"
> ./chromeos_docker28.sh https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14816.131.0_cyan_recovery_stable-channel_mp-v3.bin.zip cyan 103 x86_64
> ```
> ```
> [...]
> This is the .bashrc
> This is the .bashrc
> CONTAINER_ARCH: x86-64
> PASSTHROUGH_ARCH: x86_64
> This is the .bash_profile
> This is the .bashrc
> fatal: not a git repository (or any of the parent directories): .git 
> fatal: not a git repository (or any of the parent directories): .git 
> fatal: not a git repository (or any of the parent directories): .git 
> fatal: not a git repository (or any of the parent directories): .git 
> /usr/local/bin/crew:647:in `system': Command failed with exit 128: git (RuntimeError)
>            from /usr/local/bin/crew:647:in `block in update'
>            from /usr/local/bin/crew:642:in `chdir'
>            from /usr/local/bin/crew:642:in `update'
>            from /usr/local/bin/crew:2028:in `update_command'
>            from /usr/local/bin/crew:2046:in `<main>'
> ```
> 

Hmm. I haven't tested it on M103 in a while.

Maybe invoke the script with `bash -x ./chromeos_docker28.sh` to see what's going on?

You can also create a x86_64 subfolder, and put install.sh into there named install.sh.test to have the chromeos_docker28 use that... And then you can play with that install.sh.test script (add `set -x`, etc) to see what's going on...

**Comment by Zopolis4** [comment]
I'm working on revamping @satmandu's script over at [zopolis4/chromeos-docker](https://github.com/Zopolis4/chromeos-docker), and I'm also encountering the `fatal: not a git repository (or any of the parent directories): .git` issue.

**Comment by Zopolis4** [comment]
I'm working on revamping @satmandu's script over at [zopolis4/chromeos-docker](https://github.com/Zopolis4/chromeos-docker), and I'm also encountering the `fatal: not a git repository (or any of the parent directories): .git` issue.

**Comment by AltoRetrato** [comment]
> ```
> docker run --platform linux/amd64 --rm -it zopolis4/crewbuild:cyan.m103 /bin/bash
> ```
> 
> should have what you're looking for

Awesome! 😄 Thank you so much! I'm already running it! ❤️ 

Now all I need to know is how can I transfer the packages from the container to the Chromebook. Any tips?

**Comment by Zopolis4** [comment]
something like so:
```
docker run --platform linux/amd64 -v $(pwd)/pkg_cache:/usr/local/tmp/packages --rm -it zopolis4/crewbuild:cyan.m103 /bin/bash
# once in the container
cd /usr/local/tmp/packages
crew build <package>
```
the built package files should appear in a `pkg_cache` folder in the directory where you ran the docker command

**Comment by AltoRetrato** [comment]
Thanks again!

And finally... what would it take for Chromebrew to support older ChromeOS versions OOTB, so `crew` could install binaries compatible with the installed libc version?

**Comment by Zopolis4** [comment]
You'd have to ask satmandu on that one, he knows the most about the way we handle glibc.  I've got plans to look into this, but it may be quite some time before I get around to those.
