### ISSUE TITLE
🐞 Bug: Installation doesn't work at all, nothing comes up.

### ISSUE THREAD

**Issue by grumpyman12601** [chromebrew/chromebrew#9204]
**Describe the bug**
When running the chromebrew setup script, I am left with a blank line, no installation menu or anything. It stays on this line for about a minute before cancelling and going to the next

**To Reproduce**

1. I executed this command:

      ```shell
      # exec bash --init-file <(curl -Ls git.io/vddgY)

      ```

      Output:

      ```
      # 
      ```

**Expected behavior**
I expected the installation to proceed, or have an error, but nothing. This could be a connection issue, but I doubt it.

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
-bash: crew: command not found
***

**Additional context**

What I think needs to be done:

      - [ ] I think that it might be the way my device is running, I have been through many resets and recoveries, if this continues, I will disable and re-enable dev mode and factory reset the device.
      - [ ] Honestly don't have a lot to go off of, if there's an error log in the files somewhere I could check that, but I am not sure.

**Comment by cbellosoto** [comment]
How did you solve it?

**Comment by grumpyman12601** [comment]
I fixed what I misspelled lol
