### ISSUE TITLE
Cannot run flatpak apps🐞 Bug

### ISSUE THREAD

**Issue by NishantMajumdar** [chromebrew/chromebrew#9207]
**Describe the bug**
Flatpak cannot run any applications

**To Reproduce**
`$ flatpak run x.y.z`

Output:

 `ldconfig: /usr/lib/x86_64-linux-gnu/openh264/extra/libopenh264-2.2.0-linux64.6.so.bz2 is not an ELF file - it has the wrong magic bytes at the start.
`
`F: Not replacing "/usr/local/.config/.local/share/flatpak" with tmpfs: Path "/usr" is reserved by Flatpak`
`F: Can't find a11y bus: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.a11y.Bus received signal 5
bwrap: Failed to mount tmpfs: Operation not permitted`
    

**Expected behavior**
It should work

**Comment by satmandu** [comment]
I am open to assistance in helping fix this... there are a BUNCH of security settings on ChromeOS which keep this from working at the moment...

**Comment by NishantMajumdar** [comment]
> I am open to assistance in helping fix this... there are a BUNCH of security settings on ChromeOS which keep this from working at the moment...

Why cant we run a proper WM ?

**Comment by Ansh113130** [comment]
you can downgrade chrome os

**Comment by yeesterPlus** [comment]
mine just says that ruby is not found in the enviroment variables
