### ISSUE TITLE
Sommelier not starting on chromeos 121 stable🐞 Bug

### ISSUE THREAD

**Issue by lavilao** [chromebrew/chromebrew#9296]
**Describe the bug**
Sommelier does not start after upgrading to 121 on clean install.

**To Reproduce**

1. I executed this command:

      ```shell
      # startsommelier
      ```

      Output:

      ```
      # XDG_RUNTIME_DIR is invalid
      # failed to create display: no such file or directory
      # some sommelier processes failed to start
      ```

**Expected behavior**
sommelier should start

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /usr)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.42.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `octopus-release/R121-15699.58.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
crw also is not working right as I cant update the packages with error ```fatal: not a git repository (or any parent up to mount point /usr)``

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by uberhacker** [comment]
Are you in a bash or VT-2 session?  FWIW, sommelier works fine for me in bash on 121.

**Comment by lavilao** [comment]
yeah, I reinstalled (its still downloading, 3rd world internet) and it seems to be working. It seems like it was a download faliure on some of the packages.
