### ISSUE TITLE
Packages should not have a build dependency upon themselves.

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#9320]
The build of `linuxheaders` should not require `linuxheaders`.

```
BTW, on a tangent re package `linuxheaders`: one cannot `crew install -s linuxheaders` without an already installed linuxheaders, as the build expects headers found in the package.
```
_Originally posted by @blu in https://github.com/chromebrew/chromebrew/issues/9312#issuecomment-1939517004_

**Comment by satmandu** [comment]
Thoughts @Zopolis4 @supechicken ?

**Comment by Zopolis4** [comment]
Hard to avoid this-- for things like GCC, make, and so on. I don't see the point in going to great lengths to try and fix this for the few packages that we can fix.

**Comment by satmandu** [comment]
What's the best way to avoid this for `linuxheaders`?

**Comment by Zopolis4** [comment]
I'm not sure we can avoid it-- if it is a circular dependency, we aren't able to change that.
