### ISSUE TITLE
how to install??

### ISSUE THREAD

**Issue by dotabix** [chromebrew/chromebrew#9362]
chronos@localhost ~ $ curl -Ls git.io/vddgY | bash
/usr/local is not empty, would you like it to be cleared?
This will delete ALL files in /usr/local!
Continue?
1) Yes
2) No
#? 1) Yes
2) No
#? chronos@localhost ~ $

**Comment by satmandu** [comment]
Does running `sudo rm -rf /usr/local/*` first help?

**Comment by supechicken** [comment]
> `(termina) chronos@localhost`

You are in the Crostini VM shell (`termina`), please run the install script in ChromeOS developer mode (VT-2 shell).

> chronos@localhost ~ $ curl -Ls git.io/vddgY | bash

Please use the latest installation command mentioned in README:
```shell
exec bash --init-file <(curl -Ls git.io/vddgY)
```

**Comment by Zopolis4** [comment]
This behaviour is to be expected.
The old installation command, `curl -Ls git.io/vddgY | bash`, does not allow for user input. 
Ergo, prompting for user input to delete all files in `/usr/local` will fail. 

If you still have issues when installing via `exec bash --init-file <(curl -Ls git.io/vddgY)`, let us know and I'll reopen the issue.
