### ISSUE TITLE
Minecraft Dosent work?

### ISSUE THREAD

**Issue by Ansh113130** [chromebrew/chromebrew#9372]
I keep trying to get minecraft to install but says cant find or Download failed with error 404: Not Found?

     
 I tried both commands 

      crew install minecraft

      crew install minecraft-launcher

chronos@localhost / $ crew install minecraft-launcher
Package minecraft_launcher not found. 😞
chronos@localhost / $ crew install minecraft-launcher
Package minecraft_launcher not found. 😞
chronos@localhost / $ crew install minecraft
minecraft: A sandbox video game developed by Mojang Studios AB.
https://minecraft.net
Version: 2.2.3200
License: Mojang
Performing pre-flight checks...
The following packages also need to be installed: 
linuxheaders make shared_mime_info glib pkgconfig binutils mold findutils autoconf automake bison diffutils libtool perl_xml_parser intltool patch sed util_macros valgrind compressdoc doxygen help2man xmlcatmgr docbook_xml412 docbook_xml42 docbook_xml43 docbook_xml44 docbook_xml45 docbook_xml50 docbook_xml51 docbook_xsl docbook_xsl_nons docbook_xml py3_libxml2 itstool libxslt gtk_doc perl_locale_messages perl_text_unidecode perl_unicode_eastasianwidth texinfo cppdap jsoncpp librhash libuv cmake gawk py3_codespell ruby_mdl xdg_base ruby_rubocop ruby_yaml_lint shellcheck linter llvm17_lib ninja samurai mesonbuild libcap py3_pyelftools pax_utils gnu_time rdfind symlinks upx ruby_concurrent_ruby buildessential libmd libbsd xorg_proto libxau xcb_proto pthread_stubs libxdmcp libxcb libx11 openjdk17 cantarell_fonts adwaita_icon_theme dbus libxi libxext libxtst at_spi2_core chafa graphite libxrender lzo pixman harfbuzz freetype fontconfig cairo libusb psmisc cups fribidi libjpeg libpciaccess libdrm libglvnd libunwind libxfixes libxrandr libxshmfence libxv libxvmc libxxf86vm lm_sensors vulkan_icd_loader wayland mesa libglu freeglut jbigkit libdeflate libice libsm giflib libxt libxmu libwebp libtiff gdk_pixbuf hicolor_icon_theme libepoxy libxcomposite libxcursor libxdamage libxinerama wayland_protocols xkeyboard_config libxkbcommon libxft pango libxcvt procps wayland_info xauth xhost xcb_util xkbcomp xorg_xset xbitmaps xsetroot libxtrans libfontenc libxfont2 libxfont libxkbfile rendercheck xwayland sommelier gtk3 libcom_err libsecret
Do you agree? [Y/n] y
Proceeding...
linuxheaders: Linux headers for Chrome OS.
Precompiled binary available, downloading...
Download failed with error 404: Not Found.

That is what it says.
PS Opera dosen't work too

**Comment by Zopolis4** [comment]
So `linuxheaders` isn't working. 

Run `crew update && crew upgrade` and try again, and if that doesn't work post the output of `crew sysinfo`.

**Comment by satmandu** [comment]
@Zopolis4 @uberhacker We should probably add some code so that when crew hits an error code to please try again after running `crew update && crew upgrade`

**Comment by Ansh113130** [comment]
Thanks but ChromeOS Updated to 121😭.Now sudo dosent work in crosh and The VT-2 shell doen't work with GUI.

**Comment by Ansh113130** [comment]
![Screenshot 2024-02-27 21 28 35](https://github.com/chromebrew/chromebrew/assets/161015530/714e1c93-234d-4848-88f9-c4546730f731)
Here is img

**Comment by Bob-Teh777** [comment]
Try using crew-sudo as a sudo replacement

**Comment by SonicFlash777** [comment]
Only 4 Months ago, I have Minecraft up and running, Strange. Probably Chrome OS has new updates disabling sudo in crosh. I’ll figure this out.

**Comment by Ansh113130** [comment]
cody

**Comment by Ansh113130** [comment]
OFC it does

**Comment by SonicFlash777** [comment]
Try power washing your device after backup.It maybe a problem with the /usr folder. And probably do it with space + enter on the “OS verification is off” screen.It may reset the /usr folder.

**Comment by SonicFlash777** [comment]
I think that the `linuxheaders` link to download was changed.You should follow these instructions from an earlier comment.


> So `linuxheaders` isn't working.
> 
> Run `crew update && crew upgrade` and try again, and if that doesn't work post the output of `crew sysinfo`.

These steps are from @Zopolis4

**Comment by SonicFlash777** [comment]
> Try power washing your device after backup.It maybe a problem with the /usr folder. And probably do it with space + enter on the “OS verification is off” screen.It may reset the /usr folder.

This is probably not required, only test this once you have tried everything.

**Comment by SonicFlash777** [comment]
![IMG_0715](https://github.com/chromebrew/chromebrew/assets/149561093/ed816e68-8965-4708-89f9-d15343d495ac)
This is Minecraft on a Chromebook, only 4-5 months ago.You can see it’s using Crosh, using chromebrew files

**Comment by SonicFlash777** [comment]
> Thanks but ChromeOS Updated to 121😭.Now sudo dosent work in crosh and The VT-2 shell doen't work with GUI.

If this was the case, then chromebrew wouldn’t be working at all

**Comment by Ansh113130** [comment]
Yes but we need to find to find a way to disable flag

**Comment by SonicFlash777** [comment]
> I think that the `linuxheaders` link to download was changed.You should follow these instructions from an earlier comment.
> 
> > So `linuxheaders` isn't working.
> > Run `crew update && crew upgrade` and try again, and if that doesn't work post the output of `crew sysinfo`.
> 
> These steps are from @Zopolis4 You can also run `crew update && crew upgrade && crew install minecraft && crew sysinfo` Though this may not work, please correct me if this doesn’t have correct bash syntax.

Thy these

**Comment by SonicFlash777** [comment]
I have found a chromium os post to explain how to disable auto updates, but that is not related to this. You can try this link `https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/KuHyZfaNvGE?pli=1`

**Comment by SonicFlash777** [comment]
Are you one the dev channel?

**Comment by Bob-Teh777** [comment]
> Yes but we need to find to find a way to disable flag 

Which flag?

**Comment by Ansh113130** [comment]
There is only stable,beta and developer channels in chromeOS

**Comment by Ansh113130** [comment]
I am on stable

**Comment by Ansh113130** [comment]
![Screenshot 2024-03-04 08 03 30](https://github.com/chromebrew/chromebrew/assets/161015530/0a9b4698-38e9-4032-8104-31f15341454e)

**Comment by Ansh113130** [comment]
My chromebook is the ASUS chromebook flip C214

**Comment by Zopolis4** [comment]
The original issue here was a failure to download `linuxheaders`, which has since been fixed. For the lack of sudo caused by updating ChromeOS, `crew-sudo` should work.
