### ISSUE TITLE
Enhancement for qemu: adding "libslirp" library as a dependency 

### ISSUE THREAD

**Issue by ThrowawayAccount57** [chromebrew/chromebrew#9373]
**Describe the bug**
Qemu needs "libslirp" for the "-net user" networking option to work.  In the past "libslirp" was included with Qemu, but, to quote qemu.org: "starting with 7.2 release, qemu source does not include the slirp module anymore."

The "libslirp" library is optional - by default, if the Qemu build can't detect the presence of libslirp, then Qemu will build without "user-mode networking."

**To Reproduce**

1. I executed this command:

      ```shell
      xhost +;
      sudo qemu-system-x86_64 -net user
      ```

      Output:

      ```
      qemu-system-x86_64: -net user: network backend 'user' is not compiled into this binary
      ```

**Expected behavior**
Rather than getting the above-mentioned error, it is desirable for Qemu to launch; Qemu is expected to appear as a window that announces that it is trying to boot from "Hard Disk," and, in this case, complaining that it "could not read the boot disk."

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.43.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 4921e4656 `Add build check to Github Actions, and make getrealdeps.rb failure trigger crew error (#9319) (10 days ago)`

- OS variant: `Chrome OS`
- OS version: `eve-release/R121-15699.66.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] step one: Adding libslirp as a package to Chromebrew (https://gitlab.freedesktop.org/slirp/libslirp)
      - [ ] step two: Listing libslirp in qemu.rb as a package that Qemu "depends_on"

**Comment by satmandu** [comment]
Building qemu 8.2.1 with libslirp...

![image](https://github.com/chromebrew/chromebrew/assets/1096701/cc490f20-d5ab-492d-8ff9-c058a8fc72e6)
