### ISSUE TITLE
KVM not enabled in qemu aarch64 ChromeOS binaries

### ISSUE THREAD

**Issue by ericcurtin** [chromebrew/chromebrew#9407]
One of the advantages of using chromebrew vs the built in Debian environment is /dev/kvm is accessible. It's a pity kvm support isn't built in to the qemu binaries though.

$ qemu-system-aarch64 -accel help
Accelerators supported in QEMU binary:
tcg

**Comment by ericcurtin** [comment]
This could have been worked around by installing podman and using say Fedora binaries as an example but podman install fails.

For the record, podman would probably be easier to get working over docker, for one you don't have to worry about starting daemons.

**Comment by satmandu** [comment]
Feel free to submit a PR to reconfigure the qemu build to add kvm support...

**Comment by satmandu** [comment]
building with `--enable-kvm` doesn't resolve this on `armv7l`. Please feel free to investigate further.
