### ISSUE TITLE
🐞 problem

### ISSUE THREAD

**Issue by amogus-technologies** [chromebrew/chromebrew#9422]
**Describe the bug**
Lack of GLIBC_2.34

**To Reproduce**

1. I executed this command:

      ```shell
      $ exec bash --init-file <(curl -Ls git.io/vddgY)
      $ crew install glibc_build235
      ```
2. I executed this command:
   ```shell
   $ crew install wayland_info
   ```

   Output:

   ```shell
   Wayland_info requires glibc 2.34 and above.
   ChromeOS is currently running glibc 2.33.
   ```

**Expected behavior**
it work :)D

**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***

<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.14`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.44.4`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 3a1a8ec2a `fix crew force build (#9419) (3 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R107-15117.111.0`
- OS channel: `dev-channel`

</details>

***

**Additional context**
it no work

What I think needs to be done:

      - [ ] fix broken code
      - [ ] step two

**Comment by satmandu** [comment]
The problem is that you are on ChromeOS Milestone 107.

Update your device to the current version if it is not EOL, and you should get the current Glibc version, which is shipped with ChromeOS, not Chromebrew...

**Comment by amogus-technologies** [comment]
I can't update. It lets me download the update but when I try to reboot to apply the update it says "Chrome OS is missing or damaged"

**Comment by satmandu** [comment]
> I can't update. It lets me download the update but when I try to reboot to apply the update it says "Chrome OS is missing or damaged"

You cannot update Glibc with Chromebrew. Chromebrew only uses a Glibc that matches the system Glibc.

If your device doesn't have a system update with a newer GLIBC (from a recent ChromeOS milestone), you will have to use crouton to create a chroot with a newer GLIBC.

That's your only option if your device is EOL.

**Comment by amogus-technologies** [comment]
no like i cant update chromeos
