### ISSUE TITLE
downloading linuxheaders fails with error 404

### ISSUE THREAD

**Issue by vmhl87** [chromebrew/chromebrew#9426]
**Describe the bug**
Attempting to install linuxheaders on latest chromebrew results in an error 404.

**To Reproduce**

1. Install chromebrew on a fresh chromeos system, and then try to install linuxheaders:

      ```shell
      crew install linuxheaders
      ```

      Output:

      ```
      linuxheaders: Linux headers for Chrome OS.
      Version: 4.14-1
      License: GPL-2
      Performing pre-flight checks...
      Precompiled binary available, downloading...
      Download failed with error 404: Not Found
      ```

**Expected behavior**
linuxheaders successfully download and install.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***

<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew kernel version: `4.14`
- Chromebrew running in container: `false`

- Chromebrew version: `1.44.4`
- Chromebrew prefix: `/usr/local/`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository:

- OS variant: `Chrome OS`
- OS version: `octopus-release/R112-15359.58.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**
When I ran `crew install` with -v, it seemed like it was trying to download from the correct URL, but it cut off the file extension at the end. It looked something like `https://gitlab.com/api/v4/projects/.../linuxheaders-4.14-1-chromeos-x86_64.` whereas the correct URL seems to have a `.tpxz` at the end.

**Comment by Zopolis4** [comment]
Looks like you missed some @satmandu https://gitlab.com/chromebrew/binaries/-/packages/4446278

**Comment by vmhl87** [comment]
After messing around a little I fixed it by changing the compression algorithm from `tar.zst` to `tpxz` inside `packages/linuxheaders.rb`

**Comment by Zopolis4** [comment]
Nice! That'll work as a good temporary fix for you and anyone else who encounters this issue, until we can fix it properly.

Just note that updating crew will undo your changes, so if you delete `linuxheaders` and want to install it again you'll have to redo that change, at least until a fix is merged.

**Comment by vmhl87** [comment]
sounds good. Thanks!
