### ISSUE TITLE
Unable to run an npm create command

### ISSUE THREAD

**Issue by LolzTheDev** [chromebrew/chromebrew#9427]
**Describe the bug**
When attempting to make a Next.JS (or a React, Vite, Nuxt, and etc.) app, there is a symlink error.

**To Reproduce**

1. I executed this command:

      ```shell
      npm create vite@latest
      ```

      Output:

      ```
      Need to install the following packages:
create-vite@5.2.1
Ok to proceed? (y) 
sh: 1: create-vite: Too many levels of symbolic links
npm ERR! code 127
npm ERR! path /home/chronos/user/MyFiles/Downloads
npm ERR! command failed
npm ERR! command sh -c create-vite

npm ERR! A complete log of this run can be found in: /home/chronos/user/.npm/_logs/2024-03-03T04_09_07_887Z-debug-0.log
      ```

**Expected behavior**
Create a Vite app

**Screenshots**
![image](https://github.com/chromebrew/chromebrew/assets/141521874/293a7b96-2621-4658-ae95-ad932d9e0dc2)

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.44.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ada05ea6b `Edge 122.0.2365.52-1 => 122.0.2365.59-1 (#9404) (3 days ago)`

- OS variant: `Chrome OS`
- OS version: `hatch-release/R116-15509.72.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
Not really

**Comment by satmandu** [comment]
Try installing `nodejs` with nodebrew.

`crew install nodebrew`

**Comment by LolzTheDev** [comment]
> Try installing `nodejs` with nodebrew.
> 
> `crew install nodebrew`

that's what i originally did

**Comment by satmandu** [comment]
Ah! Sorry!

You may not be able to run that command in `/home/chronos/user/MyFiles/Downloads` because that's a weird folder that is mounted from elsewhere on the filesystem.

Try making a folder in `~/` or on `/usr/local` and then running `npm create vite@latest` in there...

**Comment by LolzTheDev** [comment]
Alright, thanks for the advice!
