### ISSUE TITLE
When im installing chromebrew it asks me to clear usr/local. I say yes and VT2 restarts

### ISSUE THREAD

**Issue by hiii532** [chromebrew/chromebrew#9433]
**Describe the bug**

**To Reproduce**

1. I executed this command:

      ```
      CREW_FORCE_INSTALL=1 exec bash --init-file <(curl -Ls git.io/vddgY)
      ```

      Output:

      ```
      VT2 restarts
      ```

**Expected behavior**
Install chromebrew
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
-bash: crew: command not found
***

**Additional context**

What I think needs to be done:

      - [maybe switch to stable channel] step one
      - [idk] step two

**Comment by Zopolis4** [comment]
We do not support non-stable channels.
