### ISSUE TITLE
🐞 sed version 4.9-1 not installing

### ISSUE THREAD

**Issue by hiii532** [chromebrew/chromebrew#9434]
**Describe the bug**

**To Reproduce**

1. I executed this command:

      ```shell
      crew install sed
      ```

      Output:

      ```
      checksum mismatch :/ try again?
      ```

**Expected behavior**
install stream editor
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
-Architecture: 'x86_64'
-Processor vendor: GenuineIntel
-User Space '64-bit"
-Chromebrew Kernel Version: '5.4'
-Chromebrew Running In Container: 'false'

-Chromebrew Version: '1.40.7'
-Chromebrew Prefix: '/usr/local'
-Chrombrew libdir: '/usr/local/lib64'

-Last Update In Local Repository: 1eedba2 04 'Move Repo To Chromebrew Org (7 weeks ago)'

-OS Variant 'Chrome OS'
-OS Version 'dedede-release/R121-15699.72.0'
-OS Channel 'stable-channel'
***

**Comment by Zopolis4** [comment]
Please update your version of crew (`crew update`)
