### ISSUE TITLE
Blender crashed at install

### ISSUE THREAD

**Issue by monolithonadmin** [chromebrew/chromebrew#9450]
I have installed successfully, but when I try to run it does not work. And I see this in the log:

`# Blender 3.0.1, Commit date: 2022-01-25 17:19, Hash dc2d18018171

# backtrace
blender(BLI_system_backtrace+0x20) [0xb0b3dd0]
blender() [0x10bad3a]
/usr/local/lib64/libc.so.6(+0x3cd10) [0x7aa55b89ed10]
blender() [0x1505639]
/usr/local/lib64/libLLVM-17.so(_ZN4llvm12PassRegistry12registerPassERKNS_8PassInfoEb+0x3bb) [0x7aa53b25192b]
/usr/local/lib64/libLLVM-17.so(+0x77a07fb) [0x7aa53ec5c7fb]
/usr/local/lib64/libc.so.6(+0x8ae4b) [0x7aa55b8ece4b]
/usr/local/lib64/libLLVM-17.so(_ZN5polly21initializePollyPassesERN4llvm12PassRegistryE+0x47e) [0x7aa53ec2ad6e]
/usr/local/lib64/libLLVM-17.so(+0x7788ca1) [0x7aa53ec44ca1]
/lib64/ld-linux-x86-64.so.2(+0x5daf) [0x7aa55bd5adaf]
/lib64/ld-linux-x86-64.so.2(+0x5ea9) [0x7aa55bd5aea9]
/usr/local/lib64/libc.so.6(_dl_catch_exception+0xf9) [0x7aa55b9af439]
/lib64/ld-linux-x86-64.so.2(+0xcff3) [0x7aa55bd61ff3]
/usr/local/lib64/libc.so.6(_dl_catch_exception+0x9e) [0x7aa55b9af3de]
/lib64/ld-linux-x86-64.so.2(+0xd3a8) [0x7aa55bd623a8]
/usr/local/lib64/libc.so.6(+0x819e0) [0x7aa55b8e39e0]
/usr/local/lib64/libc.so.6(_dl_catch_exception+0x9e) [0x7aa55b9af3de]
/usr/local/lib64/libc.so.6(_dl_catch_error+0x34) [0x7aa55b9af4a4]
/usr/local/lib64/libc.so.6(+0x813fa) [0x7aa55b8e33fa]
/usr/local/lib64/libc.so.6(dlopen+0x77) [0x7aa55b8e3aa7]
/usr/local/lib64/libGLX_mesa.so.0(+0x753bd) [0x7aa55437c3bd]
/usr/local/lib64/libGLX_mesa.so.0(+0x556be) [0x7aa55435c6be]
/usr/local/lib64/libGLX_mesa.so.0(+0x7028f) [0x7aa55437728f]
/usr/local/lib64/libGLX_mesa.so.0(+0x579e5) [0x7aa55435e9e5]
/usr/local/lib64/libGLX_mesa.so.0(+0x57f06) [0x7aa55435ef06]
/usr/local/lib64/libGLX_mesa.so.0(+0x58454) [0x7aa55435f454]
/usr/local/lib64/libGLX_mesa.so.0(+0x585f5) [0x7aa55435f5f5]
blender(_ZN15GHOST_WindowX11C1EP15GHOST_SystemX11P9_XDisplayPKciijj18GHOST_TWindowStatePS_25GHOST_TDrawingContextTypebbbbb+0x900) [0x23a8450]
blender(_ZN15GHOST_SystemX1112createWindowEPKciijj18GHOST_TWindowState25GHOST_TDrawingContextType16GHOST_GLSettingsbbPK13GHOST_IWindow+0xaa) [0x23a560a]
blender(GHOST_CreateWindow+0x3e) [0x239fade]
blender() [0x14eaacf]
blender(wm_window_ghostwindows_ensure+0x2d) [0x14eac5d]
blender(WM_check+0x5e) [0x14bb3ae]
blender(wm_homefile_read_ex+0x35d) [0x14cc46d]
blender(WM_init+0x140) [0x14d37c0]
blender(main+0x2a8) [0xfa3ca8]
/usr/local/lib64/libc.so.6(+0x286c6) [0x7aa55b88a6c6]
/usr/local/lib64/libc.so.6(__libc_start_main+0x82) [0x7aa55b88a782]
blender() [0x10b769c]

# Python backtrace`

Do you have any idea how to fix it? Thank you

**Comment by satmandu** [comment]
Blender very likely needs a package update and rebuild....

**Comment by satmandu** [comment]
I tried the current version, but it doesn't work at all on our system. Your best bet is to try it in crostini...

**Comment by satmandu** [comment]
Here's the package file I used if you want to play around with it: 
```
require 'package'

class Blender < Package
  description 'Blender is the free and open source 3D creation suite.'
  homepage 'https://www.blender.org/'
  version '4.0.2'
  license 'GPL-2'
  compatibility 'x86_64'
  source_url 'https://mirror.clarkson.edu/blender/release/Blender4.0/blender-4.0.2-linux-x64.tar.xz'
  source_sha256 '5583a5588736da8858c522ef17fff5d73be59c47a6fe91ad29c6f3263e22086a'
  binary_compression 'tar.zst'

  binary_sha256({
     x86_64: '2ef554553a2f40d3fc4a68de2389502b087a0f79c0421acb2e3445dea3224f50'
  })

  depends_on 'sommelier' # L
  depends_on 'gcc_lib' # R
  depends_on 'glibc' # R
  depends_on 'libglvnd' # R
  depends_on 'libice' # R
  depends_on 'libsm' # R
  depends_on 'libx11' # R
  depends_on 'libxext' # R
  depends_on 'libxfixes' # R
  depends_on 'libxkbcommon' # R
  depends_on 'libxrender' # R
  depends_on 'libxt' # R
  depends_on 'libxxf86vm' # R
  depends_on 'mesa' # R
  depends_on 'ncurses' # R
  depends_on 'zlibpkg' # R
  depends_on 'zstd' # R

  no_shrink

  def self.install
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin"
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/share/blender"
    FileUtils.mv Dir['*'], "#{CREW_DEST_PREFIX}/share/blender"
    FileUtils.ln_s "#{CREW_PREFIX}/share/blender/blender", "#{CREW_DEST_PREFIX}/bin/blender"
  end

  def self.postinstall
    puts
    puts "Type 'blender' to get started.".lightblue
    puts
  end
end
```

**Comment by satmandu** [comment]
The error I get now is `blender: error while loading shared libraries: libtbb.so.2: ELF load command address/offset not properly aligned`...
