### ISSUE TITLE
Packages with removed dependencies

### ISSUE THREAD

**Issue by Zopolis4** [chromebrew/chromebrew#9456]
Came across this while trying to write a script-- I'm sure its indicative of a current lack of thorough testing, and tests could certainly be written to catch this.

Right now, let's just get the issue fixed.

Code I hacked together to get some nice error messages, could be used as the foundation of a test if need be. At some point I do have plans for comprehensive testing of packages themselves (as opposed to the in-progress `crew` unit tests), but there's no harm in increasing our spotty coverage until then.
```ruby
#!/usr/bin/env ruby

# Add >LOCAL< lib to LOAD_PATH so that packages can be loaded
$LOAD_PATH.unshift '../lib'

require_relative '../lib/package'

Dir.glob('../packages/*.rb').each do |filename|
  pkg = Package.load_package(filename)
  begin
    dependencies = pkg.get_deps_list
  rescue Errno::ENOENT => e
    puts "#{pkg.name} depends on removed package #{e.to_s[/\/packages\/(\w+)\.rb/, 1]}"
  end
end
```

Affected packages:
```
dexed depends on removed package dub
obs depends on removed package qtsvg
plplot depends on removed package qtsvg
stellarium depends on removed package qtlocation
```

I ran the code on all architectures, so these should be the only broken packages.

**Comment by yeesterPlus** [comment]
nautilus has a missing dependency called: `64/tracker-3.0/libtracker-parser-libicu.so` in old tracker-3.0

**Comment by yest5xjquvf2** [comment]
somehow you blocked non spam
