### ISSUE TITLE
Inkscape dependencey not installed properley

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9472]
**Describe the bug**
inkscape dependencey not installed

**To Reproduce**

1. I executed this command:

      ```shell
      inkscape
      ```

      Output:

      ```
      inkscape: error while loading shared libraries: libboost_filesystem.so.1.83.0: cannot open shared object file: No such file or directory

      ```

**Expected behavior**
I expected it to open

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.44.8`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 6c1545571 `Signal_desktop 6.48.1 => 7.1.1 (#9449) (4 days ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R122-15753.38.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**

What I think needs to be done:

      - Make chromebrew properley install libboost

**Comment by satmandu** [comment]
If installing `boost` doesn't fix the issue, you will have to rebuild inkscape. `crew install boost ; crew reinstall -s inkscape`

**Comment by satmandu** [comment]
The new PR fixes this, but you also have to run `source ~/.bashrc` before running inkscape after install.

**Comment by yeesterPlus** [comment]
rebuilding it errors

**Comment by yeesterPlus** [comment]
it broke nautilus

**Comment by satmandu** [comment]
Does the just merged build work? If not we need to rebuild GCC....

**Comment by yeesterPlus** [comment]
rebuild GCC
