### ISSUE TITLE
Gimp crashes

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9489]
**Describe the bug**
Gimp crashes on startup

**To Reproduce**

1. I executed this command:

      ```shell
      gimp
      ```

**Expected behavior**
I expected it to open gimp.

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.45.2`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 0812b92ad `Vivaldi 6.6.3271.48-1 => 6.6.3271.50-1 (#9481) (10 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R122-15753.46.0`
- OS channel: `stable-channel`

</details>

***

here is a video
https://drive.google.com/file/d/1QZmvBhEbeGMs80xeKbAMVE4QJUq2KDJS/view?usp=drive_link

**Comment by satmandu** [comment]
This is what I see from an M90 based container:
![image](https://github.com/chromebrew/chromebrew/assets/1096701/2bfaa8d5-d9cb-4e9f-927c-ad4367ed2aa0)

But it doesn't work in a M121 based container, because gdk_pixbug appears to be having an issue with `gcc_lib`, which is complaining about our GLIBC in M122, and so no icon images get shown in the app.

So the question is, do we need to rebuild gcc_lib specifically for newer milestones?
@Zopolis4 @supechicken666 @uberhacker Thoughts?

**Comment by Zopolis4** [comment]
We're getting pretty fragmented with our glibc handling-- might be worth looking into ripping the band-aid off and just distributing 2.35 and patching with patchelf.

**Comment by yeesterPlus** [comment]
M90 is windows, please no windows sublinux

**Comment by satmandu** [comment]
It would be easier to create a chroot than use patchelf for everything...

Patchelf... Breaks stuff.

**Comment by yeesterPlus** [comment]
debugging in terminal: https://drive.google.com/file/d/1Z71c37p4k6PUprnnIQSd0KowQtJT8jzh/view?usp=sharing

**Comment by yeesterPlus** [comment]
please, no chroot, they go hard on my drive

**Comment by Zopolis4** [comment]
I'd rather risk breakage from patchelf than deal with the speed penalties of a chroot...

But right now as things are broken let's continue with what we have now-- fix first, over-arching redesign later.

**Comment by skycocker** [comment]
Please reopen if this is actually valid, I’m just cleaning up after that spammer.

**Comment by uberhacker** [comment]
Thank you for jumping on this @skycocker!  Ready to get involved again? :)

**Comment by skycocker** [comment]
I’m afraid I’m not emotionally available for this at the moment. But I’ll keep an eye out every now and then ;)

Thank you so much, guys! And I’m sorry you have to deal with such things.
