### ISSUE TITLE
🐞 Bug Neovim fails to launch 

### ISSUE THREAD

**Issue by enter-dragon** [chromebrew/chromebrew#9511]
**Describe the bug**
After installing Neovim using Crew package manager (crew install neovim), attempting to run nvim results in the following error: nvim: error while loading shared libraries: /usr/local/lib64/libmsgpackc.so.2: cannot open shared object file: No such file or directory.

**To Reproduce**

Install Neovim using Crew package manager: crew install neovim.
Attempt to run Neovim: nvim.
Expected behavior
Neovim should launch successfully without any errors.

**Environment**

Chrome version: Version 122.0.6261.137 (Official Build) (64-bit)
```
crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `AuthenticAMD`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.45.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: a39ec41c3 `Set default 'binary_compression' to 'tar.zst', allow verbose option for all crew commands. (#9505) (5 hours ago)`

- OS variant: `Chrome OS`
- OS version: `zork-release/R122-15753.55.0`
- OS channel: `stable-channel`

</details>
```

**Additional context**

This issue occurs consistently after installing Neovim using Crew package manager.
It seems that Neovim is unable to locate the libmsgpackc.so.2 shared library after installation.
I'm running Chrome version 122.0.6261.137 (Official Build) (64-bit).

What I think needs to be done:

 Investigate why Neovim is unable to locate the libmsgpackc.so.2 shared library.
 Provide a fix or workaround to ensure that Neovim launches successfully after installation.

**Comment by yeesterPlus** [comment]
<details><summary>*</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `AuthenticAMD`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.45.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: a39ec41c3 `Set default 'binary_compression' to 'tar.zst', allow verbose option for all crew commands. (#9505) (5 hours ago)`

- OS variant: `Chrome OS`
- OS version: `zork-release/R122-15753.55.0`
- OS channel: `stable-channel`

</details>

**Comment by satmandu** [comment]
Working on a PR to update neovim... looks like some dependencies need updates as well...
