### ISSUE TITLE
Missing filelists and overmatching compatibility for glibc_build232 and glibc_build233

### ISSUE THREAD

**Issue by Zopolis4** [chromebrew/chromebrew#9524]
As per title, there are no filelists for `glibc_build232`. 

Additionally, it has compatibility marked as `all` despite not providing binaries for `i686`, and with our current glibc setup it will never provide binaries for `i686`, so we should probably mark it as incompatible.

**Comment by Zopolis4** [comment]
This is also the case for `glibc_build233`.

**Comment by satmandu** [comment]
This is now taken care of.

**Comment by Zopolis4** [comment]
It's still not fixed for `glibc_build223`, at a glance. Are you sure this is fixed?

**Comment by satmandu** [comment]
Note that the older glibc packages were renamed at some point, so while the archives those packages download still have for instance a glibc.filelist inside them.

But nobody on M97 (with Glibc 2.32) is using Chromebrew, so this is less of an issue than the other brokenness likely there.
