### ISSUE TITLE
feature request [caprine](https://github.com/sindresorhus/caprine/releases/download/v2.59.3/caprine_2.59.3_amd64.deb)

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9525]
please add caprine(messenger) as debian

**Comment by uberhacker** [comment]
Debian packages can be a bit tricky due to the directory structure of the binaries.  How about an [AppImage release](https://github.com/chromebrew/chromebrew/pull/9526)?
