### ISSUE TITLE
lib mount is gone from update

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9527]
sysinfo
- Architecture: x86_64 (x86_64)
- Processor vendor: GenuineIntel
- User space: 64-bit
- Chromebrew Kernel version: 5.15
- Chromebrew Running in Container: false

- Chromebrew version: 1.45.4
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: ef4b30831 Update tracker3.rb (4 days ago)

- OS variant: Chrome OS
- OS version: octopus-release/R122-15753.55.0
- OS channel: stable-channel

**Comment by Zopolis4** [comment]
Could you explain what the issue actually is?

**Comment by yeesterPlus** [comment]
it gets wiped/not found

**Comment by uberhacker** [comment]
If you keep posting issues without a full explanation, they will be closed immediately.  We cannot keep guessing what your issue is and we won't be asking repeatedly.
