### ISSUE TITLE
The Icons are broken

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9543]
![Screenshot 2024-03-25 22 29 53](https://github.com/chromebrew/chromebrew/assets/162846629/6992f599-25c2-4976-8779-8a802ac8face)
- Architecture: x86_64 (x86_64)
- Processor vendor: GenuineIntel
- User space: 64-bit
- Chromebrew Kernel version: 5.15
- Chromebrew Running in Container: false

- Chromebrew version: 1.45.10
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: 5f8643539 Add caprine package (#9526) (3 hours ago)

- OS variant: Chrome OS
- OS version: octopus-release/R122-15753.55.0
- OS channel: stable-channel

**Comment by satmandu** [comment]
I think this is a glibc compatibility issue with gdk_pixbuf... We need to figure out how to respin our glibc builds to fix this...

**Comment by uberhacker** [comment]
There is a FAQ about how to fix missing icons in Gimp.  See https://github.com/chromebrew/chromebrew/wiki/FAQ.

**Comment by yeesterPlus** [comment]
this is not GIMP

**Comment by yeesterPlus** [comment]
Inkscape
