### ISSUE TITLE
Feature request: apt-like packages from chromebrew

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9545]
please add apt support so, that people can install every app (apt_install command for apt package installation)

**Comment by uberhacker** [comment]
We already have limited support for deb packages, however, apt support is probably not well suited for this package manager.  We can reverse engineer packages to work with crew but the directory structure in Debian is different and the results may vary for binary builds.  This package manager is more suited for source builds so if the source code is available, it would make more sense to go that route, if possible.

**Comment by yeesterPlus** [comment]
whatabout putting your packages online, and making the .cpkg file format?

**Comment by uberhacker** [comment]
We have binaries at https://gitlab.com/chromebrew/binaries/-/packages.

**Comment by yeesterPlus** [comment]
but whatabout the looking up thing that apt does, and the a package type

**Comment by uberhacker** [comment]
You mean `crew search <package>`?

**Comment by yeesterPlus** [comment]
no, package repository sift instead of local packages

**Comment by uberhacker** [comment]
All available packages are searchable locally.

**Comment by yeesterPlus** [comment]
move them online, like debian devs do
