### ISSUE TITLE
404 error when downloading libva

### ISSUE THREAD

**Issue by ry755** [chromebrew/chromebrew#9559]
**Describe the bug**
Attempting to download the libva package results in a 404 Not Found error.

**To Reproduce**

1. I executed this command:

      ```shell
      crew install libva
      ```

      Output:

      ```
      libva: Libva is an implementation for VA-API (Video Acceleration API)
      https://01.org/linuxmedia
      Version: 2.21.0
      License: MIT
      Performing pre-flight checks...
      Precompiled binary available, downloading...
      Download failed with error 404: Not Found
      ```

**Expected behavior**
The package should be downloaded and installed.

***
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.46.0`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 40a10f8dd `Edge 123.0.2420.53-1 => 123.0.2420.65-1 (#9554) (11 hours ago)`

- OS variant: `Chrome OS`
- OS version: `kukui-release/R122-15753.55.0`
- OS channel: `stable-channel`

</details>

***

**Additional context**
This was found when attempting to install crew_launcher, which depends (or possibly depends on a package which depends) on libva.

**Comment by satmandu** [comment]
My mistake! The PR should take care of this...
