### ISSUE TITLE
please add the stuff specified in #9564

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9566]
please smartley auto add systemd, add snapd, and make brew-bios-editor
```
/
|
  `usr/
      |
        ` bin/
               |
                `  systemd
```
 when /usr/bin/systemd does not exist,do `sudo mount -o remount,rw /` and auto install it, after rebooting due to `sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 4` command working after it

**Comment by uberhacker** [comment]
This is not something we will do automatically.  If you want to write your own personal script to do it, that is fine, but we won't ship this request with crew.

**Comment by yeesterPlus** [comment]
auto as in the app will do it
