### ISSUE TITLE
unlock / and add systemd

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9572]
please unlock / and add systemd

**Comment by yeesterPlus** [comment]
and deleting the close funct

**Comment by xemulat** [comment]
Hey kid, please stop spamming issues, it's unnecessary and people are making fun of you on Twitter (lmao).

**Comment by yeesterPlus** [comment]
@xemulat 
> Hey kid, please stop spamming issues, it's unnecessary and people are making fun of you on Twitter (lmao).

please tell me who
(off topic)
