### ISSUE TITLE
please add systemd , crew-bios, and snapd

### ISSUE THREAD

**Issue by 12lyj7hr** [chromebrew/chromebrew#9574]
please add systemd, snapd, and make brew-bios-editor
```
/
|
  `usr/
      |
        ` bin/
               |
                `  systemd
```
 when /usr/bin/systemd does not exist,do `sudo mount -o remount,rw /` and auto install it, after rebooting due to `sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 4` command working after it

**Comment by yeesterPlus** [comment]
please don't do this

**Comment by 12lyj7hr** [comment]
why?

**Comment by supechicken** [comment]
@yeesterPlus Please stop abusing the issue tab, that will only make you look childish.
