### ISSUE TITLE
Blocked him, reported as an abuser to github, not much more I have time for now. Borderline is a horrible disorder.

### ISSUE THREAD

**Issue by yeesterPlus** [chromebrew/chromebrew#9585]
Blocked him, reported as an abuser to github, not much more I have time for now. Borderline is a horrible disorder.

_Originally posted by @skycocker in https://github.com/chromebrew/chromebrew/discussions/9503#discussioncomment-8962716_

**Comment by uberhacker** [comment]
STOP!
