### ISSUE TITLE
Not changing the input language

### ISSUE THREAD

**Issue by DrCode32** [chromebrew/chromebrew#9605]
Hi!
When I change the input language in FydeOS, in software like firefox, English is still written when I press the keyboard keys.
I want to type in Persian language in Firefox.
```
$ crew sysinfo 
fatal: your current branch 'main' does not have any commits yet
fatal: your current branch 'main' does not have any commits yet
- Architecture: x86_64 (x86_64)
- Processor vendor: GenuineIntel
- User space: 64-bit
- Chromebrew Kernel version: 5.4
- Chromebrew Running in Container: false

- Chromebrew version: 1.46.3
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: 

- OS variant: Chromium OS
- OS version: 
- OS channel: stable-channel
```

**Comment by satmandu** [comment]
I'm not a user of Chromebrew in other input languages.  maybe @supechicken might have some ideas?

Also, does this help at all?

https://support.mozilla.org/en-US/kb/use-firefox-another-language

**Comment by DrCode32** [comment]
> I'm not a user of Chromebrew in other input languages. maybe @supechicken might have some ideas?
> 
> Also, does this help at all?
> 
> https://support.mozilla.org/en-US/kb/use-firefox-another-language

No. This is for the dictionary and language representation.
I have this problem in other software.

**Comment by supechicken** [comment]
AFAIK sommelier (X11 apps in ChromeOS) does not work with ChromeOS built-in IME yet.

However you could try Wayland, which works with ChromeOS IME on recent version if I remember correctly

**Comment by DrCode32** [comment]
> However you could try Wayland, which works with ChromeOS IME on recent version if I remember correctly
How to emigrate to Willand?
Of course, I think I'm using Willand now, how to check?
