### ISSUE TITLE
🐞 Unable To Install Chromebrew While Having Installed An Alternative Firmware On Chromebook.

### ISSUE THREAD

**Issue by luhgarlicbread** [chromebrew/chromebrew#9613]
**Describe the bug**
With this bug, you are unable to install Chromebrew while having any sort of Alternative Firmware on your Chromebook as they are also located in /usr/local where, I assume, Chromebrew installs. View the following image:
![image](https://github.com/chromebrew/chromebrew/assets/94203982/11cd37e0-fee0-443b-9a19-f577e1e7fa71)
I am unable to answer the prompt Chromebrew provides.

**To Reproduce**

1. I executed this command:

      cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

      Then I installed the RW_LEGACY alternative ChromeOS firmware, of which does not need WP to be disabled for.

**Expected behavior**
I expect Chromebrew to not need me to give up my alternative firmware to use it. Might as well only use the alternative firmware for Linux and just not have Chromebrew & Linux. (now that I think about it, that sounds like a good idea..)

I would paste "crew sysinfo -v", but crew isn't installed.

What I think needs to be done:

      - Chromebrew should be updated or provide a script to bypass this error, so I can install Chromebrew while still having an Alternative Firmware installed.

**Comment by Zopolis4** [comment]
You can set a different `CREW_PREFIX` to avoid installing in `/usr/local`, or copy out the firmware you want before installing chromebrew, then copy it back in.

**Comment by supechicken** [comment]
Please use the latest installation command provided in README.md, `curl -Ls ... | bash` is deprecated.

**Comment by luhgarlicbread** [comment]
> You can set a different `CREW_PREFIX` to avoid installing in `/usr/local`, or copy out the firmware you want before installing chromebrew, then copy it back in.

This is the strat. I install Chromebrew first, then the alternative firmware. Thanks! God bless you in Jesus’ name.
