### ISSUE TITLE
ChromeOS R123 updated to glibc 2.37, which breaks `crew`

### ISSUE THREAD

**Issue by supechicken** [chromebrew/chromebrew#9614]
Probably related: #9612

```text
chronos@maple / $ /lib/libc.so.6 
GNU C Library (Gentoo 2.37-r5 p5) stable release version 2.37.
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 10.2.0.
libc ABIs: UNIQUE ABSOLUTE
Minimum supported kernel: 3.2.0
For bug reporting instructions, please see:
<http://crbug.com/new>.

```

**Comment by satmandu** [comment]
I will be able to work on this some time Tuesday at the earliest...

**Comment by yest5xjquvf2** [comment]
let me contribute mine(X86): [libc.so.6.zip](https://github.com/chromebrew/chromebrew/files/15004426/libc.so.6.zip)

**Comment by yest5xjquvf2** [comment]
contrib your /lib64/libc.so.6 and list arch and if same than posted, don't repost

**Comment by yest5xjquvf2** [comment]
[mine as tar](https://gitlab.com/chromebrew/binaries/-/packages/24593684)

**Comment by yest5xjquvf2** [comment]
post the amd /lib64/libc.so.6

**Comment by yest5xjquvf2** [comment]
my libc.so.6 has been moved [here](https://gitlab.com/chromebrew/binaries/-/packages/24593684) by @satmandu

**Comment by satmandu** [comment]
> my libc.so.6 has been moved [here](https://gitlab.com/chromebrew/binaries/-/packages/24593684) by @satmandu

With all due respect... I didn't use your libc.so.6. I had already built the package for arm and then x86_64 earlier today...

**Comment by satmandu** [comment]
(And my builds of glibc 2.37 are just using stripped versions of the libc.so.6 already on the system...)

**Comment by yest5xjquvf2** [comment]
whatabout copy glibc
