### ISSUE TITLE
🐞 Bug Games like Minecraft can use the pointer fine but it doesn't lock

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#9620]
**Describe the bug**
Games like Minecraft can use the pointer fine but it won't lock. By lock I mean it can drag off of the window. Also, the `exo-pointer-lock` flag no longer exists.

**To Reproduce**

1. I executed this command:

      ```shell
      bash ~/Downloads/PrismLauncher-x86_64.AppImage
      ```

      Output:

      you don't need this output lmao

**Expected behavior**
Pointer locks in like it does in Crostini.

**Screenshots**
I don't think I can get a screenshot that would work here

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.46.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 

- OS variant: `Chrome OS`
- OS version: `octopus-release/R122-15753.55.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
I have removed a few packages so I could save some space but that isn't my issue because it still hasn't worked before

**Comment by Zopolis4** [comment]
This issue appears to be a duplicate of #7644.

**Comment by VenomousSteam81** [comment]
Ok, I will close this then
