### ISSUE TITLE
🐞 Bug Blender giving error about libtbb.so.2

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#9626]
**Describe the bug**
Running `blender` gives me `blender: error while loading shared libraries: libtbb.so.2: ELF load command address/offset not page-aligned`

**To Reproduce**

1. I executed this command:

      ```shell
      blender
      ```

      Output:

      ```
      blender: error while loading shared libraries: libtbb.so.2: ELF load command address/offset not page-aligned
      ```

**Expected behavior**
I expect Blender to run without any issues

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.46.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: f2fae48a7 `Rsync 3.2.7 => 3.3.0 (#9623) (7 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R122-15753.55.0`
- OS channel: `stable-channel`

</details>
***

**Screenshots**

***
![the error](https://github.com/chromebrew/chromebrew/assets/67353322/479935dd-b5de-4548-9a3c-0b8c6c48a99e)
***

**Additional context**
None

What I think needs to be done:

      - [ ] N/A

**Comment by VenomousSteam81** [comment]
I found out that `/usr/local/lib64/libtbb.so.2` didn't exist, regardless of the fact that I installed `tbb`. Now I'm getting the same error but with `libboost_python310.so.1.80.0`.

**Comment by VenomousSteam81** [comment]
It keeps giving me errors for different files but I'm just linking the closest thing I can find to the correct name. Probably will result in it not working but it's worth a shot.

**Comment by VenomousSteam81** [comment]
Yep, the linking will not work. Now it's giving me `blender: symbol lookup error: /usr/local/lib64/libboost_locale.so.1.80.0: undefined symbol: _ZTIN6icu_7310DateFormatE` because nothing is correct. At least I tried.

**Comment by yest5xjquvf2** [comment]
try flatpak once flatpak works
