### ISSUE TITLE
🐞 Bug: syntax error near unexpected toekn "newline": error when installing

### ISSUE THREAD

**Issue by Usinganame** [chromebrew/chromebrew#9647]
**Describe the bug**
Running the install command seems to not work

**To Reproduce**

1. I executed this command:

      ```shell
     Exec bash --init-file <(curl -Ls git.io/vddgy)
      ```

      Output:

      ```
      bash: /dev/fd/63: line 8: syntax error near unexpected token "newline"
      bash: /dev/fd/63: line 8: <!DOCTYPE html>
      ```

**Expected behavior**
I expected it to install

**Environment:**

***
I cannot get it install so the `crew` command will not work. The best I can do is the `uname -a` command

`Linux localhost 5.15.147-21519-g06a1de2a97d9 #1 SMP PREMPT Wed, 13 Apr 2024 04:32:12 +0000 x86_64 Intel(R) Celeron(R) N4020 CPU @ 1.10GHz Genuineintel GNU/Linux`
***

**Comment by blankuserrr** [comment]
How did you fix it?
