### ISSUE TITLE
🐞 Unit tests fail on updating crew_profile_base

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#9650]
This appears to be due to the timeout for the PAGER selection.

Do we need to add some sort of noninteractive flag like debian uses for use with apt so we can bypass this for in-container scripted usage?

@Zopolis4 You already had a variable for that...

**Comment by Zopolis4** [comment]
That didn't affect crew-profile-base, though.

**Comment by Zopolis4** [comment]
Also-- didn't we successfully update crew-profile-base in the past?

**Comment by satmandu** [comment]
I don't recall what happened the last time we updated it!
