### ISSUE TITLE
🐞 Bug nping: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by VenomousSteam81** [chromebrew/chromebrew#9653]
**Describe the bug**
When running `nping`, I get `nping: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`.

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash):

2. I executed the command(s) below:
      ```shell
      crew install nping
      nping
      ```

      Output:

      ```
      nping: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
      ```
**Expected behavior**
I expect nping to work properly

**Screenshots**
No screenshots are needed

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.46.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 3ce7c0854 `Add gopeed package (#9652) (4 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R123-15786.48.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] not sure

**Comment by VenomousSteam81** [comment]
Something to note: I linked `/usr/local/lib64/libssl.so` to `/usr/local/lib64/libssl.so.1.0.0` and I get a new error:
`nping: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`.
I did some looking around for similar issues and found issue #5235. I did some of the things a few comments said to do with same results.

**Comment by uberhacker** [comment]
Please use nmap instead.  This package also contains the nping command.
