### ISSUE TITLE
🐞 Bug CJK font is not displayed properly in Telegram

### ISSUE THREAD

**Issue by purofle** [chromebrew/chromebrew#9701]
**Describe the bug**
The fonts are blurry and Chinese characters are not displayed properly, it seems to use Serif fonts by default.

**To Reproduce**
1.install telegram and sommelier
2.launch telegram
```bash
chronos@atlas /usr/local/etc $ telegram 
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

**Expected behavior**
Fonts are displayed at the correct size

**Screenshots**
![image](https://github.com/chromebrew/chromebrew/assets/37149302/6b91a9db-0852-415a-8aff-bc7ae42f8277)

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.10`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.47.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: b08ae562b `Actually remove rubocop code from crew upload (#9698) (15 hours ago)`

- OS variant: `Chrome OS`
- OS version: `atlas-release/R123-15786.58.0`
- OS channel: `stable-channel`

</details>

***

**Comment by satmandu** [comment]
You might have to see if crostini works better for this. We do not do any testing at the moment on non-English systems.

Do you know which Chinese fonts are best for this usage?

Maybe you could work on packaging those for Chromebrew.
