### ISSUE TITLE
🐞 Bug `crew search` runs `print_source_bashrc`.

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#9751]
```
$ crew search gtk4
gtk4: GTK+ is a multi-platform toolkit for creating graphical user interfaces.

To finish the installation, please execute the following:
source ~/.bashrc
```

**Comment by satmandu** [comment]
![image](https://github.com/chromebrew/chromebrew/assets/1096701/10450098-d5ea-4085-b0f4-117110b986e6)

```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ grep -3 print_source_bashrc `which crew`
  require 'active_support/core_ext/object/blank'
  GnomePostinstall.run unless GnomePostinstall.gnome_packages.blank?

  if @pkg&.print_source_bashrc? || @pkg&.gnome?
    crewlog "@pkg.print_source_bashrc?:#{@pkg.print_source_bashrc?} @pkg.gnome?:#{@pkg.gnome?}"
    # Check to see if the trap was set in #{CREW_PREFIX}/etc/profile
    # from crew_profile_base, because otherwise, USR1 will kill crosh.
    if File.read("/proc/#{Process.ppid}/comm").include?('[trap set]')
```
search picsk up all the `@pkg` variables, so of course it will trigger anything that looks for those.

Do you want to blacklist this function during search, or is there a better way of handling this?

**Comment by satmandu** [comment]
e.g. you could set `in_search`...

**Comment by uberhacker** [comment]
This logic should only execute during postinstall, correct?  Maybe put it there instead?

**Comment by satmandu** [comment]
The logic is triggered as crew exits, as you want the reload bashrc function to only be active just before crew exits...

We could add an `at_exit` block inside install/reinstall, and move the code there...
