### ISSUE TITLE
🐞 Bug - Installation issue - OPENSSL_3.2.0 not found

### ISSUE THREAD

**Issue by monolithonadmin** [chromebrew/chromebrew#9923]
I tried to install chromebrew and the process stopped at this point:
OPENSSL_3.2.0 not found
![Screenshot 2024-06-07 19 34 53](https://github.com/chromebrew/chromebrew/assets/5338127/46286b80-3f17-4bcc-9f09-5efe8e6e9316)

I hope there's a way to fix it or any workaround is appreciated. Thank you

**Comment by uberhacker** [comment]
Can you kindly provide the output of `cat /etc/lsb-release`?

**Comment by monolithonadmin** [comment]
![2024_06_07 8_08 PM Office Lens](https://github.com/chromebrew/chromebrew/assets/5338127/08674f2e-6f68-4636-9d4a-f48395acdb65)

**Comment by uberhacker** [comment]
That is fine.  It appears we need openssl 3 for the latest 125 release.

**Comment by uberhacker** [comment]
We're working on it and hopefully, the upgraded openssl package will resolve your issue.  Stay tuned!

**Comment by satmandu** [comment]
More specifically, it looks like we will need at least OpenSSL 3.2.* — so I'm doing a build of 3.3.1 now to see if that breaks anything...

**Comment by monolithonadmin** [comment]
Great idea, I'm happy to test it.

**Comment by uberhacker** [comment]
@monolithonadmin: Give the install another try when you get a chance to make sure the latest openssl update fixes your issue.

**Comment by monolithonadmin** [comment]
![Uploading 2024_06_08 3_46 PM Office Lens.jpg…]()

**Comment by monolithonadmin** [comment]
![2024_06_08 3_46 PM Office Lens](https://github.com/chromebrew/chromebrew/assets/5338127/1620672e-e79b-4e86-8190-fd59d6e886cf)

**Comment by uberhacker** [comment]
Bummer, looks like we need to rebuild zlibpkg too @satmandu.

**Comment by satmandu** [comment]
Can you try the install with `bash -x <(curl -L git.io/vddgY) && . ~/.bashrc` please?

I would like to better understand where the install is failing...

**Comment by monolithonadmin** [comment]
![2024_06_08 4_51 PM Office Lens](https://github.com/chromebrew/chromebrew/assets/5338127/fcc33ee1-8252-4dae-9e15-7e47e656ac23)
I hope it helps

**Comment by satmandu** [comment]
Try it again? That's weird that the checksum doesn't match...

**Comment by monolithonadmin** [comment]
![2024_06_08 5_00 PM Office Lens](https://github.com/chromebrew/chromebrew/assets/5338127/7ceba667-ef4b-4e2c-b11a-10df117f0f05)
Second try

**Comment by satmandu** [comment]
What does `zstd --version` give?

**Comment by monolithonadmin** [comment]
![2024_06_08 5_17 PM Office Lens](https://github.com/chromebrew/chromebrew/assets/5338127/070acd84-b3ef-488b-9ffc-e10f8eaf387f)
