### ISSUE TITLE
🐞 Bug unable to install on stable channel

### ISSUE THREAD

**Issue by r0ddty** [chromebrew/chromebrew#9934]
**Describe the bug**
When installing Chromebrew on latest brand-new ChromeOS system on stable channel it refuses to install because "The beta, dev and canary channel are unsupported by Chromebrew"

**To Reproduce**
Steps to reproduce the behavior: Install latest stable ChromeOS with brunch, then try installing Chromebrew

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): VT-2

2. I executed the command(s) below:
      ```shell
     curl -L git.io/vddgY > install.sh
     cp install.sh /usr/local
     cd /usr/local
     bash install.sh
      ```

      Output:

      ```
      The beta, dev and canary channel are unsupported by Chromebrew.
      Run 'CREW_FORCE_INSTALL=1 exec bash --init-file <(curl -Ls git.io/vddgY)' to perform install anyway 
      ```
**Expected behavior**
Chromebrew installation

**Screenshots**
![image](https://github.com/chromebrew/chromebrew/assets/148452073/a767791f-33ce-49ff-9a68-2868f1fcad35)
![image](https://github.com/chromebrew/chromebrew/assets/148452073/567e1eba-c2df-412d-b471-2d8638898fdc)

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
chronos@brunch ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=33
CHROMEOS_ARC_VERSION=11865392
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={0BE68F68-A2F2-46B7-A7B4-B51B63F64FBA}
CHROMEOS_RELEASE_BOARD=zork-signed-mp-v9keys
CHROMEOS_RELEASE_BRANCH_NUMBER=53
CHROMEOS_RELEASE_BUILDER_PATH=zork-release/R125-15853.53.0
CHROMEOS_RELEASE_BUILD_NUMBER=15853
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=125
CHROMEOS_RELEASE_DESCRIPTION=15853.53.0 (Official Build) stable-channel zork 
CHROMEOS_RELEASE_KEYSET=mp-v9
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15853.53.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15853.53.0
***

**Additional context**
I've got the latest **stable** releases of both ChromeOS and Brunch, ChromeOS is on stable-channel so I have no idea about what is causing this

**Comment by supechicken** [comment]
Hello, please try the following command to bypass the error:
```shell
CREW_FORCE_INSTALL=1 bash <(curl -L git.io/vddgY) && . ~/.bashrc
```

Also, can you post the output of `ruby -e "p File.read('/etc/lsb-release')"` here? It can help us to find out what's going wrong there.

**Comment by uberhacker** [comment]
> Hello, please try the following command to bypass the error:
> 
> ```shell
> CREW_FORCE_INSTALL=1 bash <(curl -L git.io/vddgY) && . ~/.bashrc
> ```
> 
> Also, can you post the output of `ruby -e "p File.read('/etc/lsb-release')"` here? It can help us to find out what's going wrong there.

Why is this needed for the stable channel @supechicken?

**Comment by supechicken** [comment]
> Why is this needed for the stable channel @supechicken?

It can bypass the error in this case (an error message is not expected in this case but this is a workaround for it)

**Comment by r0ddty** [comment]
ok, it still isn't fixed
nothing changed 
but when I use this thing something weird happens:

> CREW_FORCE_INSTALL=1 bash <(curl -L git.io/vddgY) && . ~/.bashrc


https://github.com/chromebrew/chromebrew/assets/148452073/64dee032-a19a-4202-8017-bff067838d98

**Comment by supechicken** [comment]
> ok, it still isn't fixed nothing changed but when I use this thing something weird happens:
> 
> > CREW_FORCE_INSTALL=1 bash <(curl -L git.io/vddgY) && . ~/.bashrc
> 

You were executing the command that the installation command suggested, which is outdated and will not work anymore. Maybe try again with the new command above.

> @supechicken: Did you want to look into fixing the install so we don't need `CREW_FORCE_INSTALL=1`?

Working on it now...
